//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class APEXSQL_LOG_LOGIN
    {
        public int SPID { get; set; }
        public Nullable<System.DateTime> LOGIN_TIME { get; set; }
        public string LOGIN_NAME { get; set; }
        public string CLIENT_HOST { get; set; }
        public string APPLICATION_NAME { get; set; }
        public string SERVER_NAME { get; set; }
    }
}
