//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class APEXSQL_LOG_STRINGS
    {
        public int COL_TYPE { get; set; }
        public string COL_NAME { get; set; }
        public string SERVER_NAME { get; set; }
    }
}
