//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_01Luongtmp012_0009
    {
        public int ma_kh { get; set; }
        public short ma_user { get; set; }
        public short ma_user1 { get; set; }
        public string Manv { get; set; }
        public string Ten { get; set; }
        public int OP { get; set; }
        public int ok { get; set; }
        public int INS_ED { get; set; }
        public string chucvu { get; set; }
        public int bo_phan { get; set; }
        public string cmt { get; set; }
        public System.DateTime ngayvl { get; set; }
        public string mstcn { get; set; }
        public decimal luongcb { get; set; }
        public decimal nuoicon { get; set; }
        public decimal pccv { get; set; }
        public decimal antrua { get; set; }
        public decimal dienthoai { get; set; }
        public decimal xangxe { get; set; }
        public decimal phucapkhac { get; set; }
        public decimal trangphuc { get; set; }
        public decimal phucaptrn { get; set; }
        public decimal t150 { get; set; }
        public decimal t200 { get; set; }
        public decimal t300 { get; set; }
        public decimal thuong { get; set; }
        public decimal tongluong { get; set; }
        public decimal ngaycong { get; set; }
        public decimal ncthucte { get; set; }
        public decimal g150 { get; set; }
        public decimal g200 { get; set; }
        public decimal g300 { get; set; }
        public decimal tntt { get; set; }
        public decimal tnct { get; set; }
        public decimal luongbh { get; set; }
        public decimal bhxh { get; set; }
        public decimal bhyt { get; set; }
        public decimal bhtn { get; set; }
        public decimal kpcd { get; set; }
        public decimal bhxh_ld { get; set; }
        public decimal bhyt_ld { get; set; }
        public decimal bhtn_ld { get; set; }
        public decimal cong_ld { get; set; }
        public decimal banthan { get; set; }
        public decimal nguoipt { get; set; }
        public decimal tntt_cn { get; set; }
        public decimal thuetncn_pn { get; set; }
        public decimal tu { get; set; }
        public decimal thuclinh { get; set; }
        public string ky { get; set; }
        public string Tong { get; set; }
        public string gc { get; set; }
        public short DVCS { get; set; }
        public int Nhom { get; set; }
        public System.DateTime datetime { get; set; }
        public decimal f_identity { get; set; }
        public System.DateTime thangnam { get; set; }
    }
}
