//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_1_hachtoanLuong_1_2
    {
        public string TK_no { get; set; }
        public string TK_Co { get; set; }
        public int km { get; set; }
        public Nullable<decimal> PS_NO1 { get; set; }
        public Nullable<int> bo_phan { get; set; }
    }
}
