//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_1_hachtoanLuongTAM_1_3
    {
        public Nullable<int> STT { get; set; }
        public string TK_no { get; set; }
        public string TK_co { get; set; }
        public Nullable<decimal> ps_no1 { get; set; }
        public Nullable<decimal> USD { get; set; }
        public decimal f_identity { get; set; }
        public int KM { get; set; }
        public Nullable<int> bo_phan { get; set; }
    }
}
