//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_1BienThem
    {
        public decimal TR1 { get; set; }
        public decimal TR2 { get; set; }
        public decimal TR3 { get; set; }
        public decimal TR4 { get; set; }
        public decimal TR5 { get; set; }
        public decimal TR6 { get; set; }
        public decimal TR7 { get; set; }
        public decimal TR8 { get; set; }
        public decimal TR9 { get; set; }
        public decimal TR10 { get; set; }
        public decimal TR11 { get; set; }
        public decimal TR12 { get; set; }
        public decimal TR13 { get; set; }
        public decimal TR14 { get; set; }
        public decimal TR15 { get; set; }
        public decimal TR16 { get; set; }
        public decimal TR17 { get; set; }
        public decimal TR18 { get; set; }
        public decimal f_identity { get; set; }
        public System.DateTime DATETIME { get; set; }
        public System.DateTime thangnam { get; set; }
    }
}
