//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_1LgNhom008
    {
        public int nhan_su { get; set; }
        public short ma_user { get; set; }
        public short ma_user1 { get; set; }
        public string Manv { get; set; }
        public string Ten { get; set; }
        public int OP { get; set; }
        public int ok { get; set; }
        public int INS_ED { get; set; }
        public decimal TR1 { get; set; }
        public decimal TR2 { get; set; }
        public decimal TR3 { get; set; }
        public decimal TR4 { get; set; }
        public decimal TR5 { get; set; }
        public decimal TR6 { get; set; }
        public decimal TR7 { get; set; }
        public decimal TR8 { get; set; }
        public decimal TR9 { get; set; }
        public decimal TR10 { get; set; }
        public decimal TR11 { get; set; }
        public decimal TR12 { get; set; }
        public decimal TR13 { get; set; }
        public decimal TR14 { get; set; }
        public int TR15 { get; set; }
        public int TR16 { get; set; }
        public string Bophan { get; set; }
        public short DVCS { get; set; }
        public int Nhom { get; set; }
        public System.DateTime datetime { get; set; }
        public decimal f_identity { get; set; }
        public System.DateTime thangnam { get; set; }
    }
}
