//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_1LgNhom009
    {
        public int ma_kh { get; set; }
        public short ma_user { get; set; }
        public short ma_user1 { get; set; }
        public string Manv { get; set; }
        public string Ten { get; set; }
        public int OP { get; set; }
        public int ok { get; set; }
        public int INS_ED { get; set; }
        public System.DateTime TR1 { get; set; }
        public decimal tr2 { get; set; }
        public string khang_Ten { get; set; }
        public decimal tong { get; set; }
        public decimal T_Thuc { get; set; }
        public decimal TT { get; set; }
        public short DVCS { get; set; }
        public int Nhom { get; set; }
        public System.DateTime datetime { get; set; }
        public decimal f_identity { get; set; }
        public System.DateTime thangnam { get; set; }
    }
}
