//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_1LgNhom006
    {
        public int nhan_su { get; set; }
        public short ma_user { get; set; }
        public short ma_user1 { get; set; }
        public string Manv { get; set; }
        public string Ten { get; set; }
        public int OP { get; set; }
        public int ok { get; set; }
        public int INS_ED { get; set; }
        public int TR50 { get; set; }
        public int TR51 { get; set; }
        public int TR49 { get; set; }
        public string TR52 { get; set; }
        public System.DateTime TR5 { get; set; }
        public System.DateTime TR4 { get; set; }
        public System.DateTime TR7 { get; set; }
        public System.DateTime TR9 { get; set; }
        public decimal TR10 { get; set; }
        public string TR8 { get; set; }
        public string TR16 { get; set; }
        public decimal TR15 { get; set; }
        public decimal TR14 { get; set; }
        public decimal TR78 { get; set; }
        public decimal TR79 { get; set; }
        public decimal TR13 { get; set; }
        public decimal TR12 { get; set; }
        public decimal TR44 { get; set; }
        public decimal TR43 { get; set; }
        public decimal TR11 { get; set; }
        public decimal TR25 { get; set; }
        public decimal TR24 { get; set; }
        public decimal TR23 { get; set; }
        public decimal TR22 { get; set; }
        public decimal TR21 { get; set; }
        public decimal TR20 { get; set; }
        public decimal TR19 { get; set; }
        public decimal TR18 { get; set; }
        public decimal TR17 { get; set; }
        public decimal TR77 { get; set; }
        public decimal TR76 { get; set; }
        public decimal TR45 { get; set; }
        public decimal TR48 { get; set; }
        public decimal TR57 { get; set; }
        public decimal TR56 { get; set; }
        public decimal TR36 { get; set; }
        public decimal TR42 { get; set; }
        public decimal TR35 { get; set; }
        public decimal TR34 { get; set; }
        public decimal TR55 { get; set; }
        public decimal TR54 { get; set; }
        public decimal TR53 { get; set; }
        public decimal TR58 { get; set; }
        public decimal TR33 { get; set; }
        public decimal TR32 { get; set; }
        public decimal TR31 { get; set; }
        public decimal TR30 { get; set; }
        public decimal TR29 { get; set; }
        public decimal TR28 { get; set; }
        public decimal TR61 { get; set; }
        public decimal TR60 { get; set; }
        public decimal TR27 { get; set; }
        public decimal TR39 { get; set; }
        public decimal TR41 { get; set; }
        public int TR80 { get; set; }
        public int TR81 { get; set; }
        public decimal TR84 { get; set; }
        public decimal TR82 { get; set; }
        public decimal TR59 { get; set; }
        public decimal TR75 { get; set; }
        public decimal TR74 { get; set; }
        public string TR66 { get; set; }
        public string TR67 { get; set; }
        public string TR63 { get; set; }
        public string TR62 { get; set; }
        public string TR65 { get; set; }
        public string TR64 { get; set; }
        public string TR68 { get; set; }
        public string TR69 { get; set; }
        public short DVCS { get; set; }
        public int Nhom { get; set; }
        public System.DateTime datetime { get; set; }
        public decimal f_identity { get; set; }
        public System.DateTime thangnam { get; set; }
    }
}
