//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C__bangtamupdatehoadon1
    {
        public decimal f_identity { get; set; }
        public decimal so_luong { get; set; }
        public decimal ps_no1 { get; set; }
        public System.DateTime ngay_thc { get; set; }
        public decimal f_identity0 { get; set; }
    }
}
