//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C__KCPB_TT
    {
        public Nullable<decimal> f_identity { get; set; }
        public Nullable<decimal> SoPB { get; set; }
        public Nullable<decimal> PhanTram { get; set; }
        public string Sang_tk { get; set; }
        public Nullable<long> STT { get; set; }
        public Nullable<decimal> TieuThuc { get; set; }
        public int Loai_NX { get; set; }
    }
}
