//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_APIMOBIFONE_78
    {
        public string apiName { get; set; }
        public int apiid { get; set; }
        public string mota { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
        public string ContentType { get; set; }
    }
}
