//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_BANGDGIA
    {
        public decimal COUNTER { get; set; }
        public System.DateTime NGAY { get; set; }
        public int MA_THB { get; set; }
        public decimal DON_GIA { get; set; }
        public decimal f_identity { get; set; }
        public System.DateTime datetime { get; set; }
        public int ma_kh { get; set; }
    }
}
