//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_BANGTG
    {
        public System.DateTime ngay { get; set; }
        public decimal ty_gia1 { get; set; }
        public decimal ty_gia2 { get; set; }
        public decimal ty_gia3 { get; set; }
        public decimal ty_gia4 { get; set; }
        public decimal ty_gia5 { get; set; }
        public string ty_gia6 { get; set; }
        public decimal ty_gia7 { get; set; }
        public decimal ty_gia8 { get; set; }
        public decimal ty_gia9 { get; set; }
        public decimal ty_gia10 { get; set; }
        public decimal ty_gia11 { get; set; }
        public decimal ty_gia12 { get; set; }
        public decimal ty_gia13 { get; set; }
        public System.DateTime datetime { get; set; }
        public decimal f_identity { get; set; }
    }
}
