//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_baolanh
    {
        public byte cap { get; set; }
        public string ma { get; set; }
        public string ten { get; set; }
        public string sohd { get; set; }
        public int vviec { get; set; }
        public string tennh { get; set; }
        public string dcnh { get; set; }
        public string sotk { get; set; }
        public System.DateTime ngaybd { get; set; }
        public int songay { get; set; }
        public System.DateTime ngaykt { get; set; }
        public decimal tyle { get; set; }
        public decimal giatri { get; set; }
        public decimal phibl { get; set; }
        public int baolanh { get; set; }
        public decimal f_identity { get; set; }
        public short ma_user { get; set; }
        public short ma_user1 { get; set; }
        public System.DateTime datetime { get; set; }
        public short dvcs { get; set; }
        public int tiengui { get; set; }
        public byte status { get; set; }
        public System.DateTime ngayht { get; set; }
        public string ghichu { get; set; }
        public string LoaiBaolanh { get; set; }
        public decimal stt { get; set; }
        public short loaidl { get; set; }
        public short daxong { get; set; }
    }
}
