//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_banhang_1_1_0
    {
        public long recno { get; set; }
        public int invisible { get; set; }
        public int banhang { get; set; }
        public System.DateTime ngay { get; set; }
        public string chungtu { get; set; }
        public int ma_kh { get; set; }
        public string ghichu { get; set; }
        public decimal tongtien { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
    }
}
