//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_banhangct
    {
        public int banhang { get; set; }
        public int ma_thb { get; set; }
        public string ghichu { get; set; }
        public decimal soluong { get; set; }
        public decimal dongia { get; set; }
        public decimal thanhtien { get; set; }
        public string ktdb { get; set; }
        public decimal dg_svat { get; set; }
        public decimal vat { get; set; }
        public decimal tongtien { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
    }
}
