//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_bbnt
    {
        public System.DateTime ngay_thc { get; set; }
        public decimal tyle { get; set; }
        public int giaidoan { get; set; }
        public string ghichu { get; set; }
        public int trangthai { get; set; }
        public decimal f_identity { get; set; }
        public System.DateTime datetime { get; set; }
        public short ma_user { get; set; }
        public short ma_user1 { get; set; }
        public decimal stt { get; set; }
        public int vviec { get; set; }
        public string ten_file { get; set; }
        public byte[] tailieu { get; set; }
        public decimal size { get; set; }
        public int ploaihs { get; set; }
        public byte loai { get; set; }
        public int tthaihs { get; set; }
        public int loaihd { get; set; }
        public decimal ps_no1 { get; set; }
        public short loaidl { get; set; }
        public string ghichu1 { get; set; }
        public string dot_cu { get; set; }
        public int key_cu { get; set; }
        public System.DateTime ngayxacnhan { get; set; }
        public decimal tien_thanhly { get; set; }
        public string sobb { get; set; }
        public decimal thuhoitu { get; set; }
        public decimal thuctt { get; set; }
    }
}
