//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_BienThemCFG
    {
        public string Ten { get; set; }
        public string Kieu { get; set; }
        public decimal Ten_Cot { get; set; }
        public int Dai { get; set; }
        public int nDecima { get; set; }
        public int Change { get; set; }
        public int dvcs { get; set; }
        public decimal f_identity { get; set; }
        public string TenHT { get; set; }
        public string English { get; set; }
    }
}
