//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_BO
    {
        public int BO { get; set; }
        public string TEN { get; set; }
        public decimal DON_GIA { get; set; }
        public decimal SO_LUONG { get; set; }
        public string GHI_CHU { get; set; }
        public int MA_USER { get; set; }
        public System.DateTime DATETIME { get; set; }
        public decimal F_IDENTITY { get; set; }
        public int LOAI_TC { get; set; }
        public short DVCS { get; set; }
    }
}
