//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_cauhinh_misa
    {
        public int apiid { get; set; }
        public int cauhinh { get; set; }
        public string ncc { get; set; }
        public string effect { get; set; }
        public decimal stt { get; set; }
        public string batdau { get; set; }
        public string ketthuc { get; set; }
        public byte chitiet { get; set; }
        public string dieukien { get; set; }
        public string ghi_chu_ncc { get; set; }
        public string ghi_chu { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
    }
}
