//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_CCDC
    {
        public string MA { get; set; }
        public byte CAP { get; set; }
        public int CCDC { get; set; }
        public string TEN { get; set; }
        public string DV_DO { get; set; }
        public int NGUON { get; set; }
        public string NUOC_SX { get; set; }
        public string NAM_SD { get; set; }
        public System.DateTime NGAY_SD { get; set; }
        public string NOI_SD { get; set; }
        public string SO_HIEU { get; set; }
        public decimal SO_LUONG { get; set; }
        public decimal NG_GIA_VND { get; set; }
        public decimal NG_GIA_USD { get; set; }
        public decimal TL_KHAO { get; set; }
        public decimal TIEU_THUC { get; set; }
        public decimal TONG_KH { get; set; }
        public decimal CONLAI_VND { get; set; }
        public decimal CONLAI_USD { get; set; }
        public short DVCS { get; set; }
        public string CO { get; set; }
        public string TK_KHNO { get; set; }
        public string TK_KHCO { get; set; }
        public string TK_CCDC { get; set; }
        public int KHOANMUC { get; set; }
        public int BO_PHAN { get; set; }
        public int VVIEC { get; set; }
        public int LOAI_NX { get; set; }
        public int LOAI_TC { get; set; }
        public short MA_USER { get; set; }
        public string MA_TCTY { get; set; }
        public System.DateTime DATETIME { get; set; }
        public byte DISABLE { get; set; }
        public int vp_ddien { get; set; }
        public short MA_USER1 { get; set; }
        public decimal f_identity { get; set; }
        public int DVCS1 { get; set; }
        public byte linhvuc { get; set; }
    }
}
