//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_CHART
    {
        public string Ma { get; set; }
        public string Ten { get; set; }
        public byte SoCot { get; set; }
        public byte LoaiDoThi { get; set; }
        public string C_Sql { get; set; }
        public string HoanhDo { get; set; }
        public bool TTSql { get; set; }
        public int ma_repo { get; set; }
        public System.DateTime DateTime { get; set; }
        public decimal f_identity { get; set; }
    }
}
