//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ChamCong_Luong
    {
        public short dvcs { get; set; }
        public int ma_kh { get; set; }
        public int bo_phan { get; set; }
        public int loai_nx { get; set; }
        public decimal CongQD { get; set; }
        public decimal CongThucTe { get; set; }
        public decimal CongNgayThuong { get; set; }
        public decimal CongCN { get; set; }
        public decimal CongNM_CongTac { get; set; }
        public decimal CongThemGio { get; set; }
        public decimal PhepNam { get; set; }
        public decimal BuCong { get; set; }
        public decimal CongLe { get; set; }
        public decimal NghiLe_Luong { get; set; }
        public decimal CongAnTrua { get; set; }
        public decimal TongCongDcHuong { get; set; }
        public decimal CongKhoan { get; set; }
        public decimal TruTienHangHong { get; set; }
        public decimal TruChuyenCan { get; set; }
        public decimal ViPhamKyLuat { get; set; }
        public decimal KyQuy { get; set; }
        public decimal f_identity { get; set; }
        public System.DateTime datetime { get; set; }
        public short ma_user { get; set; }
        public short ma_user1 { get; set; }
        public int Thang { get; set; }
        public int Nam { get; set; }
        public System.DateTime Ngay_thc { get; set; }
    }
}
