//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_CHAMNGON
    {
        public int chamngon { get; set; }
        public string VIETNAM { get; set; }
        public string ENGLISH { get; set; }
        public string tg_VIETNAM { get; set; }
        public string tg_ENGLISH { get; set; }
        public string CHINA { get; set; }
        public string tg_CHINA { get; set; }
        public string imagepath { get; set; }
        public string fcolor1 { get; set; }
        public string fcolor2 { get; set; }
        public System.DateTime tungay { get; set; }
        public System.DateTime denngay { get; set; }
        public bool amlich { get; set; }
        public bool special { get; set; }
        public long f_identity { get; set; }
    }
}
