//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Chuyen_doi_tai_khoan_Convert
    {
        public string tutk { get; set; }
        public string sangtk { get; set; }
        public short ma_user { get; set; }
        public short ma_user1 { get; set; }
        public int ws { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime datetime { get; set; }
        public decimal f_identity { get; set; }
    }
}
