//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_chatroommessage
    {
        public string wsname { get; set; }
        public string username { get; set; }
        public string messagetext { get; set; }
        public System.DateTime datetime { get; set; }
        public string read_users { get; set; }
        public decimal f_identity { get; set; }
    }
}
