//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_convert_bang
    {
        public string bangnguon { get; set; }
        public string bangdich { get; set; }
        public string cotnguon { get; set; }
        public string cotdich { get; set; }
        public byte cotkey { get; set; }
        public string ghichu { get; set; }
        public string dieukien { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
        public string databaseName { get; set; }
        public byte chithem { get; set; }
    }
}
