//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_CoquanBHXH
    {
        public short ma_user { get; set; }
        public short ma_user1 { get; set; }
        public System.DateTime datetao { get; set; }
        public System.DateTime datetime { get; set; }
        public int coquanbhxh { get; set; }
        public byte cap { get; set; }
        public string ma { get; set; }
        public string ten { get; set; }
        public string ghichu { get; set; }
        public int tinh { get; set; }
        public string matinh { get; set; }
        public string MaDBHC { get; set; }
        public string Loai { get; set; }
        public long f_identity { get; set; }
    }
}
