//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_congvan
    {
        public System.DateTime ngay_thc { get; set; }
        public string So_cvan { get; set; }
        public string ghichu { get; set; }
        public string so_hdong { get; set; }
        public int ma_kh { get; set; }
        public System.DateTime ngay_xly { get; set; }
        public string ghichu_xly { get; set; }
        public byte xuly { get; set; }
        public decimal f_identity { get; set; }
        public System.DateTime datetime { get; set; }
        public short ma_user { get; set; }
        public short ma_user1 { get; set; }
        public decimal stt { get; set; }
        public int vviec { get; set; }
        public string daidien { get; set; }
        public int giaidoan { get; set; }
        public short loaidl { get; set; }
    }
}
