//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_DANHMUC
    {
        public int cap { get; set; }
        public string ma { get; set; }
        public string ten { get; set; }
        public string tendm { get; set; }
        public string alia { get; set; }
        public string ten_vn { get; set; }
        public string ten_eng { get; set; }
        public string key_field { get; set; }
        public int hfit { get; set; }
        public int init_use { get; set; }
        public string tag_def { get; set; }
        public string co1 { get; set; }
        public int bsc { get; set; }
        public int copyra { get; set; }
        public int download { get; set; }
        public int ma_user { get; set; }
        public int quyen_id { get; set; }
        public string path { get; set; }
        public decimal sttdm { get; set; }
        public string ten_ngan { get; set; }
        public int fit_type { get; set; }
        public int barcode { get; set; }
        public int eff_fix { get; set; }
        public int sql { get; set; }
        public int sql2 { get; set; }
        public int no_sql { get; set; }
        public int sqldvcs { get; set; }
        public int combo { get; set; }
        public int hs_lui_ten { get; set; }
        public int mincode { get; set; }
        public int maxcode { get; set; }
        public string image { get; set; }
        public int norequery { get; set; }
        public int f_identity { get; set; }
        public string sum_fields { get; set; }
        public System.DateTime datetime { get; set; }
        public string VIETNAM { get; set; }
        public string ENGLISH { get; set; }
        public string JAPAN { get; set; }
        public string CHINA { get; set; }
        public string tat_VIETNAM { get; set; }
        public string tat_ENGLISH { get; set; }
        public string tat_CHINA { get; set; }
        public string tat_JAPAN { get; set; }
        public short allowfilter { get; set; }
        public short userpermission { get; set; }
        public byte isMergeRepli { get; set; }
        public int seed { get; set; }
        public byte step { get; set; }
        public string loaddata { get; set; }
        public string quyen { get; set; }
        public byte FRX { get; set; }
        public byte import_Luong { get; set; }
        public bool dele_data { get; set; }
        public string dbName { get; set; }
        public string sortBy { get; set; }
        public short KCDK { get; set; }
        public decimal sttdmerp { get; set; }
        public bool chohrm { get; set; }
    }
}
