//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_DinhMuc01201508
    {
        public int ok { get; set; }
        public int Loai_tc { get; set; }
        public int ma_thb { get; set; }
        public decimal So_luong { get; set; }
        public decimal SoTrenDM { get; set; }
        public short dvcs { get; set; }
        public int Nhom_kc { get; set; }
        public int DinhMuc { get; set; }
        public decimal f_identity { get; set; }
        public System.DateTime datetime { get; set; }
        public string DV_do { get; set; }
        public decimal HS_TieuHao { get; set; }
    }
}
