//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_DINHMUC1
    {
        public int DINHMUC1 { get; set; }
        public short NHOM { get; set; }
        public int LOAI_TC { get; set; }
        public int MA_THB { get; set; }
        public decimal SO_LUONG { get; set; }
        public int SLDM { get; set; }
        public byte PT_TGIAN { get; set; }
        public byte PHAN_LOAI { get; set; }
        public byte DONG_GOI { get; set; }
        public byte IDOP { get; set; }
        public short DVCS { get; set; }
        public decimal DON_GIA { get; set; }
        public decimal DON_GIATB { get; set; }
        public decimal DON_GIATBU { get; set; }
        public decimal TH_TIEN { get; set; }
        public int KHOANMUC { get; set; }
        public int BO_PHAN { get; set; }
        public int VVIEC { get; set; }
        public int LOAI_NX { get; set; }
        public decimal PT_HAOHUT { get; set; }
        public int NHAN_SU { get; set; }
        public System.DateTime DATETIME { get; set; }
        public decimal f_identity { get; set; }
    }
}
