//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_dl_ccong
    {
        public int Nhan_Su { get; set; }
        public int Bo_phan { get; set; }
        public int Ra_vao { get; set; }
        public System.DateTime Ngay_thc { get; set; }
        public System.DateTime datetime { get; set; }
        public decimal f_identity { get; set; }
        public short Ma_user { get; set; }
        public short Ma_User1 { get; set; }
    }
}
