//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_dongcuoi
    {
        public string ten { get; set; }
        public string ten_eng { get; set; }
        public System.DateTime DateTime { get; set; }
        public int idtxtcuoi { get; set; }
        public string chuky_dongdau { get; set; }
        public string chuky_dongdau_eng { get; set; }
        public int Loai { get; set; }
        public string Kho { get; set; }
        public string LoaiKho { get; set; }
        public string TenNguoiKy { get; set; }
        public string NgayThangNam { get; set; }
        public int f_identity { get; set; }
        public string china { get; set; }
    }
}
