//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_DUTIENTE
    {
        public string MA_TK0 { get; set; }
        public Nullable<decimal> DUVND { get; set; }
        public Nullable<decimal> DUNTE { get; set; }
        public Nullable<decimal> CHENHLECH { get; set; }
        public string NTE { get; set; }
        public Nullable<decimal> MA_KH { get; set; }
        public decimal f_identity { get; set; }
        public Nullable<decimal> ty_gia { get; set; }
    }
}
