//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_DV
    {
        public string ma { get; set; }
        public string DIEN_GIAI { get; set; }
        public decimal TY_GIA { get; set; }
        public byte CO { get; set; }
        public System.DateTime NGAY { get; set; }
        public decimal TY_GIA1 { get; set; }
        public decimal THANG1 { get; set; }
        public decimal THANG2 { get; set; }
        public decimal THANG3 { get; set; }
        public decimal THANG4 { get; set; }
        public decimal THANG5 { get; set; }
        public decimal THANG6 { get; set; }
        public decimal THANG7 { get; set; }
        public decimal THANG8 { get; set; }
        public decimal THANG9 { get; set; }
        public decimal THANG10 { get; set; }
        public decimal THANG11 { get; set; }
        public decimal THANG12 { get; set; }
        public string FTY_GIA { get; set; }
        public System.DateTime DATETIME { get; set; }
        public int bo_phan { get; set; }
        public decimal f_identity { get; set; }
        public string tenvt { get; set; }
        public string tenle { get; set; }
    }
}
