//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_DVCS
    {
        public string ma { get; set; }
        public string ten { get; set; }
        public short dvcs { get; set; }
        public System.DateTime datetime { get; set; }
        public System.DateTime Ngay_khoa { get; set; }
        public int bo_phan { get; set; }
        public int user_saochep { get; set; }
        public int f_identity { get; set; }
        public string CotMacDinhView { get; set; }
    }
}
