//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_FileAttachBkav
    {
        public decimal keyhd { get; set; }
        public string fileName { get; set; }
        public string fileExt { get; set; }
        public string fileContents { get; set; }
        public byte fileType { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
    }
}
