//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_formobj
    {
        public string VIETNAM { get; set; }
        public string ma { get; set; }
        public int f_identity { get; set; }
        public string form { get; set; }
        public string loai { get; set; }
        public int vitrixx { get; set; }
        public int vitriyy { get; set; }
        public int docao { get; set; }
        public int dorong { get; set; }
        public string proc_ { get; set; }
        public string when_ { get; set; }
        public string refresh_ { get; set; }
        public string tooltip { get; set; }
        public string image { get; set; }
        public string datasource { get; set; }
        public string forecolor { get; set; }
        public short update_ { get; set; }
        public string datatype { get; set; }
        public string hotkey { get; set; }
        public string fromlist { get; set; }
        public string control { get; set; }
        public int tabindex { get; set; }
        public string mask { get; set; }
        public int cap { get; set; }
        public string font { get; set; }
        public string backcolor { get; set; }
        public string defaultvalue { get; set; }
        public short anhientheodanhmuc { get; set; }
        public string imagelist { get; set; }
        public System.DateTime datetime { get; set; }
        public string ENGLISH { get; set; }
        public string C_Image { get; set; }
        public string C_NameButton { get; set; }
        public string invisibleuser { get; set; }
        public string readonlyuser { get; set; }
        public string guide { get; set; }
        public byte init_use { get; set; }
        public string CHINA { get; set; }
        public string JAPAN { get; set; }
        public string DllReferences { get; set; }
        public string Properties { get; set; }
    }
}
