//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_FormfitBtnProc
    {
        public int f_identity { get; set; }
        public string ma_btn { get; set; }
        public string dataSource { get; set; }
        public string proc_ { get; set; }
        public System.DateTime datetime { get; set; }
        public string quyen { get; set; }
        public string tooltip { get; set; }
    }
}
