//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_FORM
    {
        public string TEN { get; set; }
        public short FORM { get; set; }
        public string FRX_FILE { get; set; }
        public string TIT { get; set; }
        public byte TIEN_VND { get; set; }
        public string QUYEN { get; set; }
        public byte MACDINH { get; set; }
        public byte LOC_LOAICT { get; set; }
        public byte LOC_NGAY { get; set; }
        public byte LOC_CTU { get; set; }
        public byte LOC_CTGS { get; set; }
        public byte LOC_SOHD { get; set; }
        public byte LOC_BOPHAN { get; set; }
        public byte LOC_KHO { get; set; }
        public byte LOC_BTTHEM { get; set; }
        public byte LOC_SERIHD { get; set; }
        public byte NHAN_DOI { get; set; }
        public string WHERE_MEM { get; set; }
        public string XL_MEM { get; set; }
        public byte SODONG { get; set; }
        public byte DISABLE { get; set; }
        public string SLOAI_CT { get; set; }
        public short MA_USER { get; set; }
        public string IN_NHIEU { get; set; }
        public System.DateTime DATETIME { get; set; }
        public decimal f_identity { get; set; }
        public string ma { get; set; }
        public string C_image { get; set; }
        public short cap { get; set; }
        public string mau { get; set; }
        public string CHINA { get; set; }
        public string TIT_CHINA { get; set; }
    }
}
