//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_GIAOTIEPE
    {
        public decimal COUNTER { get; set; }
        public short MA_USER { get; set; }
        public string GIAOTIEP { get; set; }
        public byte ESUA { get; set; }
        public byte KSUA { get; set; }
        public byte DANGSUA { get; set; }
        public decimal f_identity { get; set; }
    }
}
