//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_HDDT_CONFIG_TOKEN_FUNC_WEBSERVICE
    {
        public string Func_Name { get; set; }
        public long ID { get; set; }
        public string Parameter { get; set; }
        public string Return_Type { get; set; }
        public string ghi_chu { get; set; }
        public string kq_tra_ve { get; set; }
        public int Unumber { get; set; }
        public short ma_user { get; set; }
        public short ma_user1 { get; set; }
        public int ws { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
    }
}
