//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_HDDT_CONFIG_FUNC_WEBSERVICE
    {
        public string FUNC_NAME { get; set; }
        public decimal ID { get; set; }
        public string PARAMETER { get; set; }
        public string RETURN_TYPE { get; set; }
        public string GHI_CHU { get; set; }
        public string KQ_TRA_VE { get; set; }
        public string URL { get; set; }
        public byte Unumber { get; set; }
        public int MA_USER { get; set; }
        public int MA_USER1 { get; set; }
        public int WS { get; set; }
        public System.DateTime DATE { get; set; }
        public System.DateTime DATETIME { get; set; }
        public decimal F_IDENTITY { get; set; }
    }
}
