//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_HDDT_STRUCT_XML_FUNC_SERVICE_1thue_v3
    {
        public string STRUCT_NAME { get; set; }
        public decimal ID { get; set; }
        public decimal ID_PARENT { get; set; }
        public decimal STT { get; set; }
        public string MO_THE { get; set; }
        public string NOI_DUNG { get; set; }
        public string DONG_THE { get; set; }
        public string DEF_NOI_DUNG { get; set; }
        public string NAME_UPDATE { get; set; }
        public byte BAT_BUOC { get; set; }
        public byte CHITIET { get; set; }
        public byte CAP { get; set; }
        public byte INVISIBLE { get; set; }
        public int MA_USER { get; set; }
        public int MA_USER1 { get; set; }
        public int WS { get; set; }
        public System.DateTime DATE { get; set; }
        public System.DateTime DATETIME { get; set; }
        public decimal F_IDENTITY { get; set; }
        public string dformat { get; set; }
        public string noidung { get; set; }
        public string dieukien { get; set; }
    }
}
