//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_HDDT_PARAMETER_STRUCT
    {
        public decimal ID { get; set; }
        public decimal ID_PARENT { get; set; }
        public decimal STT { get; set; }
        public string PARA_NAME { get; set; }
        public string PARA_VALUE { get; set; }
        public byte XML_STRUCT { get; set; }
        public string GHI_CHU { get; set; }
        public byte CAP { get; set; }
        public byte INVISIBLE { get; set; }
        public int MA_USER { get; set; }
        public int MA_USER1 { get; set; }
        public int WS { get; set; }
        public System.DateTime DATE { get; set; }
        public System.DateTime DATETIME { get; set; }
        public decimal F_IDENTITY { get; set; }
    }
}
