//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_history_edit
    {
        public string tableName { get; set; }
        public string columnName { get; set; }
        public string value0 { get; set; }
        public string value1 { get; set; }
        public long fidentity { get; set; }
        public string fkey { get; set; }
        public string captionCol { get; set; }
        public short ma_user { get; set; }
        public string addWhere { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
    }
}
