//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_history_erp2
    {
        public string tableName0 { get; set; }
        public string tableName1 { get; set; }
        public string keycol0 { get; set; }
        public string keycol1 { get; set; }
        public string colName { get; set; }
        public string value0 { get; set; }
        public string value1 { get; set; }
        public string valuestr0 { get; set; }
        public string valuesstr1 { get; set; }
        public int @operator { get; set; }
        public int ma_user { get; set; }
        public int ws { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
    }
}
