//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_hrm_hopdong
    {
        public string sohopdong { get; set; }
        public System.DateTime ngayky { get; set; }
        public System.DateTime ngaybd { get; set; }
        public System.DateTime ngaykt { get; set; }
        public string thoihan { get; set; }
        public int loaihd { get; set; }
        public int bo_phan { get; set; }
        public int vitri { get; set; }
        public decimal luongthu { get; set; }
        public decimal luongchinh { get; set; }
        public decimal stt { get; set; }
        public int nhanvien { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
        public System.DateTime datetao { get; set; }
        public long fquyetdinh { get; set; }
    }
}
