//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_hrm_hinhthuc
    {
        public int hinhthuc { get; set; }
        public string ma { get; set; }
        public string ten { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
        public short trangthai { get; set; }
        public int tunhom { get; set; }
        public int sangnhom { get; set; }
        public string ktudau { get; set; }
        public string tennhom { get; set; }
        public short tutrangthai { get; set; }
        public int nghi { get; set; }
        public short ma_user { get; set; }
        public short ma_user1 { get; set; }
        public System.DateTime datetao { get; set; }
        public byte nghits { get; set; }
    }
}
