//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_hrm_bienthem
    {
        public byte thang { get; set; }
        public short nam { get; set; }
        public int nhom { get; set; }
        public short dvcs { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
        public decimal luongcs { get; set; }
        public decimal ldbhxh { get; set; }
        public decimal ldbhyt { get; set; }
        public decimal ldbhtn { get; set; }
        public decimal ldkpcd { get; set; }
        public decimal dnbhxh { get; set; }
        public decimal dnbhyt { get; set; }
        public decimal dnbhtn { get; set; }
        public decimal dnkpcd { get; set; }
        public decimal gtbt { get; set; }
        public decimal gtpt { get; set; }
        public decimal hsthem { get; set; }
        public decimal congchuan { get; set; }
        public decimal antrua { get; set; }
        public decimal tcapdxcot { get; set; }
        public decimal tcapdxkot { get; set; }
    }
}
