//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_hrm_kyhieucc
    {
        public int kyhieu { get; set; }
        public string ma { get; set; }
        public string ten { get; set; }
        public string ghichu { get; set; }
        public System.DateTime datetime { get; set; }
        public short ma_user { get; set; }
        public long f_identity { get; set; }
        public string kyhieucc { get; set; }
        public decimal tinhcong { get; set; }
        public byte loai { get; set; }
    }
}
