//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_hrm_danhgia
    {
        public int nhanvien { get; set; }
        public short ma_user { get; set; }
        public short ma_user1 { get; set; }
        public System.DateTime datetao { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
        public decimal stt { get; set; }
        public System.DateTime ngay { get; set; }
        public int nam { get; set; }
        public int danhhieu { get; set; }
        public decimal diem { get; set; }
        public string hinhthuc { get; set; }
        public string dexuat { get; set; }
        public string ghichu { get; set; }
        public string nguoidg { get; set; }
    }
}
