//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_hrm_quyetdinh
    {
        public System.DateTime ngay_thc { get; set; }
        public string chung_tu { get; set; }
        public int nhanvien { get; set; }
        public int vitricu { get; set; }
        public int hinhthuc { get; set; }
        public string lydo { get; set; }
        public decimal giaitri { get; set; }
        public int vitri { get; set; }
        public short ma_user { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
        public byte[] filedinhkem { get; set; }
        public System.DateTime ngay_adtt { get; set; }
        public System.DateTime ngay_tluong { get; set; }
        public decimal luongvt { get; set; }
        public decimal luongnl { get; set; }
        public decimal dghqkd { get; set; }
        public decimal luongcb { get; set; }
        public decimal pcchucvu { get; set; }
        public decimal pctrnhiem { get; set; }
        public decimal thuongkpi { get; set; }
        public decimal thuonghqdt { get; set; }
        public decimal dganchinh { get; set; }
        public decimal dganphu { get; set; }
        public int bo_phan { get; set; }
        public int bo_phancu { get; set; }
        public short inquyetdinh { get; set; }
        public byte[] filequyetdinh { get; set; }
        public string dinhdang { get; set; }
        public string ghichu { get; set; }
        public byte tinhlg1lan { get; set; }
        public decimal stt { get; set; }
        public System.DateTime ngay_adden { get; set; }
        public int songaybh { get; set; }
        public int nghits { get; set; }
        public short ma_user1 { get; set; }
        public System.DateTime datetao { get; set; }
        public byte kobhxh { get; set; }
        public decimal pcvpp { get; set; }
        public decimal pcphuongtien { get; set; }
        public decimal pcantrua { get; set; }
        public decimal pckhac { get; set; }
        public decimal hsluong { get; set; }
        public decimal hschucvu { get; set; }
        public decimal hstrnhiem { get; set; }
        public decimal hskhac { get; set; }
        public decimal pcdienthoai { get; set; }
        public int quyetdinh { get; set; }
        public decimal hsvkhung { get; set; }
        public decimal hstnien { get; set; }
        public decimal hsdochai { get; set; }
        public decimal hsknhiem { get; set; }
        public int loaihd { get; set; }
        public decimal luongtthuan { get; set; }
    }
}
