//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_hrm_danhhieu
    {
        public byte CAP { get; set; }
        public string MA { get; set; }
        public string TEN { get; set; }
        public int VITRI { get; set; }
        public decimal ps_no1 { get; set; }
        public System.DateTime DATETIME { get; set; }
        public long f_identity { get; set; }
        public short ma_user { get; set; }
        public int danhhieu { get; set; }
        public short ma_user1 { get; set; }
        public System.DateTime datetao { get; set; }
    }
}
