//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_hrm_phuthuoc
    {
        public int nhanvien { get; set; }
        public string ten { get; set; }
        public string ghichu { get; set; }
        public int loai { get; set; }
        public System.DateTime ngaysinh { get; set; }
        public string diachi { get; set; }
        public string masothue { get; set; }
        public System.DateTime tungay { get; set; }
        public System.DateTime denngay { get; set; }
        public short ma_user { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
        public decimal stt { get; set; }
        public short ma_user1 { get; set; }
        public System.DateTime datetao { get; set; }
        public int quoctich { get; set; }
        public string sokhaisinh { get; set; }
        public string quyenkhaisinh { get; set; }
        public int quocgia { get; set; }
        public int tinh { get; set; }
        public int quan { get; set; }
        public int phuong { get; set; }
    }
}
