//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_hrm_vitri
    {
        public byte CAP { get; set; }
        public string MA { get; set; }
        public string TEN { get; set; }
        public int VITRI { get; set; }
        public decimal SO_LUONG { get; set; }
        public int BO_PHAN { get; set; }
        public System.DateTime DATETIME { get; set; }
        public long f_identity { get; set; }
        public int hopdongmau { get; set; }
        public int kpi { get; set; }
        public int kpi2 { get; set; }
        public int chedochinh { get; set; }
        public string tenvt { get; set; }
        public int Bienche { get; set; }
        public short ma_user { get; set; }
        public short ma_user1 { get; set; }
        public System.DateTime datetao { get; set; }
        public string motavitri { get; set; }
    }
}
