//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_hrm_bangcap
    {
        public int nhanvien { get; set; }
        public string ten { get; set; }
        public short ma_user { get; set; }
        public short ma_user1 { get; set; }
        public System.DateTime datetao { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
        public System.DateTime ngay { get; set; }
        public int truong { get; set; }
        public int TrinhDoCM { get; set; }
        public int hocvi { get; set; }
        public int LoaiTN { get; set; }
        public int nganhdt { get; set; }
        public System.DateTime tungay { get; set; }
        public System.DateTime denngay { get; set; }
        public string diachi { get; set; }
        public string ghichu { get; set; }
        public string he { get; set; }
        public decimal stt { get; set; }
        public int ungvien { get; set; }
    }
}
