//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_hrm_nhanvien_1_6_0
    {
        public long recno { get; set; }
        public int invisible { get; set; }
        public byte cap { get; set; }
        public string ma { get; set; }
        public string ten { get; set; }
        public int nhanvien { get; set; }
        public int mauv { get; set; }
        public string diachi { get; set; }
        public string ma_gtgt { get; set; }
        public System.DateTime ngaycapcmt { get; set; }
        public string noicapcmt { get; set; }
        public int gioitinh { get; set; }
        public System.DateTime ngaysinh { get; set; }
        public byte[] fileanh { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public System.DateTime ngaybd { get; set; }
        public byte[] filehopdong { get; set; }
        public string masothue { get; set; }
        public string mabhxh { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
        public int vitri { get; set; }
        public string TKHOAN_NH { get; set; }
        public string TenNganHang { get; set; }
        public string DiaChiNH { get; set; }
        public string chinhanh_ngh { get; set; }
        public int tinh { get; set; }
        public int quanhuyen { get; set; }
        public int ma_kh { get; set; }
        public decimal hsdochai { get; set; }
        public decimal hstrnhiem { get; set; }
        public decimal hsvkhung { get; set; }
        public decimal hstnien { get; set; }
        public decimal luongcb { get; set; }
        public decimal pcvpp { get; set; }
        public decimal hsknhiem { get; set; }
        public int nhom { get; set; }
        public byte trangthai { get; set; }
        public int bo_phan { get; set; }
        public System.DateTime ngaykiemnhiem { get; set; }
        public decimal hsluong { get; set; }
        public decimal hschucvu { get; set; }
        public short bng { get; set; }
        public short cutru { get; set; }
        public decimal pcdienthoai { get; set; }
        public decimal pcphuongtien { get; set; }
        public string ghichu { get; set; }
        public int songuoi { get; set; }
        public string tenckhoan { get; set; }
        public int hinhthuc { get; set; }
        public decimal dienthoai { get; set; }
        public long quyetdinh { get; set; }
        public int nghits { get; set; }
        public string tenthue { get; set; }
        public string sobhyt { get; set; }
        public int dantoc { get; set; }
        public int quoc_gia { get; set; }
        public string mahogd { get; set; }
        public string noilv { get; set; }
        public int tinhtt { get; set; }
        public int quantt { get; set; }
        public int phuongtt { get; set; }
        public int quan { get; set; }
        public int phuong { get; set; }
        public string noio { get; set; }
        public int vung { get; set; }
        public int tinhkcb { get; set; }
        public int CoquanBHXH { get; set; }
        public string sohopdong { get; set; }
        public System.DateTime ngayky { get; set; }
        public int loaihd { get; set; }
        public System.DateTime ngaybatdau { get; set; }
        public System.DateTime ngayketthuc { get; set; }
        public byte trungdc { get; set; }
        public byte kobhxh { get; set; }
        public decimal tienkshc { get; set; }
        public int donviyte { get; set; }
        public int hinhthucluong { get; set; }
        public short dvcs { get; set; }
        public decimal pckhac { get; set; }
        public decimal luongtthuan { get; set; }
        public decimal pcchucvu { get; set; }
    }
}
