//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_hrm_cautrucnhomluong
    {
        public int nhom { get; set; }
        public decimal sttsx { get; set; }
        public string field { get; set; }
        public string VIETNAM { get; set; }
        public string ENGLISH { get; set; }
        public string type { get; set; }
        public int bwidth { get; set; }
        public int subwidth { get; set; }
        public byte ndecimal { get; set; }
        public byte gop { get; set; }
        public string proccode { get; set; }
        public string code { get; set; }
        public string fromlist { get; set; }
        public string from_alia { get; set; }
        public string from_field { get; set; }
        public string filt_field { get; set; }
        public string condition { get; set; }
        public decimal sttcode { get; set; }
        public string oldfield { get; set; }
        public string oldtype { get; set; }
        public int oldbwidth { get; set; }
        public byte oldndecimal { get; set; }
        public string relatedfieldproc { get; set; }
        public string relatedfieldcode { get; set; }
        public string from_list { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
        public byte iskeyfield { get; set; }
        public string code2 { get; set; }
        public short ktao { get; set; }
    }
}
