//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_hrm_nhomluong
    {
        public decimal stt { get; set; }
        public string VIETNAM { get; set; }
        public string ENGLISH { get; set; }
        public int nhom { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
        public string nhomVietNam { get; set; }
        public string nhomEnglish { get; set; }
        public int headerHeight { get; set; }
        public string tatVIETNAM { get; set; }
        public int ma_repo { get; set; }
    }
}
