//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_hrm_chamcong
    {
        public int chamcong { get; set; }
        public short nam { get; set; }
        public short thang { get; set; }
        public int nhanvien { get; set; }
        public System.DateTime ngay { get; set; }
        public string N1 { get; set; }
        public string N2 { get; set; }
        public string N3 { get; set; }
        public decimal congthoigian { get; set; }
        public decimal tongsongay { get; set; }
        public decimal nghikhongphep { get; set; }
        public string N4 { get; set; }
        public string N5 { get; set; }
        public string N6 { get; set; }
        public string N7 { get; set; }
        public string N8 { get; set; }
        public string N9 { get; set; }
        public string N10 { get; set; }
        public string N11 { get; set; }
        public string N12 { get; set; }
        public string N13 { get; set; }
        public string N14 { get; set; }
        public string N15 { get; set; }
        public string N16 { get; set; }
        public string N17 { get; set; }
        public string N18 { get; set; }
        public string N19 { get; set; }
        public string N20 { get; set; }
        public string N21 { get; set; }
        public string N22 { get; set; }
        public string N23 { get; set; }
        public string N24 { get; set; }
        public string N25 { get; set; }
        public string N26 { get; set; }
        public string N27 { get; set; }
        public string N28 { get; set; }
        public string N29 { get; set; }
        public string N30 { get; set; }
        public string N31 { get; set; }
        public string ghichu { get; set; }
        public short ma_user { get; set; }
        public short ma_user1 { get; set; }
        public System.DateTime datetime { get; set; }
        public System.DateTime datetao { get; set; }
        public long f_identity { get; set; }
        public decimal congphep { get; set; }
        public decimal congtangca { get; set; }
    }
}
