//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_hrm_xulythem
    {
        public string tenbang { get; set; }
        public int nhom { get; set; }
        public string cotnguon { get; set; }
        public string cotdich { get; set; }
        public string quydoi { get; set; }
        public string from_alia { get; set; }
        public string from_field { get; set; }
        public string filt_field { get; set; }
        public short dvcs { get; set; }
        public string ghi_chu { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
        public string dieukien { get; set; }
        public string giatri { get; set; }
        public byte iskeyfield { get; set; }
        public byte isgroup { get; set; }
        public string dkthem { get; set; }
    }
}
