//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_hrm_luongnhom1
    {
        public decimal luongcb { get; set; }
        public decimal luongtthuan { get; set; }
        public decimal congthoigian { get; set; }
        public decimal congphep { get; set; }
        public decimal congtangca { get; set; }
        public decimal congtong { get; set; }
        public decimal tienluong { get; set; }
        public decimal pcchucvu { get; set; }
        public decimal pcvpp { get; set; }
        public decimal pcphuongtien { get; set; }
        public decimal pcdienthoai { get; set; }
        public decimal pckhac { get; set; }
        public decimal tcapdxcot { get; set; }
        public decimal tcapdxkot { get; set; }
        public decimal sosuatan { get; set; }
        public decimal pcantrua { get; set; }
        public decimal tongtien { get; set; }
        public decimal tientinhbh { get; set; }
        public decimal nbhxh { get; set; }
        public decimal nbhyt { get; set; }
        public decimal nbhtn { get; set; }
        public decimal nkpcd { get; set; }
        public decimal dbhxh { get; set; }
        public decimal dbhyt { get; set; }
        public decimal dbhtn { get; set; }
        public decimal dkpcd { get; set; }
        public decimal tnnopthue { get; set; }
        public decimal songuoipt { get; set; }
        public decimal giamgc { get; set; }
        public decimal tntinhthue { get; set; }
        public decimal thuetncn { get; set; }
        public decimal tamung { get; set; }
        public decimal truythu { get; set; }
        public decimal tongkhautru { get; set; }
        public decimal thuclinh { get; set; }
        public int vitri { get; set; }
        public decimal quyetdinh { get; set; }
        public int hinhthuc { get; set; }
        public int nghits { get; set; }
        public int loaihd { get; set; }
        public int kobh { get; set; }
        public byte ok { get; set; }
        public System.DateTime ngay_thc { get; set; }
        public int nhanvien { get; set; }
        public Nullable<int> bo_phan { get; set; }
        public byte op { get; set; }
        public byte bh { get; set; }
        public short dvcs { get; set; }
        public short ma_user { get; set; }
        public short ma_user1 { get; set; }
        public int ws { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
    }
}
