//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_InvoicesMISA
    {
        public decimal partnerInvoiceID { get; set; }
        public string partnerInvoiceStringID { get; set; }
        public string InvoiceGuid { get; set; }
        public string invoiceForm { get; set; }
        public string invoiceSerial { get; set; }
        public string invoiceNo { get; set; }
        public string status { get; set; }
        public string Messlog { get; set; }
        public byte statushd { get; set; }
        public decimal keyhdtt { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
        public string MTC { get; set; }
        public byte editversion { get; set; }
    }
}
