//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_InvoicesViettel
    {
        public string keyhd { get; set; }
        public string hashString { get; set; }
        public string transactionID { get; set; }
        public string supplierTaxCode { get; set; }
        public string invoiceNo { get; set; }
        public string reservationCode { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
    }
}
