//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_KC_CTTheoNhom
    {
        public decimal CTTheo { get; set; }
        public decimal NhomKC { get; set; }
        public int hien { get; set; }
        public decimal f_identity { get; set; }
        public System.DateTime datetime { get; set; }
        public int dvcs { get; set; }
    }
}
