//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_KHPW
    {
        public string TEN { get; set; }
        public string TEN_ENG { get; set; }
        public string DIACHI { get; set; }
        public string DIACHIE { get; set; }
        public string SODANGKY { get; set; }
        public string PHONE { get; set; }
        public string MA_GTGT { get; set; }
        public string TK_NHANG { get; set; }
        public System.DateTime NGAY00 { get; set; }
        public string USR { get; set; }
        public byte DONGBO { get; set; }
        public byte SEPDATA { get; set; }
        public byte SEPDATA1 { get; set; }
        public byte USD { get; set; }
        public short DVCS { get; set; }
        public string NGAY_HH { get; set; }
        public byte BC_USD { get; set; }
        public byte TG { get; set; }
        public string TK_156 { get; set; }
        public string TK_BQ { get; set; }
        public string TK_FIFO { get; set; }
        public string TK_632 { get; set; }
        public string TK_211 { get; set; }
        public string TK_214 { get; set; }
        public string TK_911 { get; set; }
        public string TK_154 { get; set; }
        public string TK_155 { get; set; }
        public string TK_KC { get; set; }
        public string CASH { get; set; }
        public string TK_TGNO { get; set; }
        public string TK_TGCO { get; set; }
        public string TK_NTE { get; set; }
        public byte GVCK { get; set; }
        public string SKS { get; set; }
        public byte THANGTC { get; set; }
        public System.DateTime NGAY_LUU { get; set; }
        public byte KT_CNKHO { get; set; }
        public byte THU_CONG { get; set; }
        public string KTRA { get; set; }
        public byte SANL { get; set; }
        public byte NO_VL_SP { get; set; }
        public byte CPC { get; set; }
        public byte DMDV { get; set; }
        public short KM_NVL { get; set; }
        public int LMAGIN { get; set; }
        public int RMAGIN { get; set; }
        public byte FONTSIZE { get; set; }
        public string LUONG_SX1 { get; set; }
        public string LUONG_SX2 { get; set; }
        public string LUONG_SX3 { get; set; }
        public string VAR_GVTC { get; set; }
        public string VAR_GVBQ { get; set; }
        public string VAR_GVFF { get; set; }
        public byte GV_KHOTC { get; set; }
        public byte GV_KHOBQ { get; set; }
        public byte GV_KHOFF { get; set; }
        public System.DateTime MOCGV { get; set; }
        public byte KHONG_GV { get; set; }
        public string DVTT0 { get; set; }
        public byte LTGUSD { get; set; }
        public short IDSAOCHEP { get; set; }
        public string SCR_FILE { get; set; }
        public string REP_FILE { get; set; }
        public string VERSION { get; set; }
        public byte HINHTHUCSO { get; set; }
        public byte NKYKETOAN { get; set; }
        public string MEDIA_CFG { get; set; }
        public System.DateTime DateTime { get; set; }
        public decimal f_identity { get; set; }
        public string CuoiThang { get; set; }
        public string tk_242142 { get; set; }
        public int DinhMucThang { get; set; }
        public int SoPhayV { get; set; }
        public int SoPhayU { get; set; }
        public int SoPhaySL { get; set; }
        public string nguoi_lh { get; set; }
        public byte qdinh { get; set; }
        public string thongtu { get; set; }
        public string link_webservice1 { get; set; }
        public string link_webservice2 { get; set; }
        public string user_webservice { get; set; }
        public string pass_webservice { get; set; }
        public string acname_webservice { get; set; }
        public string acpass_webservice { get; set; }
        public bool option_einvoice { get; set; }
        public string link_webservice3 { get; set; }
        public string email_einvoice { get; set; }
        public string pass_einvoice { get; set; }
        public string subject_einvoice { get; set; }
        public string content_einvoice { get; set; }
        public int DLDinhmucthang { get; set; }
        public string tk_dtk { get; set; }
        public string tk_cpk { get; set; }
        public byte theo_lo { get; set; }
        public byte luachonhddt { get; set; }
        public byte tonkhotheolo { get; set; }
        public string giamdoc { get; set; }
        public string ketoantruong { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string website { get; set; }
    }
}
