//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_KHPW2
    {
        public byte PRINTDATE { get; set; }
        public byte KHOASUA_KC { get; set; }
        public string HELP_PH_IN { get; set; }
        public byte IDNOCMM { get; set; }
        public byte LOGO { get; set; }
        public int A4SUBLEFT { get; set; }
        public int A4SUBTOP { get; set; }
        public int A4SUBLEFT1 { get; set; }
        public int A4SUBTOP1 { get; set; }
        public int A3SUBLEFT { get; set; }
        public int A3SUBTOP { get; set; }
        public int A3SUBLEFT1 { get; set; }
        public int A3SUBTOP1 { get; set; }
        public byte LOAIDL { get; set; }
        public byte THEM1 { get; set; }
        public byte THEM2 { get; set; }
        public byte THEM3 { get; set; }
        public byte THEM4 { get; set; }
        public byte THEM5 { get; set; }
        public string CAMFIELDS { get; set; }
        public decimal f_identity { get; set; }
    }
}
