//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_KHO
    {
        public byte CAP { get; set; }
        public string MA { get; set; }
        public string TEN { get; set; }
        public int KHO { get; set; }
        public decimal SO_PHAN_BO { get; set; }
        public decimal PHAN_TRAM { get; set; }
        public decimal TIEU_THUC { get; set; }
        public decimal HS_TTHUC { get; set; }
        public string TK_KCNO { get; set; }
        public short MA_USER { get; set; }
        public decimal STT { get; set; }
        public short DVCS { get; set; }
        public System.DateTime DATETIME { get; set; }
        public short ma_user1 { get; set; }
        public int bo_phan { get; set; }
        public decimal f_identity { get; set; }
        public int DVCS1 { get; set; }
        public decimal HeSo { get; set; }
    }
}
