//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_KichBan
    {
        public string Ma { get; set; }
        public string Ten { get; set; }
        public int kichban { get; set; }
        public short dvcs { get; set; }
        public decimal f_identity { get; set; }
        public System.DateTime Datetime { get; set; }
        public short ma_user { get; set; }
        public short Ma_user1 { get; set; }
    }
}
