//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_KSCfg
    {
        public decimal nStt { get; set; }
        public string cTK { get; set; }
        public int Bo_Phan { get; set; }
        public int KhoanMuc { get; set; }
        public int ma_Kh { get; set; }
        public int Vviec { get; set; }
        public int Loai_nx { get; set; }
        public int Loai_tc { get; set; }
        public int Kho { get; set; }
        public int ma_THB { get; set; }
        public int Tscd { get; set; }
        public int Vung { get; set; }
        public string KSThem { get; set; }
        public System.DateTime DATETIME { get; set; }
        public decimal f_identity { get; set; }
        public string LenhThem { get; set; }
        public int luongtinh { get; set; }
        public string Macdinh { get; set; }
    }
}
