//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_KTRA_CTU
    {
        public int KTRA_CTU { get; set; }
        public string OK { get; set; }
        public string FIELDTT { get; set; }
        public string VAR { get; set; }
        public string THONGBAO { get; set; }
        public short MA_SCR { get; set; }
        public string COMM1 { get; set; }
        public string FUNC { get; set; }
        public short STT { get; set; }
        public System.DateTime DATETIME { get; set; }
        public decimal f_identity { get; set; }
    }
}
