//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ListKS
    {
        public int STT { get; set; }
        public string Name { get; set; }
        public int UserSD { get; set; }
        public System.DateTime DateTimeSD { get; set; }
        public int KS { get; set; }
        public int UserKS { get; set; }
        public System.DateTime DateTimeKS { get; set; }
        public System.DateTime DateTime { get; set; }
        public decimal f_identity { get; set; }
        public System.DateTime NgayBD { get; set; }
        public System.DateTime NgayKT { get; set; }
    }
}
