//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_LOG_Invoices
    {
        public string keyhd { get; set; }
        public string ten { get; set; }
        public string noidung { get; set; }
        public short ma_user { get; set; }
        public int ws { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
    }
}
