//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_LOAI_TC
    {
        public int LOAI_TC { get; set; }
        public byte SPCAP { get; set; }
        public string MA { get; set; }
        public byte CAP { get; set; }
        public string TEN { get; set; }
        public string DV_DO { get; set; }
        public decimal SO_LUONG { get; set; }
        public decimal DON_GIATB { get; set; }
        public decimal DON_GIATBU { get; set; }
        public decimal TH_TIEN { get; set; }
        public short LOAI_TB { get; set; }
        public string GHI_CHU { get; set; }
        public decimal SO_PHAN_BO { get; set; }
        public decimal PHAN_TRAM { get; set; }
        public string CO { get; set; }
        public short DVCS { get; set; }
        public decimal TIEU_THUC { get; set; }
        public decimal HS_TTHUC { get; set; }
        public int MA_TP { get; set; }
        public string TK_KCNO { get; set; }
        public decimal SLDM { get; set; }
        public decimal NGAYDM { get; set; }
        public decimal GT_KHOACH { get; set; }
        public short MA_USER { get; set; }
        public System.DateTime DATETIME { get; set; }
        public byte DISABLE { get; set; }
        public string QUY_CACH { get; set; }
        public decimal f_identity { get; set; }
        public short ma_user1 { get; set; }
        public decimal HeSo { get; set; }
        public int loai_nx { get; set; }
        public string tk_kho { get; set; }
        public int kho { get; set; }
    }
}
