//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_luufile
    {
        public decimal f_identity { get; set; }
        public System.DateTime datetime { get; set; }
        public short ma_user { get; set; }
        public short ma_user1 { get; set; }
        public string ten_file { get; set; }
        public byte[] luuTailieu { get; set; }
        public decimal size { get; set; }
        public string sTailieu { get; set; }
        public int loaihd { get; set; }
        public int ploaihs { get; set; }
        public int vviec { get; set; }
        public int vviecpl { get; set; }
        public decimal stt { get; set; }
        public string mucdich { get; set; }
        public string ghichu { get; set; }
        public int giaidoan { get; set; }
        public System.DateTime ngay_thc { get; set; }
        public string guid_file { get; set; }
    }
}
