//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_LUONG_NH
    {
        public string OK { get; set; }
        public decimal STT { get; set; }
        public string TEN { get; set; }
        public byte KHONG_DVKH { get; set; }
        public string LUONG_SX1 { get; set; }
        public string LUONG_SX2 { get; set; }
        public string LUONG_SX3 { get; set; }
        public byte NGAYCONG { get; set; }
        public string PROCBEFORE { get; set; }
        public string PROCAFTER { get; set; }
        public short NHOM { get; set; }
        public System.DateTime DATETIME { get; set; }
        public decimal f_identity { get; set; }
    }
}
