//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_LuongCfg
    {
        public decimal Stt { get; set; }
        public string Kieu { get; set; }
        public string Ten_Cot { get; set; }
        public string Ten_cot_cu { get; set; }
        public string Ten { get; set; }
        public int Dai { get; set; }
        public int nDecima { get; set; }
        public string Bt_tinh { get; set; }
        public string TK_no1 { get; set; }
        public string TK_co1 { get; set; }
        public int KM1 { get; set; }
        public string TK_no2 { get; set; }
        public string TK_co2 { get; set; }
        public int KM2 { get; set; }
        public string TK_no3 { get; set; }
        public string TK_co3 { get; set; }
        public int KM3 { get; set; }
        public string TK_no4 { get; set; }
        public string TK_co4 { get; set; }
        public int KM4 { get; set; }
        public decimal Nhom { get; set; }
        public int Change { get; set; }
        public System.DateTime DateTime { get; set; }
        public decimal f_identity { get; set; }
        public int nHienThi { get; set; }
        public string from_alia { get; set; }
        public string from_field { get; set; }
        public string filt_field { get; set; }
        public string cl_Thu_tien { get; set; }
        public int An { get; set; }
        public int gop { get; set; }
        public string BangLayDL { get; set; }
        public string CongThucLayDL { get; set; }
        public string Lienket { get; set; }
        public string Code { get; set; }
        public string DieuKien { get; set; }
        public string fromlist { get; set; }
        public short dvcs { get; set; }
        public System.DateTime DateTimeCode { get; set; }
        public decimal Sttcode { get; set; }
        public int Nocopy { get; set; }
        public string English { get; set; }
    }
}
