//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_MAIL_GROUP
    {
        public byte Ma_User { get; set; }
        public bool C_Check { get; set; }
        public string Ma { get; set; }
        public string Ten { get; set; }
        public System.DateTime DateTime { get; set; }
        public decimal f_identity { get; set; }
    }
}
