//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_NGUON
    {
        public int NGUON { get; set; }
        public int cap { get; set; }
        public string ma { get; set; }
        public string TEN { get; set; }
        public short MA_USER { get; set; }
        public System.DateTime DATETIME { get; set; }
        public short ma_user1 { get; set; }
        public int bo_phan { get; set; }
        public decimal f_identity { get; set; }
    }
}
