//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ngayle
    {
        public byte ngay { get; set; }
        public byte thang { get; set; }
        public string lydo { get; set; }
        public byte amlich { get; set; }
        public byte tanggiam { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
        public byte thu { get; set; }
        public decimal heso { get; set; }
        public byte khongdung { get; set; }
    }
}
