//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Nhom_KC
    {
        public string OK { get; set; }
        public decimal STT { get; set; }
        public string VietNam { get; set; }
        public string DK_pb1 { get; set; }
        public short dvcs { get; set; }
        public string tables { get; set; }
        public string F10 { get; set; }
        public string F11 { get; set; }
        public string Phanbo { get; set; }
        public decimal TieuThuc { get; set; }
        public short HeSo { get; set; }
        public decimal f_identity { get; set; }
        public System.DateTime datetime { get; set; }
        public string PhanBo2 { get; set; }
        public decimal TieuThuc2 { get; set; }
        public short HeSo1 { get; set; }
        public int kc { get; set; }
        public int pb { get; set; }
        public string DK_KC { get; set; }
        public int cap { get; set; }
        public string makc { get; set; }
        public string English { get; set; }
        public string Ghi_Chu { get; set; }
        public int Tu_no { get; set; }
        public int Ca_SL { get; set; }
        public int Tach_VL_dt { get; set; }
        public int SangVlsphh1 { get; set; }
        public int SangVlsphh2 { get; set; }
        public int HeSo2 { get; set; }
        public int ChiTP1 { get; set; }
        public int ChiTP2 { get; set; }
        public int Pb_Lan2 { get; set; }
        public int Pb_LienTuc { get; set; }
        public string dk_Pb2 { get; set; }
        public string DK_tt1 { get; set; }
        public int nhom_kc { get; set; }
        public string dk_tt2 { get; set; }
        public string tables2 { get; set; }
        public bool ChiPs { get; set; }
        public int GV { get; set; }
        public decimal SoTrenDM { get; set; }
        public decimal HS_TieuHao { get; set; }
        public int DM { get; set; }
        public int kichban { get; set; }
        public string F9 { get; set; }
        public string CHINA { get; set; }
        public byte GV2 { get; set; }
    }
}
