//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_NHOM_NHO
    {
        public int NHOM { get; set; }
        public byte CAP { get; set; }
        public string MA { get; set; }
        public string TEN { get; set; }
        public string FIELD_KTRA { get; set; }
        public string FIELD_PHNX { get; set; }
        public byte OK { get; set; }
        public byte DVCS { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime datetime { get; set; }
        public int ma_user { get; set; }
        public int ma_user1 { get; set; }
        public decimal F_IDENTITY { get; set; }
    }
}
