//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_NhapKhoTP01
    {
        public string ma_tk0 { get; set; }
        public string ma_tk1 { get; set; }
        public int Loai_tc { get; set; }
        public decimal So_luong { get; set; }
        public decimal Don_gia { get; set; }
        public decimal ps_no1 { get; set; }
        public decimal f_identity { get; set; }
    }
}
