//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_NhomLuong
    {
        public decimal Stt { get; set; }
        public string Ten { get; set; }
        public int Khong_Dvkh { get; set; }
        public string Luong_sx1 { get; set; }
        public string Luong_sx2 { get; set; }
        public string Luong_sx3 { get; set; }
        public decimal Ngay_cong { get; set; }
        public string Procbefor { get; set; }
        public string Procafter { get; set; }
        public System.DateTime DateTime { get; set; }
        public decimal f_identity { get; set; }
        public string OK { get; set; }
        public int NhomLuong { get; set; }
        public int KhongHachToan { get; set; }
        public int GopTK { get; set; }
        public string KeyDMLuong { get; set; }
        public string DanhMucLuong { get; set; }
        public int dvcs { get; set; }
        public string DK_filterDM { get; set; }
        public string DK_CopyThang { get; set; }
        public string quyen { get; set; }
        public int ws { get; set; }
        public short ma_usersd { get; set; }
        public string English { get; set; }
    }
}
