//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Noidung1
    {
        public int iMa_repo { get; set; }
        public double fStt { get; set; }
        public string cTen { get; set; }
        public string cKieu { get; set; }
        public string cVar1 { get; set; }
        public string cDK { get; set; }
        public string tDK_Them { get; set; }
        public string cTruong { get; set; }
        public string cRelay { get; set; }
        public string cField_Ten { get; set; }
        public short iVN { get; set; }
        public short iCong { get; set; }
        public short iSum_type { get; set; }
        public short iLTheo { get; set; }
        public string cGiaiThich { get; set; }
        public short iDau { get; set; }
        public string cGhi_Chu { get; set; }
        public byte iSoAm { get; set; }
        public short iSXep { get; set; }
        public string cTen_Vn { get; set; }
        public string cTen_Eng { get; set; }
        public string tDau_Cot { get; set; }
        public string tCuoi_Cot { get; set; }
        public byte bKhong_Hien { get; set; }
        public short iGop_Theo { get; set; }
        public byte bGop_Them { get; set; }
        public string tProc { get; set; }
        public short iIDsXep { get; set; }
        public byte bKhong_In { get; set; }
        public double fHS_DanCot { get; set; }
        public int iWidth { get; set; }
        public byte bDongGiongNhau { get; set; }
        public byte iKhong_Lap { get; set; }
        public string EnterCot { get; set; }
        public string HeaderColor { get; set; }
        public string KyTuDuoiCot { get; set; }
        public decimal f_identity { get; set; }
        public System.DateTime DateTime { get; set; }
        public int NT { get; set; }
        public string CHINA { get; set; }
        public string AsTenCot { get; set; }
        public byte kiem_tra_null { get; set; }
    }
}
