//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PHNX
    {
        public decimal f_identity { get; set; }
        public System.DateTime NGAY_THC { get; set; }
        public int MA_SCR { get; set; }
        public byte LOAICT { get; set; }
        public string CHUNG_TU { get; set; }
        public string SOHD { get; set; }
        public string SERIHD { get; set; }
        public string ONGBA { get; set; }
        public decimal SO_LUONG { get; set; }
        public string DV_DO { get; set; }
        public decimal TY_GIA { get; set; }
        public decimal DON_GIA { get; set; }
        public decimal DG_VON { get; set; }
        public string SO_LENHSX { get; set; }
        public string ORDER_NO { get; set; }
        public int BO_PHAN { get; set; }
        public int VVIEC { get; set; }
        public int LOAI_NX { get; set; }
        public int LOAI_TC { get; set; }
        public short LOAI_KH { get; set; }
        public short LOAI_TB { get; set; }
        public int KHO { get; set; }
        public int KHO11 { get; set; }
        public int MA_KH { get; set; }
        public string MA_TK0 { get; set; }
        public decimal PS_NO1 { get; set; }
        public string MA_TK1 { get; set; }
        public decimal PS_CO1 { get; set; }
        public decimal TIEN_USD { get; set; }
        public decimal VAT { get; set; }
        public string TK_NO1 { get; set; }
        public string TK_CO1 { get; set; }
        public string TK_NO2 { get; set; }
        public string TK_CO2 { get; set; }
        public string TK_NO3 { get; set; }
        public string TK_CO3 { get; set; }
        public decimal THUE_XNK { get; set; }
        public string GHI_CHU { get; set; }
        public string GCH_DETAIL { get; set; }
        public string CTU_REF { get; set; }
        public short LOAI_TBT { get; set; }
        public int MA_THB { get; set; }
        public int TSCD { get; set; }
        public System.DateTime PHI_TM { get; set; }
        public short MA_USER { get; set; }
        public short MA_USER1 { get; set; }
        public short WS { get; set; }
        public int KHOANMUC { get; set; }
        public byte BTFIRST { get; set; }
        public short DVCS { get; set; }
        public short IDSAOCHEP { get; set; }
        public string CTGS { get; set; }
        public int MA_KHC { get; set; }
        public System.DateTime DATE { get; set; }
        public int VUNG { get; set; }
        public int NGUON { get; set; }
        public int MUCLUC { get; set; }
        public int TKNHANG { get; set; }
        public int TKNHANGG { get; set; }
        public int SALESMAN { get; set; }
        public short LOAIDL { get; set; }
        public string KTDB { get; set; }
        public string TT1 { get; set; }
        public string TT2 { get; set; }
        public string TT3 { get; set; }
        public string TT4 { get; set; }
        public byte KHUTRUNG { get; set; }
        public string MSTHUE { get; set; }
        public string KHTHUE { get; set; }
        public string DCTHUE { get; set; }
        public string NHOM_VAT { get; set; }
        public int NHAN_SU { get; set; }
        public string SO_LO { get; set; }
        public System.DateTime DATETIME { get; set; }
        public byte GVTC { get; set; }
        public byte ID_BHANH { get; set; }
        public int MA_KHHD { get; set; }
        public byte LSX_END { get; set; }
        public int vp_ddien { get; set; }
        public int hiep_hoi { get; set; }
        public int bo_phanc { get; set; }
        public int nhan_vien { get; set; }
        public System.DateTime Hanthanhtoan { get; set; }
        public System.DateTime Ngay_CheckIn { get; set; }
        public System.DateTime Ngay_CheckOut { get; set; }
        public System.DateTime Ngay_RaHD { get; set; }
        public decimal Tien_CK { get; set; }
        public int PhanTram_TT { get; set; }
    }
}
