//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_phanloaihd
    {
        public int phanloai { get; set; }
        public string ma { get; set; }
        public string ten { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
        public string tablename { get; set; }
        public string fieldname { get; set; }
        public string filtername { get; set; }
        public string ma_tk0 { get; set; }
        public string ma_tk1 { get; set; }
        public int kho { get; set; }
    }
}
