//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_phuong
    {
        public int phuong { get; set; }
        public byte cap { get; set; }
        public string ma { get; set; }
        public string ten { get; set; }
        public short ma_user { get; set; }
        public short ma_user1 { get; set; }
        public System.DateTime datetao { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
        public int quan { get; set; }
        public int tinh { get; set; }
        public string loai { get; set; }
        public string maquan { get; set; }
        public string matinh { get; set; }
    }
}
