//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_quanly_database
    {
        public string ten_database { get; set; }
        public string ma { get; set; }
        public string ten { get; set; }
        public int trangthai { get; set; }
        public string ghichu { get; set; }
        public System.DateTime datetime { get; set; }
        public int ma_user { get; set; }
        public decimal f_identity { get; set; }
        public string them1 { get; set; }
        public string diachi { get; set; }
        public string masothue { get; set; }
        public string dienthoai { get; set; }
        public string sotaikhoan { get; set; }
        public string tennganhang { get; set; }
        public string thongtu { get; set; }
        public string ten_dtvt { get; set; }
    }
}
