//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ReportFilter
    {
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
        public int ma_repo { get; set; }
        public string Language { get; set; }
        public byte[] FilterElement { get; set; }
        public byte type { get; set; }
        public int ma_user { get; set; }
    }
}
