//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_REPORT_BSC
    {
        public int MA_REPO { get; set; }
        public int STT { get; set; }
        public string MASO { get; set; }
        public string NHOM { get; set; }
        public string TMINH { get; set; }
        public string CHI_TIEU { get; set; }
        public string TR1 { get; set; }
        public string TR2 { get; set; }
        public string TR3 { get; set; }
        public string TR4 { get; set; }
        public string TR5 { get; set; }
        public string TR6 { get; set; }
        public string TR7 { get; set; }
        public string TR8 { get; set; }
        public string TR9 { get; set; }
        public string TR10 { get; set; }
        public string TEN_ENG { get; set; }
        public byte IN_DAM { get; set; }
        public byte CAP { get; set; }
        public string NHAN_ENTER { get; set; }
        public int F_IDENTITY { get; set; }
        public System.DateTime DATETIME { get; set; }
        public string tr11 { get; set; }
        public string tr12 { get; set; }
        public string tr13 { get; set; }
        public string tr14 { get; set; }
        public string tr15 { get; set; }
        public string CHINA { get; set; }
        public byte DISABLE { get; set; }
        public string ghichu { get; set; }
        public string ghichu2 { get; set; }
        public string ghichu3 { get; set; }
        public string ghichu4 { get; set; }
        public byte invisible { get; set; }
    }
}
