//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_REPORT
    {
        public short TREE { get; set; }
        public int MA_REPO { get; set; }
        public byte CAP { get; set; }
        public string MA { get; set; }
        public string TEN { get; set; }
        public string TEN_ENG { get; set; }
        public byte RCAP { get; set; }
        public byte LAND { get; set; }
        public string RTHEO { get; set; }
        public decimal TINH_THEO { get; set; }
        public byte NHOM { get; set; }
        public int BO_PHAN { get; set; }
        public int KHOANMUC { get; set; }
        public int MA_KH { get; set; }
        public int MA_THB { get; set; }
        public int TSCD { get; set; }
        public int VVIEC { get; set; }
        public int KHO { get; set; }
        public string MA_TK0 { get; set; }
        public int LOAI_NX { get; set; }
        public int LOAI_TC { get; set; }
        public byte TGV { get; set; }
        public byte NTE { get; set; }
        public string DK { get; set; }
        public string FROM_TK { get; set; }
        public string TINH_SAU { get; set; }
        public string DK_CUOI { get; set; }
        public byte KLOAI { get; set; }
        public byte NBANG { get; set; }
        public byte DETECT { get; set; }
        public byte TACHH { get; set; }
        public byte THEO_SOCOT { get; set; }
        public byte A3 { get; set; }
        public byte IDTXTCUOI { get; set; }
        public byte ONLYTHIS { get; set; }
        public byte CONGDUOI { get; set; }
        public string FRX { get; set; }
        public string FRXE { get; set; }
        public string FRXEV { get; set; }
        public byte SODUOICOT { get; set; }
        public decimal THEMTITLE { get; set; }
        public decimal XUONGTITLE { get; set; }
        public string MAU { get; set; }
        public byte CANGIUA { get; set; }
        public byte KHUNGNHAT { get; set; }
        public byte WMAX { get; set; }
        public string CO { get; set; }
        public int OK { get; set; }
        public byte PS { get; set; }
        public byte GD { get; set; }
        public byte BSC { get; set; }
        public short FROMBC { get; set; }
        public string SBSC { get; set; }
        public byte SUA_TR_IN { get; set; }
        public string VARIABLES { get; set; }
        public string CodeVari { get; set; }
        public string FR { get; set; }
        public string FONTDIEUKIEN { get; set; }
        public string FONT_TIT { get; set; }
        public string FONTDETAIL { get; set; }
        public string FONTCTY { get; set; }
        public string FONTATEN { get; set; }
        public string FONTNHOM { get; set; }
        public string FONTLAPNGAY { get; set; }
        public string FONTLAPBIEU { get; set; }
        public string FONTCHUKY { get; set; }
        public byte FILLING { get; set; }
        public byte NOLINE { get; set; }
        public byte LOGONODEF { get; set; }
        public string NHOM_COT { get; set; }
        public int LMAGIN { get; set; }
        public int RMAGIN { get; set; }
        public string SPROCSTT { get; set; }
        public string DATQUYEN { get; set; }
        public byte NO_TMPLUU { get; set; }
        public byte SO_TRONG { get; set; }
        public byte CHI_IN { get; set; }
        public byte TONGHOP { get; set; }
        public byte BCTHANGQUY { get; set; }
        public string GHI_CHU { get; set; }
        public byte IDSUA { get; set; }
        public decimal STT { get; set; }
        public byte DISABLE { get; set; }
        public string DBFBSC { get; set; }
        public int MA_REPOE { get; set; }
        public string BEFOREALL { get; set; }
        public string TIENXL_MEM { get; set; }
        public string XULY2_MEM { get; set; }
        public string HAUXL_MEM { get; set; }
        public string MTHAMSO { get; set; }
        public string TIEUDEIN { get; set; }
        public byte THEO_PAR { get; set; }
        public decimal THEMSUM { get; set; }
        public decimal XUONGSUM { get; set; }
        public string PROC_F1 { get; set; }
        public string MLOAIDL { get; set; }
        public byte NOTITCTY { get; set; }
        public byte NODATE { get; set; }
        public byte NODAUBC { get; set; }
        public byte NOTITLE2 { get; set; }
        public byte NOCONGBANG { get; set; }
        public byte KCONGBANG { get; set; }
        public byte NOPTIME { get; set; }
        public byte CUSTSIZE { get; set; }
        public decimal PAPERAT { get; set; }
        public byte KHONGCHUKY { get; set; }
        public byte REPBASE { get; set; }
        public short KEYCOLUMN { get; set; }
        public short KEYCOLUMN1 { get; set; }
        public short KEYCOLUMN2 { get; set; }
        public string DATA_ID { get; set; }
        public byte THEONGAY { get; set; }
        public byte FIX_COT { get; set; }
        public string TKVIEW { get; set; }
        public byte NSTARTDATE { get; set; }
        public byte ID_PROCF1 { get; set; }
        public System.DateTime DATETIME { get; set; }
        public byte NO_IDLOAI { get; set; }
        public byte CUSTONLY { get; set; }
        public string image { get; set; }
        public short cap0 { get; set; }
        public string p_Dk_Loc { get; set; }
        public string p_Xau1 { get; set; }
        public int ma_repo_ct { get; set; }
        public byte DAUBC { get; set; }
        public string RUNSQL { get; set; }
        public string RUNSQLDAU { get; set; }
        public bool XauTim { get; set; }
        public bool viet { get; set; }
        public bool eng { get; set; }
        public int VienBaoCao { get; set; }
        public int LineStyle { get; set; }
        public string NguoiLapBieu { get; set; }
        public string ChuKy { get; set; }
        public string VIETNAM { get; set; }
        public string ENGLISH { get; set; }
        public string JAPAN { get; set; }
        public string CHINA { get; set; }
        public byte RenameColumn { get; set; }
        public int SELETOP { get; set; }
        public string CauTrucDL { get; set; }
        public bool EnterCot { get; set; }
        public byte[] FRX0 { get; set; }
        public string DongBang { get; set; }
        public byte[] CauTrucErp { get; set; }
        public string quyeninit { get; set; }
        public string table_goc { get; set; }
        public string join_them { get; set; }
        public string code_repo_frx { get; set; }
        public int ps_dbc { get; set; }
        public string DK_TaoView { get; set; }
        public string thaythe_ngay_thc { get; set; }
        public string font_dbc { get; set; }
        public string thongtu { get; set; }
        public decimal f_identity { get; set; }
        public string sqlsaudorep { get; set; }
        public string sqlsaudorepdbc { get; set; }
        public string FONTKYHO { get; set; }
        public string FONT_TONGCONG { get; set; }
    }
}
