//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Rowfilter_read_ct
    {
        public string tblname { get; set; }
        public string dk { get; set; }
        public string users { get; set; }
        public int ma_user { get; set; }
        public System.DateTime datetime { get; set; }
        public int cap { get; set; }
        public string ma { get; set; }
        public string ten_ht { get; set; }
        public int @readonly { get; set; }
        public int ws { get; set; }
        public decimal f_identity { get; set; }
    }
}
