//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SALESMAN
    {
        public int SALESMAN { get; set; }
        public string TEN { get; set; }
        public System.DateTime DATETIME { get; set; }
        public short ma_user { get; set; }
        public int loai_nx { get; set; }
        public int bo_phan { get; set; }
        public int tknHang { get; set; }
        public System.DateTime Ngay_BD_TViec { get; set; }
        public System.DateTime Ngay_KT_TViec { get; set; }
        public System.DateTime Ngay_DB_CThuc { get; set; }
        public System.DateTime Ngay_KT_CThuc { get; set; }
        public System.DateTime Ngay_Sinh { get; set; }
        public string Dia_chi { get; set; }
        public string dien_Thoai { get; set; }
        public string Vitri_CTac { get; set; }
        public string CongViec { get; set; }
        public int cap { get; set; }
        public string ma { get; set; }
        public decimal f_identity { get; set; }
        public short ma_user1 { get; set; }
    }
}
