//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_screen_ktra
    {
        public byte ok { get; set; }
        public string codeproc { get; set; }
        public string ghi_chu { get; set; }
        public string tencot { get; set; }
        public string tenbang { get; set; }
        public string dkktra { get; set; }
        public decimal stt { get; set; }
        public int ma_scr { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
    }
}
