//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_screen_erp2_default
    {
        public decimal stt { get; set; }
        public int ma_scr { get; set; }
        public string field { get; set; }
        public string defaultvalue { get; set; }
        public byte issqlfunction { get; set; }
        public string ghichu { get; set; }
        public string function_editing { get; set; }
        public string listparameters { get; set; }
        public byte recallwhensave { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
    }
}
