//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_screen_erp
    {
        public int MA_SCR { get; set; }
        public byte CAP { get; set; }
        public string MA { get; set; }
        public string DE_LAI { get; set; }
        public int BO_PHAN { get; set; }
        public int KHO { get; set; }
        public int KHOANMUC { get; set; }
        public int VVIEC { get; set; }
        public int LOAI_NX { get; set; }
        public int LOAI_TC { get; set; }
        public int MA_THB { get; set; }
        public int MA_KH { get; set; }
        public byte LOAIDL { get; set; }
        public string MA_TK0 { get; set; }
        public string MA_TK1 { get; set; }
        public string DVTT { get; set; }
        public byte KTSO_LUONG { get; set; }
        public byte CP_SXUAT { get; set; }
        public short FORM { get; set; }
        public string CO { get; set; }
        public byte DISABLE { get; set; }
        public byte KIEUBANG { get; set; }
        public byte GIAK { get; set; }
        public byte NOCTU { get; set; }
        public byte MOTVE { get; set; }
        public byte BANDAU { get; set; }
        public byte NO_MA_TK0 { get; set; }
        public byte NO_MA_TK1 { get; set; }
        public byte TIENTR { get; set; }
        public byte LOAI_CT { get; set; }
        public string BT_TINH { get; set; }
        public byte GB { get; set; }
        public byte GB1 { get; set; }
        public byte TG { get; set; }
        public byte TG1 { get; set; }
        public byte TSCD { get; set; }
        public byte KHAUHAO { get; set; }
        public byte NGUONTS { get; set; }
        public byte CHKHO { get; set; }
        public byte NHAP_DVDO1 { get; set; }
        public byte TIEN_DVDO1 { get; set; }
        public byte TY_LE_THU { get; set; }
        public short DVCS_RIENG { get; set; }
        public byte NHAPTP { get; set; }
        public byte HDON { get; set; }
        public byte HDON1 { get; set; }
        public byte HDON2 { get; set; }
        public byte XAULOC_HD { get; set; }
        public byte SDKM { get; set; }
        public byte NHIEU_MUC { get; set; }
        public string XAU_VL { get; set; }
        public decimal STT { get; set; }
        public string FIELD_KTRA { get; set; }
        public string FIELD_PHNX { get; set; }
        public string FIELD_FIT { get; set; }
        public byte PB_TTHUC { get; set; }
        public string PB_MA_TKNO { get; set; }
        public short PB_MA_SCR { get; set; }
        public byte PB_VND_USD { get; set; }
        public string ADD_FIELDS { get; set; }
        public string KTUTD_CUOI { get; set; }
        public string KTU_TD { get; set; }
        public byte THEOHD { get; set; }
        public byte THEOBP { get; set; }
        public byte THEOKHO { get; set; }
        public byte THEONAM { get; set; }
        public byte GIA_VON { get; set; }
        public byte PB_THEOSL { get; set; }
        public string PROC_FORM { get; set; }
        public string PROC_ { get; set; }
        public string VALIDPROC { get; set; }
        public string VALIDFIELD { get; set; }
        public string VALIDFIEL1 { get; set; }
        public string QUYEN { get; set; }
        public string WVR_SNUM { get; set; }
        public byte DB1 { get; set; }
        public byte DB2 { get; set; }
        public byte DB3 { get; set; }
        public string GHI_CHU { get; set; }
        public string CT_FOCUS { get; set; }
        public string LOCPB { get; set; }
        public byte PENDING { get; set; }
        public string PROC_KTRA { get; set; }
        public string DK_DANHMUC { get; set; }
        public byte INPHIEU { get; set; }
        public byte INKHONGHOI { get; set; }
        public byte SD_LOAIDL { get; set; }
        public string KTDB { get; set; }
        public string NOT_EMPTY { get; set; }
        public string CHUC_NANG { get; set; }
        public string CHONNHIEU { get; set; }
        public string BTTHEMS { get; set; }
        public string CHSCHEPVAO { get; set; }
        public short MA_USER { get; set; }
        public string SDECIMAL { get; set; }
        public byte DIRECTSQL { get; set; }
        public string TABLE_TT { get; set; }
        public byte LUUTACH { get; set; }
        public System.DateTime DATETIME { get; set; }
        public byte CUOI_PHIEU { get; set; }
        public byte VERSION { get; set; }
        public decimal f_identity { get; set; }
        public string image { get; set; }
        public short cap0 { get; set; }
        public string VIETNAM { get; set; }
        public string ENGLISH { get; set; }
        public string CHINA { get; set; }
        public string JAPAN { get; set; }
        public string F_READONLY { get; set; }
        public string F_ENABLE { get; set; }
        public string F_READONLY_F2 { get; set; }
        public string FIELDSHOW { get; set; }
        public string sumfield { get; set; }
        public int so_cot { get; set; }
        public string ctu_field { get; set; }
        public string ctu_nfield { get; set; }
        public byte ctu_tudong { get; set; }
        public byte ctu_ktra { get; set; }
        public byte ctu_nam { get; set; }
        public string filter_f2 { get; set; }
        public string anhien_nut { get; set; }
        public byte allow_edit_when_f2 { get; set; }
    }
}
