//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_screen_danhmuc
    {
        public string tableName { get; set; }
        public int danhmuc { get; set; }
        public string listField { get; set; }
        public string ma { get; set; }
        public string VIETNAM { get; set; }
        public int form { get; set; }
        public string image { get; set; }
        public string ENGLISH { get; set; }
        public byte columns { get; set; }
        public string keycol { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
        public byte allowrecreate { get; set; }
        public string listFieldSearch { get; set; }
        public byte allowrecreateSearch { get; set; }
        public byte columnsSearch { get; set; }
        public string buttonlist { get; set; }
        public string listFieldReadonly { get; set; }
        public string listFieldReadOnlyEdit { get; set; }
        public string uploadFrx { get; set; }
        public string exTableName { get; set; }
        public string exListField { get; set; }
        public string defaultWhereSearch { get; set; }
        public string defaultOrderby { get; set; }
        public int mascr { get; set; }
    }
}
