//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_screen_erp2_code
    {
        public string ma { get; set; }
        public string control { get; set; }
        public string form { get; set; }
        public string codeProc { get; set; }
        public int ma_scr { get; set; }
        public string tableName { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
    }
}
