//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_screenobj
    {
        public string ma_obj { get; set; }
        public int f_identity { get; set; }
        public int hang { get; set; }
        public byte nhom { get; set; }
        public string form { get; set; }
        public string field_phnx { get; set; }
        public int ma_scr { get; set; }
        public short hien { get; set; }
        public short sudung { get; set; }
        public short luu { get; set; }
        public short delai { get; set; }
        public System.DateTime datetime { get; set; }
    }
}
