//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_screen_erp2
    {
        public int ma_scr { get; set; }
        public string tableName { get; set; }
        public string ListField { get; set; }
        public string ma { get; set; }
        public string VIETNAM { get; set; }
        public byte cap { get; set; }
        public int form { get; set; }
        public string image { get; set; }
        public byte cap0 { get; set; }
        public string ENGLISH { get; set; }
        public byte columns { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
        public string keycol { get; set; }
        public byte allowrecreate { get; set; }
        public string listFieldReadonly { get; set; }
        public string listFieldReadOnlyEdit { get; set; }
        public string xuly { get; set; }
        public string sua_dev { get; set; }
        public string file_frx { get; set; }
        public string listFieldNotEmpty { get; set; }
        public string buttonlist { get; set; }
        public byte khongsuagoc { get; set; }
    }
}
