//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_screen_erp2_ex
    {
        public int ma_scr { get; set; }
        public string procWhenSave { get; set; }
        public string procWhenLoad { get; set; }
        public string procAfterSave { get; set; }
        public string procWhenSign { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
    }
}
