//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_screen_chitiet
    {
        public int ma_scr { get; set; }
        public string tableName { get; set; }
        public string ListField { get; set; }
        public string copyField { get; set; }
        public byte GridForm { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
        public int chitiet { get; set; }
        public decimal stt { get; set; }
        public string VietNam { get; set; }
        public string groupString { get; set; }
        public int HeaderHeight { get; set; }
        public string procAllColumn { get; set; }
        public string addsObject { get; set; }
        public string dkthem { get; set; }
        public string cottt { get; set; }
        public string keycol { get; set; }
        public string readonlyCellWhen { get; set; }
        public string keyimport { get; set; }
        public string copy_xuongluoi { get; set; }
        public byte readonlytheoform { get; set; }
        public byte camthem { get; set; }
        public byte camxoa { get; set; }
        public string pivotfield { get; set; }
        public string ignorefield { get; set; }
        public string valuefield { get; set; }
        public string groupfield { get; set; }
        public string sheetimport { get; set; }
    }
}
