//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SL_CPC
    {
        public short SL_CPC { get; set; }
        public short NHOM { get; set; }
        public string TU_TK { get; set; }
        public string SANG_TK { get; set; }
        public string GHI_CHU { get; set; }
        public System.DateTime DATETIME { get; set; }
        public decimal f_identity { get; set; }
    }
}
