//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SL_TTPB
    {
        public short SL_TTPB { get; set; }
        public byte STT { get; set; }
        public string TEN { get; set; }
        public string TEN_ENG { get; set; }
        public string GIA_TRI { get; set; }
        public string DK { get; set; }
        public string RELA { get; set; }
        public string PROC_ { get; set; }
        public System.DateTime DATETIME { get; set; }
        public decimal f_identity { get; set; }
    }
}
