//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SoDuKC
    {
        public string OK { get; set; }
        public string TKN { get; set; }
        public string TKC { get; set; }
        public int TuBen { get; set; }
        public decimal SoDu { get; set; }
        public decimal SoKC { get; set; }
        public decimal ConLai { get; set; }
        public decimal f_identity { get; set; }
        public System.DateTime DateTime { get; set; }
        public string chung_tu { get; set; }
        public decimal So_luong { get; set; }
        public decimal f_identity2 { get; set; }
        public int bo_phan { get; set; }
        public int ma_thb { get; set; }
        public int Loai_tc { get; set; }
    }
}
