//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SQL
    {
        public string Ma { get; set; }
        public string Ten { get; set; }
        public string TenFSP { get; set; }
        public string ThamSo { get; set; }
        public string MoTa { get; set; }
        public string VD { get; set; }
        public string Code { get; set; }
        public decimal f_identity { get; set; }
        public System.DateTime datetime { get; set; }
        public int cap { get; set; }
        public int Fu { get; set; }
        public string TacGia { get; set; }
        public int MaHoa { get; set; }
        public string C_sql1 { get; set; }
    }
}
