//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_struct_import
    {
        public int ma { get; set; }
        public string column_default { get; set; }
        public string column_name { get; set; }
        public string headertext { get; set; }
        public int ma_scr { get; set; }
        public string table_name { get; set; }
        public decimal f_identity { get; set; }
    }
}
