//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_struct_import2
    {
        public string fieldname0 { get; set; }
        public string fieldname1 { get; set; }
        public string field { get; set; }
        public string from_Alia { get; set; }
        public string from_field { get; set; }
        public string filt_field { get; set; }
        public byte byDvcs { get; set; }
        public int ma_scr { get; set; }
        public string VIETNAM { get; set; }
        public string table_Name { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
    }
}
