//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SuaCauTruc
    {
        public short ok { get; set; }
        public string Ten { get; set; }
        public string IsNull { get; set; }
        public string kieu { get; set; }
        public string DoRong { get; set; }
        public int SoThapPhan { get; set; }
        public string Default_ { get; set; }
        public string Ten_Cu { get; set; }
        public string IsNull_Cu { get; set; }
        public string kieu_cu { get; set; }
        public string DoRong_cu { get; set; }
        public int SoThapPhan_cu { get; set; }
        public string Default_cu { get; set; }
        public int TT { get; set; }
        public decimal f_identity { get; set; }
        public System.DateTime Datetime { get; set; }
        public string TenDefault { get; set; }
        public int is_identity { get; set; }
        public int GT_BD { get; set; }
        public int BuocNhay { get; set; }
        public int Pkey { get; set; }
        public int is_identity_cu { get; set; }
        public int GT_BD_cu { get; set; }
        public int BuocNhay_cu { get; set; }
        public int Pkey_cu { get; set; }
        public string ghichu { get; set; }
        public string ghichu_cu { get; set; }
    }
}
