//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_tableDKRowFilter
    {
        public string tblname { get; set; }
        public string dk_rowFilter { get; set; }
        public int Ma_user { get; set; }
        public System.DateTime datetime { get; set; }
        public int cap { get; set; }
        public string ma { get; set; }
        public decimal f_identity { get; set; }
        public string Ten_HT { get; set; }
        public string dk_RowReadonly { get; set; }
    }
}
