//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_tblTonDNPS
    {
        public System.DateTime Ngay_thc { get; set; }
        public int Ma_thb { get; set; }
        public Nullable<decimal> TienTon { get; set; }
        public Nullable<decimal> SLTon { get; set; }
        public decimal DG { get; set; }
    }
}
