//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_tblKCDuK
    {
        public string cTu_TK { get; set; }
        public string cSang_TK { get; set; }
        public byte iLan_Thu { get; set; }
        public byte iTu_Ben { get; set; }
        public string sGhi_Chu { get; set; }
        public string Gop_Them { get; set; }
        public short dvcs { get; set; }
        public System.DateTime datetime { get; set; }
        public decimal f_identity { get; set; }
    }
}
