//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_tblKCDuK1
    {
        public string Tu_TK { get; set; }
        public string Sang_TK { get; set; }
        public byte Lan { get; set; }
        public byte Tu_Ben { get; set; }
        public Nullable<decimal> Ps_no { get; set; }
        public Nullable<decimal> Tien_usd { get; set; }
        public decimal f_identity { get; set; }
    }
}
