//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TD_BQGQ
    {
        public decimal MA_THB { get; set; }
        public string TK { get; set; }
        public decimal TienTon { get; set; }
        public decimal SL { get; set; }
        public int Thang { get; set; }
        public int Nam { get; set; }
        public int kho { get; set; }
        public System.DateTime DateTime { get; set; }
        public int Check { get; set; }
        public decimal f_identity { get; set; }
    }
}
