//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Testing
    {
        public string senderName { get; set; }
        public System.DateTime timeSent { get; set; }
        public string requirement { get; set; }
        public string receiverName { get; set; }
        public System.DateTime deadLine { get; set; }
        public string status { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
        public string result { get; set; }
        public byte[] bi { get; set; }
        public byte[] vbi { get; set; }
        public string te { get; set; }
        public Nullable<bool> bitt { get; set; }
        public Nullable<System.DateTime> g { get; set; }
        public string C_where { get; set; }
    }
}
