//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_temp_convert_to_fieldshow_screen_table
    {
        public string tenct { get; set; }
        public int ma_scr { get; set; }
        public int duoiluoi { get; set; }
        public string field { get; set; }
        public string from_alia { get; set; }
        public string filt_field { get; set; }
        public int batbuoc { get; set; }
    }
}
