//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_temp_bthem
    {
        public decimal stt { get; set; }
        public string ghi_chu { get; set; }
        public string ma_tk0 { get; set; }
        public string ma_tk1 { get; set; }
        public string bt_ma_tk0 { get; set; }
        public string bt_ma_tk1 { get; set; }
        public string bt_tinh { get; set; }
        public int sl { get; set; }
        public int cuoi_phieu { get; set; }
        public string add_fields { get; set; }
        public string dkhien { get; set; }
        public int hien_san { get; set; }
        public int bat_buoc { get; set; }
        public string proc { get; set; }
        public int ma_scr { get; set; }
        public System.DateTime datetime { get; set; }
        public string EngLish { get; set; }
        public decimal f_identity { get; set; }
    }
}
