//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ThueTNCN
    {
        public System.DateTime ngay { get; set; }
        public decimal mucthunhap { get; set; }
        public decimal pt { get; set; }
        public short ma_user { get; set; }
        public short ma_user1 { get; set; }
        public System.DateTime datetime { get; set; }
        public decimal f_identity { get; set; }
        public string Cach1 { get; set; }
        public string Cach2 { get; set; }
    }
}
