//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_THIETBI
    {
        public int MA_THB { get; set; }
        public byte CAP { get; set; }
        public string MA { get; set; }
        public string TEN { get; set; }
        public string MO_TA { get; set; }
        public string TK_KHO { get; set; }
        public string DV_DO { get; set; }
        public string DV_DO1 { get; set; }
        public decimal TY_LE { get; set; }
        public decimal TY_LE1 { get; set; }
        public decimal TY_LE2 { get; set; }
        public decimal TY_LE3 { get; set; }
        public short TG_BH { get; set; }
        public decimal SO_LUONG { get; set; }
        public decimal DON_GIATB { get; set; }
        public decimal DON_GIATBU { get; set; }
        public decimal TH_TIEN { get; set; }
        public decimal TH_TIENU { get; set; }
        public short LOAI_TB { get; set; }
        public short DVCS { get; set; }
        public decimal GIA_BAN { get; set; }
        public decimal GIA_NHAP { get; set; }
        public decimal SL_MIN { get; set; }
        public byte S { get; set; }
        public decimal VAT { get; set; }
        public byte S1 { get; set; }
        public int KHOANMUC { get; set; }
        public decimal TIEU_THUC { get; set; }
        public decimal HS_TTHUC { get; set; }
        public decimal SO_PHAN_BO { get; set; }
        public decimal PHAN_TRAM { get; set; }
        public int LOAI_TC { get; set; }
        public byte SPCAP { get; set; }
        public System.DateTime NGAY_SAI { get; set; }
        public string TK_KCNO { get; set; }
        public string CO { get; set; }
        public string MA_TCTY { get; set; }
        public short MA_USER { get; set; }
        public System.DateTime DATETIME { get; set; }
        public byte DISABLE { get; set; }
        public decimal HeSo { get; set; }
        public int VP_DDien { get; set; }
        public int Loai_nx { get; set; }
        public int Nguon { get; set; }
        public short MA_USER1 { get; set; }
        public int bo_phan { get; set; }
        public decimal f_identity { get; set; }
        public int DVCS1 { get; set; }
        public decimal ty_leck { get; set; }
        public int kho { get; set; }
    }
}
