//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TieuThucPB
    {
        public string Ten { get; set; }
        public string GiaTri { get; set; }
        public string DK { get; set; }
        public string tables { get; set; }
        public string code { get; set; }
        public decimal f_identity { get; set; }
        public System.DateTime DateTime { get; set; }
        public int lan { get; set; }
        public string KieuCong { get; set; }
        public int TieuThucPB { get; set; }
        public int dvcs { get; set; }
        public int PB_tay { get; set; }
        public string Vietnam { get; set; }
        public string English { get; set; }
        public string China { get; set; }
    }
}
