//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_tiendo_hd
    {
        public System.DateTime tu_ngay { get; set; }
        public decimal thoigianht { get; set; }
        public System.DateTime den_ngay { get; set; }
        public System.DateTime ngay_kttt { get; set; }
        public string ghichu { get; set; }
        public decimal f_identity { get; set; }
        public System.DateTime datetime { get; set; }
        public short ma_user { get; set; }
        public short ma_user1 { get; set; }
        public decimal stt { get; set; }
        public int vviec { get; set; }
        public int giaidoan { get; set; }
        public decimal tyle { get; set; }
        public decimal ps_no1 { get; set; }
        public string lydo { get; set; }
        public int bo_phan { get; set; }
        public short loaidl { get; set; }
        public System.DateTime ngay_bdtt { get; set; }
        public System.DateTime ngay_ttkh { get; set; }
        public System.DateTime ngay_nthu { get; set; }
        public string lydo_nthu { get; set; }
        public string lydo_tt { get; set; }
        public int hangmuc { get; set; }
        public decimal tien_tttt { get; set; }
        public string ghichu1 { get; set; }
        public string ghichu2 { get; set; }
        public int sngay_th { get; set; }
        public int sngay_nthu { get; set; }
        public int sngay_tt { get; set; }
        public byte cangaynghi { get; set; }
        public int keytt_cu { get; set; }
        public int bo_phan2 { get; set; }
        public decimal thuhoitu { get; set; }
        public decimal thuctt { get; set; }
    }
}
