//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_titbrow_fox
    {
        public decimal STT { get; set; }
        public string TABLE { get; set; }
        public string FIELD { get; set; }
        public string VARI { get; set; }
        public string TYPE { get; set; }
        public string TEN { get; set; }
        public string TITLE_ENG { get; set; }
        public string BWIDTH { get; set; }
        public short SUBWIDTH { get; set; }
        public short SUBWIDTH1 { get; set; }
        public string CHECK { get; set; }
        public string CONDITION { get; set; }
        public string RONLYWHEN { get; set; }
        public string ADDITION { get; set; }
        public string O_NHAP { get; set; }
        public int TREE { get; set; }
        public string FROM_ALIA { get; set; }
        public string FROM_FIELD { get; set; }
        public string FILT_FIELD { get; set; }
        public string WITH_TAG { get; set; }
        public string KEYEXPR { get; set; }
        public string PARENTALIA { get; set; }
        public string KIEU { get; set; }
        public int MASO { get; set; }
        public string C_WHEN { get; set; }
        public string VALID { get; set; }
        public string C_PROC { get; set; }
        public string ENABLE { get; set; }
        public string WVR_SNUM { get; set; }
        public string FORECOLOR { get; set; }
        public string BACKCOLOR { get; set; }
        public string FROM_LIST { get; set; }
        public int NDECIMAL { get; set; }
        public string DEF_VALUE { get; set; }
        public byte HIDE { get; set; }
        public string PT1 { get; set; }
        public string PT2 { get; set; }
        public string GIA_TRI1 { get; set; }
        public string GIA_TRI2 { get; set; }
        public string QUYEN { get; set; }
        public string QCHIDOC { get; set; }
        public string TOOLTIP { get; set; }
        public string ALIATIP { get; set; }
        public string DEF_DBF { get; set; }
        public byte WEBPAGE { get; set; }
        public System.DateTime DATETIME { get; set; }
        public string EXPRESSIONS { get; set; }
        public string VIETNAM { get; set; }
        public string ENGLISH { get; set; }
        public string CHINA { get; set; }
        public string JAPAN { get; set; }
        public decimal f_identity { get; set; }
    }
}
