//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TKhoDau_PS_BQGQ
    {
        public System.DateTime NGAY_THC { get; set; }
        public int ma_thb { get; set; }
        public int ma_scr { get; set; }
        public int loaidl { get; set; }
        public int dvcs { get; set; }
        public decimal so_luong { get; set; }
        public string ma_tk0 { get; set; }
        public decimal ps_no1 { get; set; }
        public string ma_tk1 { get; set; }
        public decimal ps_co1 { get; set; }
        public decimal Tien_usd { get; set; }
        public int btfirst { get; set; }
        public int gvtc { get; set; }
        public System.DateTime Datetime { get; set; }
    }
}
