//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TKHOAN
    {
        public string DVTT { get; set; }
        public byte CAP { get; set; }
        public string MA { get; set; }
        public string TEN { get; set; }
        public string TEN_ENG { get; set; }
        public decimal DU_NO0 { get; set; }
        public decimal DU_CO0 { get; set; }
        public decimal DU_NO { get; set; }
        public decimal DU_CO { get; set; }
        public decimal PS_NO { get; set; }
        public decimal PS_CO { get; set; }
        public byte CN { get; set; }
        public byte KHO { get; set; }
        public byte TGHT { get; set; }
        public byte TONGCTY { get; set; }
        public decimal PHAN_TRAM { get; set; }
        public decimal TIEU_THUC { get; set; }
        public decimal SO_PHAN_BO { get; set; }
        public string QUYEN { get; set; }
        public string TK_KCNO { get; set; }
        public short MA_USER { get; set; }
        public byte DISABLE { get; set; }
        public short MA_USERK { get; set; }
        public System.DateTime NGAY_KHOA { get; set; }
        public System.DateTime DATETIME { get; set; }
        public short MA_USER1 { get; set; }
        public string tknhang { get; set; }
        public string chinhanh { get; set; }
        public decimal f_identity { get; set; }
        public byte LT { get; set; }
        public string web_tygia { get; set; }
        public string ten_chin { get; set; }
    }
}
