//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TKNHANG
    {
        public int TKNHANG { get; set; }
        public int MA_KH { get; set; }
        public string MATK { get; set; }
        public string TK_KTOAN { get; set; }
        public string TEN { get; set; }
        public string TINH_TP { get; set; }
        public string DIA_CHI { get; set; }
        public short MA_USER { get; set; }
        public System.DateTime DATETIME { get; set; }
        public string Ten_HuongT { get; set; }
        public string DC_HuongT { get; set; }
        public string So_TK { get; set; }
        public string Ten_Nhang { get; set; }
        public string SWIFT { get; set; }
        public string IBAN { get; set; }
        public int cap { get; set; }
        public string Ma { get; set; }
        public int bo_phan { get; set; }
        public string dvtt { get; set; }
        public short ma_user1 { get; set; }
        public string ma_easia { get; set; }
        public decimal f_identity { get; set; }
        public string quyen { get; set; }
    }
}
