//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_treeview
    {
        public string ma { get; set; }
        public string ten { get; set; }
        public int f_identity { get; set; }
        public short cap { get; set; }
        public string proc_f10 { get; set; }
        public short nutme { get; set; }
        public int img { get; set; }
    }
}
