//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TREE
    {
        public Nullable<byte> cap { get; set; }
        public string ma { get; set; }
        public string ten { get; set; }
        public string C_ForeColor { get; set; }
        public string C_BackColor { get; set; }
        public string C_Image { get; set; }
        public string C_Font { get; set; }
        public Nullable<int> Stt { get; set; }
        public Nullable<byte> SapXepNhom { get; set; }
        public int f_identity { get; set; }
    }
}
