//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_uploadfile
    {
        public System.DateTime datetime { get; set; }
        public decimal f_identity { get; set; }
        public string chung_tu { get; set; }
        public System.DateTime ngay_thc { get; set; }
        public int ma_scr { get; set; }
        public string ghi_chu { get; set; }
        public byte[] filecontent { get; set; }
        public string filename { get; set; }
        public decimal filesize { get; set; }
        public byte uploadfile { get; set; }
        public byte downloadfile { get; set; }
        public short dvcs { get; set; }
    }
}
