//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_USERS
    {
        public byte CAP { get; set; }
        public string MA { get; set; }
        public string TEN { get; set; }
        public short MA_USER { get; set; }
        public short MA_USER0 { get; set; }
        public string GHI_CHU { get; set; }
        public string CO { get; set; }
        public byte QSUA { get; set; }
        public byte CAM { get; set; }
        public decimal STT { get; set; }
        public byte DATQUYEN { get; set; }
        public string PWD { get; set; }
        public string QUYEN { get; set; }
        public string PARS { get; set; }
        public string DK_FIT { get; set; }
        public string RIGHT_NH { get; set; }
        public string DK_CHECK { get; set; }
        public byte ONECLICK { get; set; }
        public string TEPTT { get; set; }
        public byte FIX { get; set; }
        public byte VEFFECT { get; set; }
        public short NNGAYSUA { get; set; }
        public string SMASOTRAM { get; set; }
        public string GIAOTIEP { get; set; }
        public System.DateTime datetime { get; set; }
        public byte userreadonly { get; set; }
        public byte vqsua { get; set; }
        public byte vqxoaf8 { get; set; }
        public byte vqsuasodu { get; set; }
        public byte vcamsua { get; set; }
        public byte vqsuabc { get; set; }
        public int bo_phan { get; set; }
        public string kt_dau { get; set; }
        public string kt_dauHD { get; set; }
        public System.DateTime camngay { get; set; }
        public bool quyencaonhat { get; set; }
        public string QuyenNhom { get; set; }
        public bool QDatQuyen { get; set; }
        public decimal f_identity { get; set; }
        public string databaseName { get; set; }
    }
}
