//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ViewMethod_Group
    {
        public string tableName { get; set; }
        public byte fieldgroup { get; set; }
        public string fieldwhere { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
        public string tableName0 { get; set; }
    }
}
