//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_VVIEC
    {
        public byte CAP { get; set; }
        public string MA { get; set; }
        public string TEN { get; set; }
        public string SO_HDONG { get; set; }
        public short SL_THE { get; set; }
        public System.DateTime TU_NGAY { get; set; }
        public System.DateTime DEN_NGAY { get; set; }
        public int MA_KH { get; set; }
        public string TEN_DVKH { get; set; }
        public decimal TIEN_HDONG { get; set; }
        public System.DateTime NGAYKY_HD { get; set; }
        public decimal SO_PHAN_BO { get; set; }
        public decimal TIEU_THUC { get; set; }
        public decimal PHAN_TRAM { get; set; }
        public decimal HS_TTHUC { get; set; }
        public string TK_KCNO { get; set; }
        public short DVCS { get; set; }
        public short MA_USER { get; set; }
        public short ma_user1 { get; set; }
        public System.DateTime DATETIME { get; set; }
        public int VVIEC { get; set; }
        public byte DISABLE { get; set; }
        public int SalesMan { get; set; }
        public decimal TyleLaiGop_Dtinh { get; set; }
        public System.DateTime NgayYeuCau { get; set; }
        public System.DateTime NgayXacNhan { get; set; }
        public decimal f_identity { get; set; }
        public decimal HeSo { get; set; }
        public string mapm { get; set; }
        public int tinh { get; set; }
        public int tthaihd { get; set; }
        public int loaihd { get; set; }
        public decimal tien_goc { get; set; }
        public System.DateTime ngay_thanhly { get; set; }
        public decimal tien_thanhly { get; set; }
        public byte loai_thanhly { get; set; }
        public System.DateTime ngay_kttt { get; set; }
        public byte loai { get; set; }
    }
}
