//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_vviecpluc
    {
        public string mapm { get; set; }
        public System.DateTime ngayky_hd { get; set; }
        public string so_hdong { get; set; }
        public string ten { get; set; }
        public System.DateTime tu_ngay { get; set; }
        public System.DateTime den_ngay { get; set; }
        public decimal tien_hdong { get; set; }
        public decimal tien_thanhly { get; set; }
        public decimal f_identity { get; set; }
        public System.DateTime datetime { get; set; }
        public short ma_user { get; set; }
        public short ma_user1 { get; set; }
        public decimal stt { get; set; }
        public int vviec { get; set; }
        public int giaidoan { get; set; }
        public short loaidl { get; set; }
        public int loaihd { get; set; }
        public System.DateTime ngayxacnhan { get; set; }
    }
}
