//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_WS
    {
        public int ws { get; set; }
        public byte trang_thai { get; set; }
        public string ghi_chu { get; set; }
        public string ten_may { get; set; }
        public string chuoikhoa { get; set; }
        public System.DateTime datetime { get; set; }
        public System.DateTime lockdate { get; set; }
        public byte lockws { get; set; }
        public System.DateTime resettime { get; set; }
        public byte quittime { get; set; }
        public byte getdl { get; set; }
        public byte tongcty { get; set; }
        public int isInternet { get; set; }
        public string folderName { get; set; }
        public decimal f_identity { get; set; }
    }
}
