//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Xe
    {
        public byte Cap { get; set; }
        public string Ma { get; set; }
        public string Ten { get; set; }
        public int Xe { get; set; }
        public decimal f_identity { get; set; }
        public System.DateTime datetime { get; set; }
    }
}
