//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class EFF_TMDV_KS_khang6868
    {
        public int MA_KH { get; set; }
        public string MA { get; set; }
        public byte CAP { get; set; }
        public string TEN { get; set; }
        public string PHONE { get; set; }
        public string TKHOAN_NH { get; set; }
        public short LOAI_KH { get; set; }
        public short DVCS { get; set; }
        public byte CHI_PHI { get; set; }
        public decimal TIEU_THUC { get; set; }
        public decimal HS_TTHUC { get; set; }
        public decimal SO_PHAN_BO { get; set; }
        public decimal PHAN_TRAM { get; set; }
        public string CO { get; set; }
        public byte CASH { get; set; }
        public short SO_NGAY_NO { get; set; }
        public decimal SO_TIEN_NO { get; set; }
        public decimal P_TRAM_LAI { get; set; }
        public byte CAM_XUAT { get; set; }
        public string DIA_CHI { get; set; }
        public string MA_GTGT { get; set; }
        public string TK_KCNO { get; set; }
        public int MA_KHKD { get; set; }
        public string MA_TCTY { get; set; }
        public short MA_USER { get; set; }
        public System.DateTime DATETIME { get; set; }
        public byte DISABLE { get; set; }
        public int VUNG { get; set; }
        public string Ten_DayDu { get; set; }
        public int mucluc { get; set; }
        public int loai_nx { get; set; }
        public int KHOANMUC { get; set; }
        public string TK_no { get; set; }
        public string TK_co { get; set; }
        public System.DateTime Ngay_Sinh { get; set; }
        public string TenNganHang { get; set; }
        public string DoiTac_LienHe { get; set; }
        public string DiaChiNH { get; set; }
        public string ThanhPho { get; set; }
        public int tknhang { get; set; }
        public short MA_USER1 { get; set; }
        public decimal f_identity { get; set; }
        public int DVCS1 { get; set; }
        public string quyen { get; set; }
        public decimal HeSo { get; set; }
    }
}
