//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_HUMAN_NHAN_SU
    {
        public int NHAN_SU { get; set; }
        public string MA_CCONG { get; set; }
        public string MA { get; set; }
        public byte CAP { get; set; }
        public string TEN { get; set; }
        public string TEN_TGOI { get; set; }
        public System.DateTime NGAY_SINH { get; set; }
        public string GIOI_TINH { get; set; }
        public string NOISINH_X { get; set; }
        public string NOISINH_H { get; set; }
        public int NOISINH_T { get; set; }
        public string QUEQUAN_X { get; set; }
        public string QUEQUAN_H { get; set; }
        public int QUEQUAN_T { get; set; }
        public string DIA_CHI { get; set; }
        public string DAN_TOC { get; set; }
        public string TON_GIAO { get; set; }
        public string TPHAN_GD { get; set; }
        public string N_NGHIEPT { get; set; }
        public string NNG_MASO { get; set; }
        public short TRINH_DO { get; set; }
        public short NGANH_DT { get; set; }
        public string LLUAN_CTRI { get; set; }
        public string NGOAI_NGU { get; set; }
        public System.DateTime NGAY_CM { get; set; }
        public string TOCHUC_CM { get; set; }
        public System.DateTime NGAY_NNGU { get; set; }
        public System.DateTime NGAY_XNGU { get; set; }
        public string QUAN_HAM { get; set; }
        public System.DateTime NGAY_TUYEN { get; set; }
        public string CQ_TUYEN { get; set; }
        public System.DateTime NGAY_DANG { get; set; }
        public System.DateTime NGAY_CTHUC { get; set; }
        public string CVU_HTAI { get; set; }
        public string MASO_CVU { get; set; }
        public string NGACH_CCH { get; set; }
        public string MASO_NGACH { get; set; }
        public decimal BAC_LUONG { get; set; }
        public byte TU_THANG { get; set; }
        public short TU_NAM { get; set; }
        public string DANH_HIEU { get; set; }
        public string SUC_KHOE { get; set; }
        public decimal CHIEU_CAO { get; set; }
        public decimal CAN_NANG { get; set; }
        public string SO_TRUONG { get; set; }
        public string KH_THUONG { get; set; }
        public string KY_LUAT { get; set; }
        public string PIC_FILE { get; set; }
        public string DD_LICHSU { get; set; }
        public string THAMGIA_TC { get; set; }
        public string TU_NHANSET { get; set; }
        public string CMND_SO { get; set; }
        public System.DateTime CMND_NGAY { get; set; }
        public string CMND_NCAP { get; set; }
        public System.DateTime NGAY_BDLV { get; set; }
        public string BACLUONGHT { get; set; }
        public decimal HSLUONGHT { get; set; }
        public System.DateTime TG_TLUONG { get; set; }
        public byte ID_LAODONG { get; set; }
        public byte KHONGVIEC { get; set; }
        public byte ID_TOCHUC { get; set; }
        public byte DANG_VIEN { get; set; }
        public byte PL_LANHDAO { get; set; }
        public byte PL_LUONG { get; set; }
        public byte PL_PHUCAP { get; set; }
        public string CDANH_HT { get; set; }
        public string PHONG_BAN { get; set; }
        public System.DateTime TG_BDBH { get; set; }
        public string SO_SOBHXH { get; set; }
        public string SO_PKCB { get; set; }
        public int DK_KCB { get; set; }
        public string CO { get; set; }
        public string ENABLED { get; set; }
        public short DVCS { get; set; }
        public int MA_KH { get; set; }
        public string LL_TUTHUAT { get; set; }
        public int BO_PHAN { get; set; }
        public int VVIEC { get; set; }
        public int LOAI_NX { get; set; }
        public int LOAI_TC { get; set; }
        public byte NHOM_LUONG { get; set; }
        public short MA_USER { get; set; }
        public System.DateTime datetime { get; set; }
        public decimal f_identity { get; set; }
        public byte ok { get; set; }
    }
}
