//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_TIMKIEM_DK
    {
        public int timkiem { get; set; }
        public short ma_user { get; set; }
        public byte[] filtercondition { get; set; }
        public long f_identity { get; set; }
        public System.DateTime datetime { get; set; }
    }
}
