//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_HUMAN_KNANG_NV
    {
        public byte CAP { get; set; }
        public string MA { get; set; }
        public string TEN { get; set; }
        public string MO_TA { get; set; }
        public int KNANG_NV { get; set; }
        public System.DateTime datetime { get; set; }
        public decimal f_identity { get; set; }
    }
}
