//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_ORDER_THUNG_VD
    {
        public decimal COUNTER { get; set; }
        public System.DateTime NGAY1 { get; set; }
        public int MA_USER { get; set; }
        public string PHIEN_BAN { get; set; }
        public string PHAN_LOAI { get; set; }
        public string PHATSINH { get; set; }
        public string CHI_TIET { get; set; }
        public string GIAIPHAP { get; set; }
    }
}
