//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_KHANG_KM_GGIA
    {
        public decimal COUNTER { get; set; }
        public int MA_THB { get; set; }
        public System.DateTime TU_NGAY { get; set; }
        public System.DateTime DEN_NGAY { get; set; }
        public short PT_GGIA { get; set; }
        public string GHI_CHU { get; set; }
        public string KMAI { get; set; }
        public string MA_NHOM { get; set; }
        public decimal f_identity { get; set; }
        public System.DateTime datetime { get; set; }
    }
}
