//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_TASK_PS_MAIL
    {
        public decimal COUNTER { get; set; }
        public decimal MAIL { get; set; }
        public System.DateTime DATE { get; set; }
        public string NOI_DUNG { get; set; }
        public string CHI_TIET { get; set; }
        public short MA_USER { get; set; }
        public System.DateTime DATETIME { get; set; }
    }
}
