//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_KHANG_DK_KMGG
    {
        public decimal COUNTER { get; set; }
        public decimal KM_GGIA { get; set; }
        public decimal SL_LONHON { get; set; }
        public decimal TI_LONHON { get; set; }
        public System.DateTime DS_TUNGAY { get; set; }
        public System.DateTime DS_DENNGAY { get; set; }
        public decimal DS_LONHON { get; set; }
        public decimal f_identity { get; set; }
    }
}
