//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_KHANG_GIAODICH
    {
        public decimal COUNTER { get; set; }
        public int MA_KHKD { get; set; }
        public System.DateTime NGAY_THC { get; set; }
        public byte THU { get; set; }
        public byte GIAODICH { get; set; }
        public string NOI_DUNG { get; set; }
        public string GHI_CHU { get; set; }
        public string NGUOI_DG { get; set; }
        public string PHANHOI { get; set; }
        public string CHI_TIET { get; set; }
        public string KE_HOACH { get; set; }
        public System.DateTime KH_THGIAN { get; set; }
        public int MA_USER { get; set; }
        public int KHAN_CAP { get; set; }
        public int T_TRANG { get; set; }
        public int HINHTHUC { get; set; }
        public string TAI_LIEU { get; set; }
        public string BAOGIA { get; set; }
        public string OK { get; set; }
        public byte DEMO_LAN { get; set; }
        public decimal BAO_GIA { get; set; }
    }
}
