//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_HUMAN_QLY_NS
    {
        public decimal COUNTER { get; set; }
        public int NHAN_SU { get; set; }
        public System.DateTime TU_NGAY { get; set; }
        public System.DateTime DEN_NGAY { get; set; }
        public string NOI_DUNG { get; set; }
        public string VI_TRI { get; set; }
        public int BO_PHAN { get; set; }
        public string DIA_CHI { get; set; }
        public decimal LUONG { get; set; }
        public short DVCS { get; set; }
        public string CO { get; set; }
        public short MA_USER { get; set; }
    }
}
