//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_Don_Dat_Hang
    {
        public System.DateTime ngay_thc { get; set; }
        public string chung_tu { get; set; }
        public string ghi_chu { get; set; }
        public string gch_detail { get; set; }
        public int ma_thb { get; set; }
        public int kho { get; set; }
        public int kho1 { get; set; }
        public int ma_kh { get; set; }
        public int ma_khc { get; set; }
        public decimal so_luong { get; set; }
        public decimal don_gia { get; set; }
        public decimal ps_no1 { get; set; }
        public string ma_tk0 { get; set; }
        public string ma_tk1 { get; set; }
        public byte loaidl { get; set; }
        public string loai_dh { get; set; }
        public byte duyet_pkd1 { get; set; }
        public int user_dpkd1 { get; set; }
        public System.DateTime ngay_duyet { get; set; }
        public byte duyet_pvt { get; set; }
        public int user_dpvt { get; set; }
        public System.DateTime ngay_duyet1 { get; set; }
        public byte duyet_pkh { get; set; }
        public int user_dpkh { get; set; }
        public System.DateTime ngay_duyet2 { get; set; }
        public byte duyet_pkd2 { get; set; }
        public int user_dpkd2 { get; set; }
        public System.DateTime ngay_duyet3 { get; set; }
        public int user_huy { get; set; }
        public decimal sl_giu { get; set; }
        public byte giu_cho { get; set; }
        public int ma_user { get; set; }
        public int ma_user1 { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime datetime { get; set; }
        public int ws { get; set; }
        public int ma_scr { get; set; }
        public decimal f_identity { get; set; }
        public byte invisible { get; set; }
        public System.DateTime ngay_huy { get; set; }
        public System.DateTime ngay_hoanthanh { get; set; }
        public byte in_dam { get; set; }
        public byte cap { get; set; }
        public string don_dat_hang { get; set; }
        public decimal sl_dk_sx { get; set; }
    }
}
