//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_HUMAN_TongHopDLCC
    {
        public int Nhan_su { get; set; }
        public System.DateTime Ngay_thc { get; set; }
        public int Ca { get; set; }
        public System.DateTime Gio_vao { get; set; }
        public System.DateTime Gio_Ra { get; set; }
        public int Cong { get; set; }
        public decimal di_som_muon { get; set; }
        public decimal Ve_som_muon { get; set; }
        public decimal He_so { get; set; }
        public decimal f_identity { get; set; }
        public System.DateTime Datetime { get; set; }
        public short ma_user { get; set; }
        public short Ma_user1 { get; set; }
    }
}
