//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_HUMAN_KHTHUONG
    {
        public System.DateTime ngay { get; set; }
        public string noi_dung { get; set; }
        public string cap_qd { get; set; }
        public int nhan_su { get; set; }
        public System.DateTime datetime { get; set; }
        public decimal f_identity { get; set; }
    }
}
