//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_PRIVATE_PROC
    {
        public string formname { get; set; }
        public string controlname { get; set; }
        public string loai { get; set; }
        public string proc_ { get; set; }
        public System.DateTime datetime { get; set; }
        public decimal f_identity { get; set; }
        public string when_ { get; set; }
    }
}
