//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_KHANG_HOPDONG
    {
        public decimal COUNTER { get; set; }
        public int MA_KHKD { get; set; }
        public System.DateTime NGAY { get; set; }
        public string PHIEN_BAN { get; set; }
        public string PHAN_LOAI { get; set; }
        public decimal TONGTIEN { get; set; }
        public string DVTT { get; set; }
        public decimal TY_GIA { get; set; }
        public decimal QUY_VND { get; set; }
        public string TRANGTHAI { get; set; }
        public System.DateTime NGAY_THU { get; set; }
        public string THUC_HIEN { get; set; }
        public string NOIDUNG { get; set; }
        public short MA_USER { get; set; }
        public System.DateTime DATETIME { get; set; }
        public string DATEKT { get; set; }
        public System.DateTime NGAY_KY { get; set; }
        public string GHI_CHU { get; set; }
        public string TINHBAOTRI { get; set; }
    }
}
