//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_loaidl
    {
        public int loaidl { get; set; }
        public string ma { get; set; }
        public string ten { get; set; }
        public int ma_user { get; set; }
        public System.DateTime datetime { get; set; }
        public decimal f_identity { get; set; }
    }
}
