//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_HUMAN_QD_Ca
    {
        public decimal stt { get; set; }
        public byte cap { get; set; }
        public string Ma { get; set; }
        public string Ten { get; set; }
        public System.TimeSpan Tu_Gio { get; set; }
        public System.TimeSpan Den_Gio { get; set; }
        public int Loai_Cong { get; set; }
        public decimal TG_muon { get; set; }
        public decimal TG_Som { get; set; }
        public int QD_Ca { get; set; }
        public decimal f_identity { get; set; }
        public System.DateTime DateTime { get; set; }
        public short Ma_user { get; set; }
        public short Ma_User1 { get; set; }
        public System.DateTime Tu_Ngay { get; set; }
    }
}
