//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_HUMAN_KYLUAT
    {
        public System.DateTime NGAY { get; set; }
        public string NOI_DUNG { get; set; }
        public string CAP_QD { get; set; }
        public int NHAN_SU { get; set; }
        public System.DateTime DATETIME { get; set; }
        public decimal F_IDENTITY { get; set; }
    }
}
