//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_HUMAN_HD_LDONG
    {
        public int HD_LDong { get; set; }
        public int NHAN_SU { get; set; }
        public int LOAI_HDONG { get; set; }
        public string NGUOI_KY { get; set; }
        public System.DateTime TU_NGAY { get; set; }
        public System.DateTime DEN_NGAY { get; set; }
        public System.DateTime NGAY_THU0 { get; set; }
        public System.DateTime NGAY_THU1 { get; set; }
        public string DIA_DIEM { get; set; }
        public string CHUC_VU { get; set; }
        public string ND_CVIEC { get; set; }
        public string GIO_HCHINH { get; set; }
        public string PHUONGTIEN { get; set; }
        public decimal MUCLUONG { get; set; }
        public System.DateTime NGAYTRA1 { get; set; }
        public System.DateTime NGAYTRA2 { get; set; }
        public decimal NNGHI_NAM { get; set; }
        public string BHXH { get; set; }
        public string PHUCLOI { get; set; }
        public string BDUONG_NV { get; set; }
        public string TTHUANKHAC { get; set; }
        public System.DateTime HIEULUCTU { get; set; }
        public System.DateTime HIEULUCDEN { get; set; }
        public short DVCS { get; set; }
        public short MA_USER { get; set; }
        public short ma_user1 { get; set; }
        public System.DateTime datetime { get; set; }
        public decimal f_identity { get; set; }
    }
}
