//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_HUMAN_chamcong
    {
        public int Nhan_su { get; set; }
        public short dvcs { get; set; }
        public System.DateTime Ngay_thc { get; set; }
        public System.DateTime Thoi_gian { get; set; }
        public int Ra { get; set; }
        public System.DateTime datetime { get; set; }
        public int Loai_Cong { get; set; }
        public decimal f_identity { get; set; }
        public short Ma_user { get; set; }
        public short ma_user1 { get; set; }
        public string ghi_chu { get; set; }
        public int ok { get; set; }
    }
}
