//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_TIMKIEM
    {
        public byte cap { get; set; }
        public string ma { get; set; }
        public string tendm { get; set; }
        public int timkiem { get; set; }
        public string VIETNAM { get; set; }
        public string ENGLISH { get; set; }
        public string caccot { get; set; }
        public string datquyen { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
        public string cacnut { get; set; }
        public string startfilter { get; set; }
        public string cot_ReadOnly { get; set; }
    }
}
