//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_CT_Vat_Tu
    {
        public System.DateTime ngay_thc { get; set; }
        public string chung_tu { get; set; }
        public int ma_scr { get; set; }
        public int ma_tp { get; set; }
        public int ma_thb { get; set; }
        public decimal so_luong { get; set; }
        public System.DateTime ngay_dap_ung { get; set; }
        public int ma_user { get; set; }
        public int ma_user1 { get; set; }
        public System.DateTime datetime { get; set; }
        public decimal f_identity { get; set; }
        public string don_dat_hang { get; set; }
        public decimal sl_dk_sx { get; set; }
    }
}
