//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_KHANG_KHANGKD
    {
        public int MA_KHKD { get; set; }
        public string MA { get; set; }
        public byte CAP { get; set; }
        public string TEN { get; set; }
        public string DAC_THU { get; set; }
        public string PHONE { get; set; }
        public string TKHOAN_NH { get; set; }
        public short DVCS { get; set; }
        public string CO { get; set; }
        public string DIA_CHI { get; set; }
        public string MA_GTGT { get; set; }
        public decimal MA_USER { get; set; }
        public string TEN_ENG { get; set; }
        public string TEN_TM { get; set; }
        public int TINH_TP { get; set; }
        public string FAX { get; set; }
        public string E_MAIL { get; set; }
        public string NGUOI_GD { get; set; }
        public string CV_GD { get; set; }
        public string PHONE_GD { get; set; }
        public string KT_TRUONG { get; set; }
        public string PHONE_KTT { get; set; }
        public string ISO { get; set; }
        public int LOAIHINH { get; set; }
        public int LINH_VUC { get; set; }
        public string TENSOFT { get; set; }
        public string GHI_CHU { get; set; }
        public System.DateTime DATE { get; set; }
        public string HIENTRANG { get; set; }
        public byte DUY_TRI { get; set; }
        public System.DateTime START_DATE { get; set; }
        public System.DateTime END_DATE { get; set; }
        public decimal BAO_GIA { get; set; }
        public string DV_DO { get; set; }
        public int NGUON { get; set; }
        public int SOFTWARE { get; set; }
        public int CHUC_VU { get; set; }
        public int MA_KH { get; set; }
        public System.DateTime BIRTHDATE { get; set; }
        public string DC_GH { get; set; }
        public short SL_GD { get; set; }
        public string WEBSITE { get; set; }
        public string ATTACH { get; set; }
        public decimal f_identity { get; set; }
        public System.DateTime datetime { get; set; }
    }
}
