//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_HUMAN_BANG_CC
    {
        public decimal COUNTER { get; set; }
        public short DVCS { get; set; }
        public int MA_USER { get; set; }
        public byte VAO { get; set; }
        public byte RA { get; set; }
        public System.DateTime NGAY { get; set; }
        public string GIO_VAO { get; set; }
        public string GIO_RA { get; set; }
        public decimal THOIGIAN { get; set; }
    }
}
