//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_KHANG_TINH_TP
    {
        public int TINH_TP { get; set; }
        public string TEN { get; set; }
        public short MA_USER { get; set; }
        public decimal f_identity { get; set; }
    }
}
