//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_ORDER_KEHOACH1
    {
        public decimal COUNTER { get; set; }
        public System.DateTime NGAY_THC { get; set; }
        public short MA_USERCG { get; set; }
        public string S2 { get; set; }
        public string C2 { get; set; }
        public string S3 { get; set; }
        public string C3 { get; set; }
        public string S4 { get; set; }
        public string C4 { get; set; }
        public string S5 { get; set; }
        public string C5 { get; set; }
        public string S6 { get; set; }
        public string C6 { get; set; }
        public string S7 { get; set; }
        public string C7 { get; set; }
    }
}
