//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_KHANG_BAOGIA
    {
        public decimal COUNTER { get; set; }
        public System.DateTime NGAY_THC { get; set; }
        public string PHIEN_BAN { get; set; }
        public int MA_KHKD { get; set; }
        public string GHI_CHU { get; set; }
        public decimal PS_NO1 { get; set; }
        public string DV_DO { get; set; }
        public decimal TL_GIA { get; set; }
        public string BGIA_DBF { get; set; }
        public string BGIA_WORD { get; set; }
        public short MA_USER { get; set; }
        public System.DateTime DATETIME { get; set; }
    }
}
