//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_HUMAN_DC_BHXH
    {
        public decimal COUNTER { get; set; }
        public string TANGGIAM { get; set; }
        public byte THANG { get; set; }
        public short NAM { get; set; }
        public int NHAN_SU { get; set; }
        public decimal LUONG_CB0 { get; set; }
        public decimal PHU_CAP0 { get; set; }
        public decimal LUONG_CB1 { get; set; }
        public decimal PHU_CAP1 { get; set; }
        public byte TU_THANG { get; set; }
        public short TU_NAM { get; set; }
        public string GHI_CHU { get; set; }
        public short DVCS { get; set; }
        public decimal f_identity { get; set; }
    }
}
