//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_ORDER_MAYCHAMC
    {
        public decimal COUNTER { get; set; }
        public short MA_USERNV { get; set; }
        public System.DateTime NGAY { get; set; }
        public string VAO { get; set; }
        public string RA { get; set; }
        public short TRE { get; set; }
        public short HOP_LE { get; set; }
        public string LY_DO { get; set; }
    }
}
