//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_HUMAN_DK_KCB
    {
        public int DK_KCB { get; set; }
        public string TEN { get; set; }
        public string DIA_CHI { get; set; }
        public System.DateTime DATETIME { get; set; }
        public decimal f_identity { get; set; }
    }
}
