//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_ORDER_DU_LIEU
    {
        public decimal COUNTER { get; set; }
        public System.DateTime NGAY_THC { get; set; }
        public System.DateTime DEN_NGAY { get; set; }
        public string THU { get; set; }
        public int MA_KH { get; set; }
        public int KHOANMUC { get; set; }
        public string PERSONS { get; set; }
        public string CONG_VIEC { get; set; }
        public string KET_QUA { get; set; }
        public string YK_KHANG { get; set; }
        public string YK_EFFECT { get; set; }
        public string SANG_CHIEU { get; set; }
        public decimal TIEN_THU { get; set; }
        public string PHAN_TRAM { get; set; }
        public string TG_HTHANH { get; set; }
        public short MA_USER { get; set; }
        public System.DateTime DATETIME { get; set; }
        public byte DIA_DIEM { get; set; }
        public decimal TIGAN { get; set; }
        public int NOPMUON { get; set; }
        public byte DIEM1 { get; set; }
        public byte DIEM2 { get; set; }
        public byte DIEM3 { get; set; }
        public byte DIEM4 { get; set; }
        public byte DIEM5 { get; set; }
        public byte TONGDIEM { get; set; }
    }
}
