//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_HUMAN_GIA_DINH
    {
        public decimal COUNTER { get; set; }
        public int NHAN_SU { get; set; }
        public string TEN { get; set; }
        public string QUAN_HE { get; set; }
        public short NAM_SINH { get; set; }
        public string NGHENGHIEP { get; set; }
        public string DIA_CHI { get; set; }
        public short DVCS { get; set; }
        public string CO { get; set; }
        public short MA_USER { get; set; }
    }
}
