//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_HUMAN_PS_DTAO
    {
        public int NHAN_SU { get; set; }
        public string DTAO_BD { get; set; }
        public string TEN_TRUONG { get; set; }
        public string CH_NGANH { get; set; }
        public System.DateTime TU_NGAY { get; set; }
        public System.DateTime DEN_NGAY { get; set; }
        public string CHEDO_HOC { get; set; }
        public string VAN_BANG { get; set; }
        public short DVCS { get; set; }
        public System.DateTime datetime { get; set; }
        public decimal f_identity { get; set; }
    }
}
