//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_ORDER_KEHOACH
    {
        public decimal COUNTER { get; set; }
        public System.DateTime NGAY_THC { get; set; }
        public string THU { get; set; }
        public string SANG_CHIEU { get; set; }
        public int MA_KH { get; set; }
        public string NOI_DUNG { get; set; }
        public short MA_USER { get; set; }
        public System.DateTime DATETIME { get; set; }
    }
}
