//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_TASK_MAIL
    {
        public decimal COUNTER { get; set; }
        public string SUBJECT { get; set; }
        public string CONTENT { get; set; }
        public string ATTACH { get; set; }
        public string PROC_ { get; set; }
        public string SUSERS { get; set; }
        public string NGUOI_NHAN { get; set; }
        public System.DateTime DATE { get; set; }
        public System.DateTime END_DATE { get; set; }
        public System.DateTime REMAN_DATE { get; set; }
        public byte HANG_THANG { get; set; }
        public byte HANG_NAM { get; set; }
        public string REMAN_HOUR { get; set; }
        public short PERI_MINS { get; set; }
        public short END_AFTERS { get; set; }
        public System.DateTime END_TODATE { get; set; }
        public string OCCU_WHEN { get; set; }
        public string OCCU_DAYS { get; set; }
        public byte SENT { get; set; }
        public byte COMPLETED { get; set; }
        public string ATTACHMENT { get; set; }
        public short MA_USER { get; set; }
        public string DATETIMER { get; set; }
        public System.DateTime DATETIME { get; set; }
    }
}
