//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRXOBJ
    {
        public int ma_repo { get; set; }
        public int Stt { get; set; }
        public string Type { get; set; }
        public string ViTri { get; set; }
        public string C_Align { get; set; }
        public int C_Left { get; set; }
        public int C_Top { get; set; }
        public int C_Width { get; set; }
        public int C_Height { get; set; }
        public string C_Font { get; set; }
        public string Color { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime DateTime { get; set; }
        public int f_identity { get; set; }
    }
}
