//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class HinhCay
    {
        public string ma { get; set; }
        public Nullable<decimal> tien { get; set; }
        public Nullable<decimal> sl { get; set; }
        public string chung_tu { get; set; }
    }
}
