//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class HTKK_dulieu
    {
        public System.DateTime ngay_thc { get; set; }
        public string tenfile { get; set; }
        public string path { get; set; }
        public decimal value { get; set; }
        public string mst { get; set; }
        public short ma_user { get; set; }
        public System.DateTime datetime { get; set; }
    }
}
