//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterfaceRegulation
    {
        public string version { get; set; }
        public string thongtu { get; set; }
        public string MainFormBackground { get; set; }
        public string AllFormBackgroundColor { get; set; }
        public string TitleMainForm { get; set; }
        public string TitleMainFormEnglish { get; set; }
        public string FooterInputForm { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
    }
}
