//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTCDKT_CongThuc
    {
        public string ChiTieu { get; set; }
        public string CT_tr1 { get; set; }
        public decimal f { get; set; }
        public Nullable<int> TT { get; set; }
        public decimal f_identity { get; set; }
    }
}
