//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTCDKT_TKLuongTinh
    {
        public string Ham { get; set; }
        public string TK { get; set; }
        public Nullable<decimal> DN { get; set; }
        public Nullable<decimal> DC { get; set; }
        public string HamFull { get; set; }
        public decimal f_identity { get; set; }
    }
}
