//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuFormfit
    {
        public string TableName { get; set; }
        public byte cap0 { get; set; }
        public string ma { get; set; }
        public string ten { get; set; }
        public string image { get; set; }
        public string proc_ { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
    }
}
