//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageBoxLanguage
    {
        public string language { get; set; }
        public string btn_OK { get; set; }
        public string btn_Cancel { get; set; }
        public string btn_Yes { get; set; }
        public string btn_No { get; set; }
        public string btn_Abort { get; set; }
        public string btn_Ignore { get; set; }
        public string btn_Retry { get; set; }
    }
}
