//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EFF_EFFE_200Entities : DbContext
    {
        public EFF_EFFE_200Entities()
            : base("name=EFF_EFFE_200Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__Dich> C__Dich { get; set; }
        public virtual DbSet<C_APICYBER> C_APICYBER { get; set; }
        public virtual DbSet<C_APIFPT> C_APIFPT { get; set; }
        public virtual DbSet<C_APIFPT_TT78> C_APIFPT_TT78 { get; set; }
        public virtual DbSet<C_APIMINVOICE> C_APIMINVOICE { get; set; }
        public virtual DbSet<C_APIMOBIFONE> C_APIMOBIFONE { get; set; }
        public virtual DbSet<C_APIMOBIFONE_78> C_APIMOBIFONE_78 { get; set; }
        public virtual DbSet<C_APINACENCOM> C_APINACENCOM { get; set; }
        public virtual DbSet<C_APIViettel> C_APIViettel { get; set; }
        public virtual DbSet<C_APIViettinbank> C_APIViettinbank { get; set; }
        public virtual DbSet<C_BANGDGIA> C_BANGDGIA { get; set; }
        public virtual DbSet<C_banhang_1_1_0> C_banhang_1_1_0 { get; set; }
        public virtual DbSet<C_BO> C_BO { get; set; }
        public virtual DbSet<C_BO_NHO> C_BO_NHO { get; set; }
        public virtual DbSet<C_BO_PHAN> C_BO_PHAN { get; set; }
        public virtual DbSet<C_BSCSTR> C_BSCSTR { get; set; }
        public virtual DbSet<C_cauhinh_fpt> C_cauhinh_fpt { get; set; }
        public virtual DbSet<C_cauhinh_fpt_TT78> C_cauhinh_fpt_TT78 { get; set; }
        public virtual DbSet<C_cauhinh_nacencom> C_cauhinh_nacencom { get; set; }
        public virtual DbSet<C_cautruc> C_cautruc { get; set; }
        public virtual DbSet<C_CCDC> C_CCDC { get; set; }
        public virtual DbSet<C_CHART> C_CHART { get; set; }
        public virtual DbSet<C_CHITIET_BO> C_CHITIET_BO { get; set; }
        public virtual DbSet<C_Chuyen_doi_screen_Convert> C_Chuyen_doi_screen_Convert { get; set; }
        public virtual DbSet<C_Chuyen_doi_tai_khoan_Convert> C_Chuyen_doi_tai_khoan_Convert { get; set; }
        public virtual DbSet<C_DINHMUC1> C_DINHMUC1 { get; set; }
        public virtual DbSet<C_dongcuoi> C_dongcuoi { get; set; }
        public virtual DbSet<C_duongdan> C_duongdan { get; set; }
        public virtual DbSet<C_DV> C_DV { get; set; }
        public virtual DbSet<C_EFF_Translate> C_EFF_Translate { get; set; }
        public virtual DbSet<C_FileAttachBkav> C_FileAttachBkav { get; set; }
        public virtual DbSet<C_FORM> C_FORM { get; set; }
        public virtual DbSet<C_form_erp> C_form_erp { get; set; }
        public virtual DbSet<C_GIAOTIEPE> C_GIAOTIEPE { get; set; }
        public virtual DbSet<C_HDDT_CONFIG_FUNC_WEBSERVICE> C_HDDT_CONFIG_FUNC_WEBSERVICE { get; set; }
        public virtual DbSet<C_HDDT_CONFIG_TOKEN_FUNC_WEBSERVICE> C_HDDT_CONFIG_TOKEN_FUNC_WEBSERVICE { get; set; }
        public virtual DbSet<C_HDDT_PARAMETER_STRUCT> C_HDDT_PARAMETER_STRUCT { get; set; }
        public virtual DbSet<C_HDDT_STRUCT_XML_FUNC_SERVICE> C_HDDT_STRUCT_XML_FUNC_SERVICE { get; set; }
        public virtual DbSet<C_history_edit> C_history_edit { get; set; }
        public virtual DbSet<C_history_erp2> C_history_erp2 { get; set; }
        public virtual DbSet<C_hrm_cautrucnhomluong> C_hrm_cautrucnhomluong { get; set; }
        public virtual DbSet<C_hrm_chamcongtong_1_1_0> C_hrm_chamcongtong_1_1_0 { get; set; }
        public virtual DbSet<C_hrm_chamcongtong_1_12_0> C_hrm_chamcongtong_1_12_0 { get; set; }
        public virtual DbSet<C_hrm_chamcongtong_1_14_0> C_hrm_chamcongtong_1_14_0 { get; set; }
        public virtual DbSet<C_hrm_chamcongtong_1_16_0> C_hrm_chamcongtong_1_16_0 { get; set; }
        public virtual DbSet<C_hrm_chamcongtong_1_2_0> C_hrm_chamcongtong_1_2_0 { get; set; }
        public virtual DbSet<C_hrm_chamcongtong_1_6_0> C_hrm_chamcongtong_1_6_0 { get; set; }
        public virtual DbSet<C_hrm_chamcongtong_1_8_0> C_hrm_chamcongtong_1_8_0 { get; set; }
        public virtual DbSet<C_hrm_chamcongtong_2_12_0> C_hrm_chamcongtong_2_12_0 { get; set; }
        public virtual DbSet<C_hrm_dlluongtong_1_1_0> C_hrm_dlluongtong_1_1_0 { get; set; }
        public virtual DbSet<C_hrm_dlluongtong_1_12_0> C_hrm_dlluongtong_1_12_0 { get; set; }
        public virtual DbSet<C_hrm_dlluongtong_1_16_0> C_hrm_dlluongtong_1_16_0 { get; set; }
        public virtual DbSet<C_hrm_dlluongtong_1_6_0> C_hrm_dlluongtong_1_6_0 { get; set; }
        public virtual DbSet<C_hrm_dlluongtong_1_8_0> C_hrm_dlluongtong_1_8_0 { get; set; }
        public virtual DbSet<C_hrm_dlluongtong_2_12_0> C_hrm_dlluongtong_2_12_0 { get; set; }
        public virtual DbSet<C_hrm_nhanvien_1_1_0> C_hrm_nhanvien_1_1_0 { get; set; }
        public virtual DbSet<C_hrm_nhanvien_1_12_0> C_hrm_nhanvien_1_12_0 { get; set; }
        public virtual DbSet<C_hrm_nhanvien_1_14_0> C_hrm_nhanvien_1_14_0 { get; set; }
        public virtual DbSet<C_hrm_nhanvien_1_16_0> C_hrm_nhanvien_1_16_0 { get; set; }
        public virtual DbSet<C_hrm_nhanvien_1_2_0> C_hrm_nhanvien_1_2_0 { get; set; }
        public virtual DbSet<C_hrm_nhanvien_1_6_0> C_hrm_nhanvien_1_6_0 { get; set; }
        public virtual DbSet<C_hrm_nhanvien_1_6_1> C_hrm_nhanvien_1_6_1 { get; set; }
        public virtual DbSet<C_hrm_nhanvien_1_8_0> C_hrm_nhanvien_1_8_0 { get; set; }
        public virtual DbSet<C_hrm_nhanvien_2_12_0> C_hrm_nhanvien_2_12_0 { get; set; }
        public virtual DbSet<C_hrm_phuthuoc> C_hrm_phuthuoc { get; set; }
        public virtual DbSet<C_hrm_qtthue_1_1_0> C_hrm_qtthue_1_1_0 { get; set; }
        public virtual DbSet<C_hrm_qtthue_1_12_0> C_hrm_qtthue_1_12_0 { get; set; }
        public virtual DbSet<C_hrm_qtthue_1_14_0> C_hrm_qtthue_1_14_0 { get; set; }
        public virtual DbSet<C_hrm_qtthue_1_16_0> C_hrm_qtthue_1_16_0 { get; set; }
        public virtual DbSet<C_hrm_qtthue_1_6_0> C_hrm_qtthue_1_6_0 { get; set; }
        public virtual DbSet<C_hrm_qtthue_1_8_0> C_hrm_qtthue_1_8_0 { get; set; }
        public virtual DbSet<C_hrm_qtthue_2_12_0> C_hrm_qtthue_2_12_0 { get; set; }
        public virtual DbSet<C_hrm_quyetdinh> C_hrm_quyetdinh { get; set; }
        public virtual DbSet<C_hrm_quyetdinhtong_1_1_0> C_hrm_quyetdinhtong_1_1_0 { get; set; }
        public virtual DbSet<C_hrm_quyetdinhtong_1_12_0> C_hrm_quyetdinhtong_1_12_0 { get; set; }
        public virtual DbSet<C_hrm_quyetdinhtong_1_14_0> C_hrm_quyetdinhtong_1_14_0 { get; set; }
        public virtual DbSet<C_hrm_quyetdinhtong_1_16_0> C_hrm_quyetdinhtong_1_16_0 { get; set; }
        public virtual DbSet<C_hrm_quyetdinhtong_1_2_0> C_hrm_quyetdinhtong_1_2_0 { get; set; }
        public virtual DbSet<C_hrm_quyetdinhtong_1_6_0> C_hrm_quyetdinhtong_1_6_0 { get; set; }
        public virtual DbSet<C_hrm_quyetdinhtong_1_8_0> C_hrm_quyetdinhtong_1_8_0 { get; set; }
        public virtual DbSet<C_hrm_quyetdinhtong_2_12_0> C_hrm_quyetdinhtong_2_12_0 { get; set; }
        public virtual DbSet<C_hrm_vitri> C_hrm_vitri { get; set; }
        public virtual DbSet<C_InvoicesBKAV> C_InvoicesBKAV { get; set; }
        public virtual DbSet<C_InvoicesCyber> C_InvoicesCyber { get; set; }
        public virtual DbSet<C_InvoicesFpt> C_InvoicesFpt { get; set; }
        public virtual DbSet<C_InvoicesMinvoice> C_InvoicesMinvoice { get; set; }
        public virtual DbSet<C_InvoicesMISA> C_InvoicesMISA { get; set; }
        public virtual DbSet<C_InvoicesMobifone> C_InvoicesMobifone { get; set; }
        public virtual DbSet<C_InvoicesNacencom> C_InvoicesNacencom { get; set; }
        public virtual DbSet<C_InvoicesSoftdream> C_InvoicesSoftdream { get; set; }
        public virtual DbSet<C_InvoicesViettel> C_InvoicesViettel { get; set; }
        public virtual DbSet<C_InvoicesViettel1> C_InvoicesViettel1 { get; set; }
        public virtual DbSet<C_InvoicesVNPT> C_InvoicesVNPT { get; set; }
        public virtual DbSet<C_KMUC_T> C_KMUC_T { get; set; }
        public virtual DbSet<C_KSCfg> C_KSCfg { get; set; }
        public virtual DbSet<C_KTRA_CTU> C_KTRA_CTU { get; set; }
        public virtual DbSet<C_KHANG> C_KHANG { get; set; }
        public virtual DbSet<C_KHANG_T> C_KHANG_T { get; set; }
        public virtual DbSet<C_KHOANMUC> C_KHOANMUC { get; set; }
        public virtual DbSet<C_KHPW> C_KHPW { get; set; }
        public virtual DbSet<C_KHPW2> C_KHPW2 { get; set; }
        public virtual DbSet<C_LINHVUC> C_LINHVUC { get; set; }
        public virtual DbSet<C_LOAI_KH> C_LOAI_KH { get; set; }
        public virtual DbSet<C_LOAI_NX> C_LOAI_NX { get; set; }
        public virtual DbSet<C_LOAI_TB> C_LOAI_TB { get; set; }
        public virtual DbSet<C_LOAI_TBT> C_LOAI_TBT { get; set; }
        public virtual DbSet<C_LOAI_TC> C_LOAI_TC { get; set; }
        public virtual DbSet<C_LOAIDL> C_LOAIDL { get; set; }
        public virtual DbSet<C_LOG> C_LOG { get; set; }
        public virtual DbSet<C_LOG_Invoices> C_LOG_Invoices { get; set; }
        public virtual DbSet<C_LUONG_NH> C_LUONG_NH { get; set; }
        public virtual DbSet<C_MAIL> C_MAIL { get; set; }
        public virtual DbSet<C_MAIL_GROUP> C_MAIL_GROUP { get; set; }
        public virtual DbSet<C_MAUSERI> C_MAUSERI { get; set; }
        public virtual DbSet<C_MUCLUC> C_MUCLUC { get; set; }
        public virtual DbSet<C_MUCLUC_T> C_MUCLUC_T { get; set; }
        public virtual DbSet<C_NCCHD> C_NCCHD { get; set; }
        public virtual DbSet<C_Noidung1> C_Noidung1 { get; set; }
        public virtual DbSet<C_NGUON> C_NGUON { get; set; }
        public virtual DbSet<C_NHOM_NHO> C_NHOM_NHO { get; set; }
        public virtual DbSet<C_PHNX> C_PHNX { get; set; }
        public virtual DbSet<C_quanly_database> C_quanly_database { get; set; }
        public virtual DbSet<C_REPORT> C_REPORT { get; set; }
        public virtual DbSet<C_REPORT_BSC> C_REPORT_BSC { get; set; }
        public virtual DbSet<C_Report_Recent> C_Report_Recent { get; set; }
        public virtual DbSet<C_ReportFilter> C_ReportFilter { get; set; }
        public virtual DbSet<C_SALESMAN> C_SALESMAN { get; set; }
        public virtual DbSet<C_SCREEN> C_SCREEN { get; set; }
        public virtual DbSet<C_screen_danhmuc_code> C_screen_danhmuc_code { get; set; }
        public virtual DbSet<C_screen_danhmuc_form> C_screen_danhmuc_form { get; set; }
        public virtual DbSet<C_screen_danhmuc_tim> C_screen_danhmuc_tim { get; set; }
        public virtual DbSet<C_screen_erp2_code> C_screen_erp2_code { get; set; }
        public virtual DbSet<C_screen_erp2_ex> C_screen_erp2_ex { get; set; }
        public virtual DbSet<C_screen_erp2_form> C_screen_erp2_form { get; set; }
        public virtual DbSet<C_screenobj> C_screenobj { get; set; }
        public virtual DbSet<C_SL_CPC> C_SL_CPC { get; set; }
        public virtual DbSet<C_SL_TTPB> C_SL_TTPB { get; set; }
        public virtual DbSet<C_struct_import> C_struct_import { get; set; }
        public virtual DbSet<C_struct_import2> C_struct_import2 { get; set; }
        public virtual DbSet<C_tableDKRowFilter> C_tableDKRowFilter { get; set; }
        public virtual DbSet<C_TBI_T> C_TBI_T { get; set; }
        public virtual DbSet<C_tblKCDuK> C_tblKCDuK { get; set; }
        public virtual DbSet<C_TITBROW> C_TITBROW { get; set; }
        public virtual DbSet<C_titbrow_fox> C_titbrow_fox { get; set; }
        public virtual DbSet<C_TKNHANG> C_TKNHANG { get; set; }
        public virtual DbSet<C_TKHOAN> C_TKHOAN { get; set; }
        public virtual DbSet<C_TSCD> C_TSCD { get; set; }
        public virtual DbSet<C_TSCD_T> C_TSCD_T { get; set; }
        public virtual DbSet<C_tthaihd> C_tthaihd { get; set; }
        public virtual DbSet<C_THIETBI> C_THIETBI { get; set; }
        public virtual DbSet<C_THU_TIEN> C_THU_TIEN { get; set; }
        public virtual DbSet<C_THU_TIEN_THUE> C_THU_TIEN_THUE { get; set; }
        public virtual DbSet<C_uploadfile> C_uploadfile { get; set; }
        public virtual DbSet<C_USERS> C_USERS { get; set; }
        public virtual DbSet<C_ViewMethod> C_ViewMethod { get; set; }
        public virtual DbSet<C_ViewMethod_Group> C_ViewMethod_Group { get; set; }
        public virtual DbSet<C_VUNG> C_VUNG { get; set; }
        public virtual DbSet<C_VVIEC> C_VVIEC { get; set; }
        public virtual DbSet<C_vviec_1_1_0> C_vviec_1_1_0 { get; set; }
        public virtual DbSet<C_vviec_1_8_0> C_vviec_1_8_0 { get; set; }
        public virtual DbSet<APEXSQL_LOG_CONNECTION_MONITOR_SESSION> APEXSQL_LOG_CONNECTION_MONITOR_SESSION { get; set; }
        public virtual DbSet<APEXSQL_LOG_STRINGS> APEXSQL_LOG_STRINGS { get; set; }
        public virtual DbSet<EFF_TMDV_KS_khang6868> EFF_TMDV_KS_khang6868 { get; set; }
        public virtual DbSet<ERP_HUMAN_DC_BHXH> ERP_HUMAN_DC_BHXH { get; set; }
        public virtual DbSet<ERP_HUMAN_DK_KCB> ERP_HUMAN_DK_KCB { get; set; }
        public virtual DbSet<ERP_HUMAN_HD_LDONG> ERP_HUMAN_HD_LDONG { get; set; }
        public virtual DbSet<ERP_HUMAN_KNANG_NV> ERP_HUMAN_KNANG_NV { get; set; }
        public virtual DbSet<ERP_HUMAN_KYLUAT> ERP_HUMAN_KYLUAT { get; set; }
        public virtual DbSet<ERP_HUMAN_KHTHUONG> ERP_HUMAN_KHTHUONG { get; set; }
        public virtual DbSet<ERP_HUMAN_NGANH_DT> ERP_HUMAN_NGANH_DT { get; set; }
        public virtual DbSet<ERP_HUMAN_NHAN_SU> ERP_HUMAN_NHAN_SU { get; set; }
        public virtual DbSet<ERP_HUMAN_PS_DTAO> ERP_HUMAN_PS_DTAO { get; set; }
        public virtual DbSet<ERP_HUMAN_TINH> ERP_HUMAN_TINH { get; set; }
        public virtual DbSet<ERP_HUMAN_TRINH_DO> ERP_HUMAN_TRINH_DO { get; set; }
        public virtual DbSet<ERP_IMAGE> ERP_IMAGE { get; set; }
        public virtual DbSet<ERP_KHANG_BANGGIA> ERP_KHANG_BANGGIA { get; set; }
        public virtual DbSet<ERP_KHANG_CHUC_VU> ERP_KHANG_CHUC_VU { get; set; }
        public virtual DbSet<ERP_KHANG_DK_KMGG> ERP_KHANG_DK_KMGG { get; set; }
        public virtual DbSet<ERP_KHANG_KM_GGIA> ERP_KHANG_KM_GGIA { get; set; }
        public virtual DbSet<ERP_KHANG_KHANGKD> ERP_KHANG_KHANGKD { get; set; }
        public virtual DbSet<ERP_KHANG_LINH_VUC> ERP_KHANG_LINH_VUC { get; set; }
        public virtual DbSet<ERP_KHANG_LOAIHINH> ERP_KHANG_LOAIHINH { get; set; }
        public virtual DbSet<ERP_KHANG_SOFTWARE> ERP_KHANG_SOFTWARE { get; set; }
        public virtual DbSet<ERP_KHANG_T_TRANG> ERP_KHANG_T_TRANG { get; set; }
        public virtual DbSet<ERP_KHANG_TINH_TP> ERP_KHANG_TINH_TP { get; set; }
        public virtual DbSet<ERP_loaidl> ERP_loaidl { get; set; }
        public virtual DbSet<FRXOBJ> FRXOBJ { get; set; }
        public virtual DbSet<HTKK> HTKK { get; set; }
        public virtual DbSet<R781_004_1_20200219082303_1_4_0> R781_004_1_20200219082303_1_4_0 { get; set; }
        public virtual DbSet<R781_004_1_20200219082402_1_4_0> R781_004_1_20200219082402_1_4_0 { get; set; }
        public virtual DbSet<R781_004_1_20200219082527_1_4_0> R781_004_1_20200219082527_1_4_0 { get; set; }
        public virtual DbSet<R781_004_1_20200219082618_1_4_0> R781_004_1_20200219082618_1_4_0 { get; set; }
        public virtual DbSet<R781_004_1_20200219082825_1_4_0> R781_004_1_20200219082825_1_4_0 { get; set; }
        public virtual DbSet<R781_004_1_20200219083616_1_4_0> R781_004_1_20200219083616_1_4_0 { get; set; }
        public virtual DbSet<R781_004_1_20200219083638_1_4_0> R781_004_1_20200219083638_1_4_0 { get; set; }
        public virtual DbSet<R781_004_1_20200219083747_1_4_0> R781_004_1_20200219083747_1_4_0 { get; set; }
        public virtual DbSet<R781_004_1_20200219083822_1_4_0> R781_004_1_20200219083822_1_4_0 { get; set; }
        public virtual DbSet<R781_004_1_20200219083837_1_4_0> R781_004_1_20200219083837_1_4_0 { get; set; }
        public virtual DbSet<R781_004_1_20200219083936_1_4_0> R781_004_1_20200219083936_1_4_0 { get; set; }
        public virtual DbSet<R781_004_1_20200219084012_1_4_0> R781_004_1_20200219084012_1_4_0 { get; set; }
        public virtual DbSet<R781_004_1_20200219084029_1_4_0> R781_004_1_20200219084029_1_4_0 { get; set; }
        public virtual DbSet<R781_004_1_20200219084139_1_4_0> R781_004_1_20200219084139_1_4_0 { get; set; }
        public virtual DbSet<R781_004_1_20200219084147_1_4_0> R781_004_1_20200219084147_1_4_0 { get; set; }
        public virtual DbSet<R781_004_1_20200219085038_1_4_0> R781_004_1_20200219085038_1_4_0 { get; set; }
        public virtual DbSet<R781_004_1_20200219085103_1_4_0> R781_004_1_20200219085103_1_4_0 { get; set; }
        public virtual DbSet<R781_004_1_20200219085219_1_4_0> R781_004_1_20200219085219_1_4_0 { get; set; }
        public virtual DbSet<R781_004_1_20200219085230_1_4_0> R781_004_1_20200219085230_1_4_0 { get; set; }
        public virtual DbSet<R811_001_1_20231222144031_1_1_0> R811_001_1_20231222144031_1_1_0 { get; set; }
        public virtual DbSet<R811_001_1_20231222144201_1_1_0> R811_001_1_20231222144201_1_1_0 { get; set; }
        public virtual DbSet<R811_001_1_20231222144238_1_1_0> R811_001_1_20231222144238_1_1_0 { get; set; }
        public virtual DbSet<R815_001_1_20231222104542_1_1_0> R815_001_1_20231222104542_1_1_0 { get; set; }
        public virtual DbSet<R819_001_1_20231222145657_1_1_0> R819_001_1_20231222145657_1_1_0 { get; set; }
        public virtual DbSet<R819_001_1_20231222145700_1_1_0> R819_001_1_20231222145700_1_1_0 { get; set; }
        public virtual DbSet<R819_006_1_20231220134932_1_6_0> R819_006_1_20231220134932_1_6_0 { get; set; }
        public virtual DbSet<R819_006_1_20231220135752_1_6_0> R819_006_1_20231220135752_1_6_0 { get; set; }
        public virtual DbSet<R821_002_1_20230922163443_1_2_0> R821_002_1_20230922163443_1_2_0 { get; set; }
        public virtual DbSet<R821_002_1_20230922163444_1_2_0> R821_002_1_20230922163444_1_2_0 { get; set; }
        public virtual DbSet<R821_002_1_20230922163545_1_2_0> R821_002_1_20230922163545_1_2_0 { get; set; }
        public virtual DbSet<R821_002_1_20230922163546_1_2_0> R821_002_1_20230922163546_1_2_0 { get; set; }
        public virtual DbSet<R821_002_1_20230922163644_1_2_0> R821_002_1_20230922163644_1_2_0 { get; set; }
        public virtual DbSet<R821_002_1_20230922163645_1_2_0> R821_002_1_20230922163645_1_2_0 { get; set; }
        public virtual DbSet<R821_002_1_20230922163717_1_2_0> R821_002_1_20230922163717_1_2_0 { get; set; }
        public virtual DbSet<R821_002_1_20230922163718_1_2_0> R821_002_1_20230922163718_1_2_0 { get; set; }
        public virtual DbSet<R821_002_1_20230922163823_1_2_0> R821_002_1_20230922163823_1_2_0 { get; set; }
        public virtual DbSet<R821_002_1_20230922163843_1_2_0> R821_002_1_20230922163843_1_2_0 { get; set; }
        public virtual DbSet<R821_002_1_20230922163844_1_2_0> R821_002_1_20230922163844_1_2_0 { get; set; }
        public virtual DbSet<R821_002_1_20230922163914_1_2_0> R821_002_1_20230922163914_1_2_0 { get; set; }
        public virtual DbSet<R821_002_1_20230922163915_1_2_0> R821_002_1_20230922163915_1_2_0 { get; set; }
        public virtual DbSet<R821_002_1_20230922164006_1_2_0> R821_002_1_20230922164006_1_2_0 { get; set; }
        public virtual DbSet<R821_002_1_20230922164007_1_2_0> R821_002_1_20230922164007_1_2_0 { get; set; }
        public virtual DbSet<R821_002_1_20230922164113_1_2_0> R821_002_1_20230922164113_1_2_0 { get; set; }
        public virtual DbSet<R821_002_1_20230922164232_1_2_0> R821_002_1_20230922164232_1_2_0 { get; set; }
        public virtual DbSet<R821_002_1_20230922164233_1_2_0> R821_002_1_20230922164233_1_2_0 { get; set; }
        public virtual DbSet<R821_002_1_20230922164332_1_2_0> R821_002_1_20230922164332_1_2_0 { get; set; }
        public virtual DbSet<R821_002_1_20230922164333_1_2_0> R821_002_1_20230922164333_1_2_0 { get; set; }
        public virtual DbSet<R821_002_1_20230922164452_1_2_0> R821_002_1_20230922164452_1_2_0 { get; set; }
        public virtual DbSet<R821_002_1_20230922164453_1_2_0> R821_002_1_20230922164453_1_2_0 { get; set; }
        public virtual DbSet<R821_002_1_20230922164515_1_2_0> R821_002_1_20230922164515_1_2_0 { get; set; }
        public virtual DbSet<R821_002_1_20230922164516_1_2_0> R821_002_1_20230922164516_1_2_0 { get; set; }
        public virtual DbSet<R821_002_1_20230922164712_1_2_0> R821_002_1_20230922164712_1_2_0 { get; set; }
        public virtual DbSet<R821_002_1_20230922164713_1_2_0> R821_002_1_20230922164713_1_2_0 { get; set; }
        public virtual DbSet<R821_006_1_20231221084154_1_6_0> R821_006_1_20231221084154_1_6_0 { get; set; }
        public virtual DbSet<R821_006_1_20231221084155_1_6_0> R821_006_1_20231221084155_1_6_0 { get; set; }
        public virtual DbSet<R821_006_1_20231221084339_1_6_0> R821_006_1_20231221084339_1_6_0 { get; set; }
        public virtual DbSet<R821_006_1_20231221085109_1_6_0> R821_006_1_20231221085109_1_6_0 { get; set; }
        public virtual DbSet<R824_001_1_20230916101947_1_1_0> R824_001_1_20230916101947_1_1_0 { get; set; }
        public virtual DbSet<R824_001_1_20230916102009_1_1_0> R824_001_1_20230916102009_1_1_0 { get; set; }
        public virtual DbSet<R824_001_1_20240306193150_1_1_0> R824_001_1_20240306193150_1_1_0 { get; set; }
        public virtual DbSet<R824_002_1_20230915085147_1_2_0> R824_002_1_20230915085147_1_2_0 { get; set; }
        public virtual DbSet<R824_002_1_20230915085534_1_2_0> R824_002_1_20230915085534_1_2_0 { get; set; }
        public virtual DbSet<R824_006_1_20231214094225_1_6_0> R824_006_1_20231214094225_1_6_0 { get; set; }
        public virtual DbSet<R824_006_1_20231214094320_1_6_0> R824_006_1_20231214094320_1_6_0 { get; set; }
        public virtual DbSet<R824_006_1_20231219101946_1_6_0> R824_006_1_20231219101946_1_6_0 { get; set; }
        public virtual DbSet<R824_006_1_20231221085726_1_6_0> R824_006_1_20231221085726_1_6_0 { get; set; }
        public virtual DbSet<R824_006_1_20231221085801_1_6_0> R824_006_1_20231221085801_1_6_0 { get; set; }
        public virtual DbSet<R824_006_1_20231221085921_1_6_0> R824_006_1_20231221085921_1_6_0 { get; set; }
        public virtual DbSet<R824_006_1_20231221090300_1_6_0> R824_006_1_20231221090300_1_6_0 { get; set; }
        public virtual DbSet<R824_006_1_20231221090545_1_6_0> R824_006_1_20231221090545_1_6_0 { get; set; }
        public virtual DbSet<R824_006_1_20231221090545_1_6_1> R824_006_1_20231221090545_1_6_1 { get; set; }
        public virtual DbSet<R824_006_1_20231221090545_1_6_2> R824_006_1_20231221090545_1_6_2 { get; set; }
        public virtual DbSet<R824_006_1_20231221090545_1_6_3> R824_006_1_20231221090545_1_6_3 { get; set; }
        public virtual DbSet<R824_008_1_20230915085016_1_8_0> R824_008_1_20230915085016_1_8_0 { get; set; }
        public virtual DbSet<R824_008_1_20230915085055_1_8_0> R824_008_1_20230915085055_1_8_0 { get; set; }
        public virtual DbSet<R824_008_1_20230915085621_1_8_0> R824_008_1_20230915085621_1_8_0 { get; set; }
        public virtual DbSet<R824_008_1_20230915112145_1_8_0> R824_008_1_20230915112145_1_8_0 { get; set; }
        public virtual DbSet<R824_008_1_20230915112217_1_8_0> R824_008_1_20230915112217_1_8_0 { get; set; }
        public virtual DbSet<R825_001_1_20240306193151_1_1_0> R825_001_1_20240306193151_1_1_0 { get; set; }
        public virtual DbSet<R825_002_1_20230915085149_1_2_0> R825_002_1_20230915085149_1_2_0 { get; set; }
        public virtual DbSet<R825_002_1_20230915085536_1_2_0> R825_002_1_20230915085536_1_2_0 { get; set; }
        public virtual DbSet<R827_016_1_20240118111430_1_16_0> R827_016_1_20240118111430_1_16_0 { get; set; }
        public virtual DbSet<R829_001_1_20230916101922_1_1_0> R829_001_1_20230916101922_1_1_0 { get; set; }
        public virtual DbSet<R829_002_1_20230915083011_1_2_0> R829_002_1_20230915083011_1_2_0 { get; set; }
        public virtual DbSet<R829_006_1_20231212095109_1_6_0> R829_006_1_20231212095109_1_6_0 { get; set; }
        public virtual DbSet<R829_006_1_20231213145514_1_6_0> R829_006_1_20231213145514_1_6_0 { get; set; }
        public virtual DbSet<R829_006_1_20231219111902_1_6_0> R829_006_1_20231219111902_1_6_0 { get; set; }
        public virtual DbSet<R829_006_1_20231221085542_1_6_0> R829_006_1_20231221085542_1_6_0 { get; set; }
        public virtual DbSet<R829_008_1_20230915085203_1_8_0> R829_008_1_20230915085203_1_8_0 { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Download> tbl_Download { get; set; }
        public virtual DbSet<tbl_Image> tbl_Image { get; set; }
        public virtual DbSet<tbl_LogIn> tbl_LogIn { get; set; }
        public virtual DbSet<tblFunctions> tblFunctions { get; set; }
        public virtual DbSet<tblUserFuntions> tblUserFuntions { get; set; }
        public virtual DbSet<TINHSAU> TINHSAU { get; set; }
        public virtual DbSet<tyle_pb_cn> tyle_pb_cn { get; set; }
        public virtual DbSet<UpdateEffect> UpdateEffect { get; set; }
        public virtual DbSet<UpdateList> UpdateList { get; set; }
        public virtual DbSet<C__bangtamupdatehoadon> C__bangtamupdatehoadon { get; set; }
        public virtual DbSet<C__bangtamupdatehoadon1> C__bangtamupdatehoadon1 { get; set; }
        public virtual DbSet<C__KCPB_TT> C__KCPB_TT { get; set; }
        public virtual DbSet<C__KCPB_TT01> C__KCPB_TT01 { get; set; }
        public virtual DbSet<C_01Luongtmp002_0010> C_01Luongtmp002_0010 { get; set; }
        public virtual DbSet<C_01Luongtmp007_0002> C_01Luongtmp007_0002 { get; set; }
        public virtual DbSet<C_01Luongtmp007_0009> C_01Luongtmp007_0009 { get; set; }
        public virtual DbSet<C_01Luongtmp007_0016> C_01Luongtmp007_0016 { get; set; }
        public virtual DbSet<C_01Luongtmp009_0009> C_01Luongtmp009_0009 { get; set; }
        public virtual DbSet<C_01Luongtmp009_0015> C_01Luongtmp009_0015 { get; set; }
        public virtual DbSet<C_01Luongtmp012_0001> C_01Luongtmp012_0001 { get; set; }
        public virtual DbSet<C_01Luongtmp012_0002> C_01Luongtmp012_0002 { get; set; }
        public virtual DbSet<C_01Luongtmp012_0003> C_01Luongtmp012_0003 { get; set; }
        public virtual DbSet<C_01Luongtmp012_0009> C_01Luongtmp012_0009 { get; set; }
        public virtual DbSet<C_01Luongtmp012_0016> C_01Luongtmp012_0016 { get; set; }
        public virtual DbSet<C_01Luongtmp012_0019> C_01Luongtmp012_0019 { get; set; }
        public virtual DbSet<C_035_loaiTK> C_035_loaiTK { get; set; }
        public virtual DbSet<C_1_hachtoanLuong_1_2> C_1_hachtoanLuong_1_2 { get; set; }
        public virtual DbSet<C_1_hachtoanLuong_1_3> C_1_hachtoanLuong_1_3 { get; set; }
        public virtual DbSet<C_1_hachtoanLuong_1_7> C_1_hachtoanLuong_1_7 { get; set; }
        public virtual DbSet<C_1_hachtoanLuong_2_2> C_1_hachtoanLuong_2_2 { get; set; }
        public virtual DbSet<C_1_hachtoanLuong_2_7> C_1_hachtoanLuong_2_7 { get; set; }
        public virtual DbSet<C_1_hachtoanLuongTAM_1_2> C_1_hachtoanLuongTAM_1_2 { get; set; }
        public virtual DbSet<C_1_hachtoanLuongTAM_1_3> C_1_hachtoanLuongTAM_1_3 { get; set; }
        public virtual DbSet<C_1_hachtoanLuongTAM_1_7> C_1_hachtoanLuongTAM_1_7 { get; set; }
        public virtual DbSet<C_1_hachtoanLuongTAM_2_2> C_1_hachtoanLuongTAM_2_2 { get; set; }
        public virtual DbSet<C_1BienThem> C_1BienThem { get; set; }
        public virtual DbSet<C_1LgNhom002> C_1LgNhom002 { get; set; }
        public virtual DbSet<C_1LgNhom006> C_1LgNhom006 { get; set; }
        public virtual DbSet<C_1LgNhom007> C_1LgNhom007 { get; set; }
        public virtual DbSet<C_1LgNhom008> C_1LgNhom008 { get; set; }
        public virtual DbSet<C_1LgNhom009> C_1LgNhom009 { get; set; }
        public virtual DbSet<C_1LgNhom012> C_1LgNhom012 { get; set; }
        public virtual DbSet<C_api_misa> C_api_misa { get; set; }
        public virtual DbSet<C_Api_SoftDream> C_Api_SoftDream { get; set; }
        public virtual DbSet<C_APIBKAV> C_APIBKAV { get; set; }
        public virtual DbSet<C_apitokhai_fpt> C_apitokhai_fpt { get; set; }
        public virtual DbSet<C_APPSTR> C_APPSTR { get; set; }
        public virtual DbSet<C_AppStr2> C_AppStr2 { get; set; }
        public virtual DbSet<C_APPSTR3> C_APPSTR3 { get; set; }
        public virtual DbSet<C_BANGTG> C_BANGTG { get; set; }
        public virtual DbSet<C_banhang> C_banhang { get; set; }
        public virtual DbSet<C_banhangct> C_banhangct { get; set; }
        public virtual DbSet<C_baolanh> C_baolanh { get; set; }
        public virtual DbSet<C_bbnt> C_bbnt { get; set; }
        public virtual DbSet<C_BienThemCFG> C_BienThemCFG { get; set; }
        public virtual DbSet<C_BTTHEM> C_BTTHEM { get; set; }
        public virtual DbSet<C_BTTHEM0> C_BTTHEM0 { get; set; }
        public virtual DbSet<C_BTTHEMS> C_BTTHEMS { get; set; }
        public virtual DbSet<C_canhbaothue> C_canhbaothue { get; set; }
        public virtual DbSet<C_cauhinh> C_cauhinh { get; set; }
        public virtual DbSet<C_cauhinh_bkav> C_cauhinh_bkav { get; set; }
        public virtual DbSet<C_cauhinh_cyber> C_cauhinh_cyber { get; set; }
        public virtual DbSet<C_cauhinh_minvoice> C_cauhinh_minvoice { get; set; }
        public virtual DbSet<C_cauhinh_misa> C_cauhinh_misa { get; set; }
        public virtual DbSet<C_cauhinh_mobifone> C_cauhinh_mobifone { get; set; }
        public virtual DbSet<C_cauhinh_mobifone_78> C_cauhinh_mobifone_78 { get; set; }
        public virtual DbSet<C_cauhinh_SoftDream> C_cauhinh_SoftDream { get; set; }
        public virtual DbSet<C_cauhinh_vtbank> C_cauhinh_vtbank { get; set; }
        public virtual DbSet<C_cauhinhtokhai_fpt> C_cauhinhtokhai_fpt { get; set; }
        public virtual DbSet<C_cauhinhvt> C_cauhinhvt { get; set; }
        public virtual DbSet<C_convert_bang> C_convert_bang { get; set; }
        public virtual DbSet<C_convert_thue> C_convert_thue { get; set; }
        public virtual DbSet<C_congvan> C_congvan { get; set; }
        public virtual DbSet<C_CoquanBHXH> C_CoquanBHXH { get; set; }
        public virtual DbSet<C_coquanthue> C_coquanthue { get; set; }
        public virtual DbSet<C_cvdoitien> C_cvdoitien { get; set; }
        public virtual DbSet<C_ChamCong_Luong> C_ChamCong_Luong { get; set; }
        public virtual DbSet<C_CHAMNGON> C_CHAMNGON { get; set; }
        public virtual DbSet<C_CHART_TABLE> C_CHART_TABLE { get; set; }
        public virtual DbSet<C_chatroommessage> C_chatroommessage { get; set; }
        public virtual DbSet<C_dantoc> C_dantoc { get; set; }
        public virtual DbSet<C_DANHMUC> C_DANHMUC { get; set; }
        public virtual DbSet<C_DELELOG> C_DELELOG { get; set; }
        public virtual DbSet<C_DinhMuc01> C_DinhMuc01 { get; set; }
        public virtual DbSet<C_DinhMuc01201501> C_DinhMuc01201501 { get; set; }
        public virtual DbSet<C_DinhMuc01201502> C_DinhMuc01201502 { get; set; }
        public virtual DbSet<C_DinhMuc01201503> C_DinhMuc01201503 { get; set; }
        public virtual DbSet<C_DinhMuc01201504> C_DinhMuc01201504 { get; set; }
        public virtual DbSet<C_DinhMuc01201505> C_DinhMuc01201505 { get; set; }
        public virtual DbSet<C_DinhMuc01201506> C_DinhMuc01201506 { get; set; }
        public virtual DbSet<C_DinhMuc01201507> C_DinhMuc01201507 { get; set; }
        public virtual DbSet<C_DinhMuc01201508> C_DinhMuc01201508 { get; set; }
        public virtual DbSet<C_DinhMuc01201510> C_DinhMuc01201510 { get; set; }
        public virtual DbSet<C_dl_ccong> C_dl_ccong { get; set; }
        public virtual DbSet<C_dmpb> C_dmpb { get; set; }
        public virtual DbSet<C_donviyte> C_donviyte { get; set; }
        public virtual DbSet<C_DUTIENTE> C_DUTIENTE { get; set; }
        public virtual DbSet<C_DVCS> C_DVCS { get; set; }
        public virtual DbSet<C_FormfitBtnProc> C_FormfitBtnProc { get; set; }
        public virtual DbSet<C_formobj> C_formobj { get; set; }
        public virtual DbSet<C_gioitinh> C_gioitinh { get; set; }
        public virtual DbSet<C_HDDT_STRUCT_XML_FUNC_SERVICE_1thue_v3> C_HDDT_STRUCT_XML_FUNC_SERVICE_1thue_v3 { get; set; }
        public virtual DbSet<C_HDDT_STRUCT_XML_FUNC_SERVICE_1thue_v5> C_HDDT_STRUCT_XML_FUNC_SERVICE_1thue_v5 { get; set; }
        public virtual DbSet<C_HDDT_STRUCT_XML_FUNC_SERVICE_nthue> C_HDDT_STRUCT_XML_FUNC_SERVICE_nthue { get; set; }
        public virtual DbSet<C_HDDT_STRUCT_XML_FUNC_SERVICE_nthue_v3> C_HDDT_STRUCT_XML_FUNC_SERVICE_nthue_v3 { get; set; }
        public virtual DbSet<C_HDDT_STRUCT_XML_FUNC_SERVICE_nthue_v5> C_HDDT_STRUCT_XML_FUNC_SERVICE_nthue_v5 { get; set; }
        public virtual DbSet<C_hocvi> C_hocvi { get; set; }
        public virtual DbSet<C_hrm_bangcap> C_hrm_bangcap { get; set; }
        public virtual DbSet<C_hrm_bienthem> C_hrm_bienthem { get; set; }
        public virtual DbSet<C_hrm_chamcong> C_hrm_chamcong { get; set; }
        public virtual DbSet<C_hrm_chamcongtong> C_hrm_chamcongtong { get; set; }
        public virtual DbSet<C_hrm_danhgia> C_hrm_danhgia { get; set; }
        public virtual DbSet<C_hrm_danhhieu> C_hrm_danhhieu { get; set; }
        public virtual DbSet<C_hrm_dlluong> C_hrm_dlluong { get; set; }
        public virtual DbSet<C_hrm_dlluongtong> C_hrm_dlluongtong { get; set; }
        public virtual DbSet<C_hrm_functions> C_hrm_functions { get; set; }
        public virtual DbSet<C_hrm_hinhthuc> C_hrm_hinhthuc { get; set; }
        public virtual DbSet<C_hrm_hinhthucluong> C_hrm_hinhthucluong { get; set; }
        public virtual DbSet<C_hrm_hopdong> C_hrm_hopdong { get; set; }
        public virtual DbSet<C_hrm_kyhieucc> C_hrm_kyhieucc { get; set; }
        public virtual DbSet<C_hrm_loaipt> C_hrm_loaipt { get; set; }
        public virtual DbSet<C_hrm_loaitcap> C_hrm_loaitcap { get; set; }
        public virtual DbSet<C_hrm_luongnhom1> C_hrm_luongnhom1 { get; set; }
        public virtual DbSet<C_hrm_luongnhom2> C_hrm_luongnhom2 { get; set; }
        public virtual DbSet<C_hrm_nhanvien> C_hrm_nhanvien { get; set; }
        public virtual DbSet<C_hrm_nhomluong> C_hrm_nhomluong { get; set; }
        public virtual DbSet<C_hrm_qtthue> C_hrm_qtthue { get; set; }
        public virtual DbSet<C_hrm_qtthuect> C_hrm_qtthuect { get; set; }
        public virtual DbSet<C_hrm_quyetdinhtong> C_hrm_quyetdinhtong { get; set; }
        public virtual DbSet<C_hrm_xulythem> C_hrm_xulythem { get; set; }
        public virtual DbSet<C_HTTT> C_HTTT { get; set; }
        public virtual DbSet<C_import_table_temp> C_import_table_temp { get; set; }
        public virtual DbSet<C_KC_CTTheoNhom> C_KC_CTTheoNhom { get; set; }
        public virtual DbSet<C_KCTheo> C_KCTheo { get; set; }
        public virtual DbSet<C_KichBan> C_KichBan { get; set; }
        public virtual DbSet<C_KichBanCT> C_KichBanCT { get; set; }
        public virtual DbSet<C_KT> C_KT { get; set; }
        public virtual DbSet<C_KHO> C_KHO { get; set; }
        public virtual DbSet<C_ListKS> C_ListKS { get; set; }
        public virtual DbSet<C_loaihd> C_loaihd { get; set; }
        public virtual DbSet<C_loaitn> C_loaitn { get; set; }
        public virtual DbSet<C_LuongCfg> C_LuongCfg { get; set; }
        public virtual DbSet<C_luufile> C_luufile { get; set; }
        public virtual DbSet<C_MtlSoDuKC> C_MtlSoDuKC { get; set; }
        public virtual DbSet<C_nganhdt> C_nganhdt { get; set; }
        public virtual DbSet<C_nganhnghe> C_nganhnghe { get; set; }
        public virtual DbSet<C_ngayle> C_ngayle { get; set; }
        public virtual DbSet<C_ngaynghi> C_ngaynghi { get; set; }
        public virtual DbSet<C_NhapKhoTP01> C_NhapKhoTP01 { get; set; }
        public virtual DbSet<C_Nhom_KC> C_Nhom_KC { get; set; }
        public virtual DbSet<C_NhomLuong> C_NhomLuong { get; set; }
        public virtual DbSet<C_phanloaihd> C_phanloaihd { get; set; }
        public virtual DbSet<C_phuong> C_phuong { get; set; }
        public virtual DbSet<C_quan> C_quan { get; set; }
        public virtual DbSet<C_quoc_gia> C_quoc_gia { get; set; }
        public virtual DbSet<C_quytacplhd> C_quytacplhd { get; set; }
        public virtual DbSet<C_Rowfilter_read_ct> C_Rowfilter_read_ct { get; set; }
        public virtual DbSet<C_screen_chitiet> C_screen_chitiet { get; set; }
        public virtual DbSet<C_screen_danhmuc> C_screen_danhmuc { get; set; }
        public virtual DbSet<C_screen_erp> C_screen_erp { get; set; }
        public virtual DbSet<C_screen_erp2> C_screen_erp2 { get; set; }
        public virtual DbSet<C_screen_erp2_default> C_screen_erp2_default { get; set; }
        public virtual DbSet<C_screen_ktra> C_screen_ktra { get; set; }
        public virtual DbSet<C_SoDuKC> C_SoDuKC { get; set; }
        public virtual DbSet<C_SoDuKC01> C_SoDuKC01 { get; set; }
        public virtual DbSet<C_SQL> C_SQL { get; set; }
        public virtual DbSet<C_sua_tt> C_sua_tt { get; set; }
        public virtual DbSet<C_SuaCauTruc> C_SuaCauTruc { get; set; }
        public virtual DbSet<C_tblKCDuK01> C_tblKCDuK01 { get; set; }
        public virtual DbSet<C_tblKCDuK1> C_tblKCDuK1 { get; set; }
        public virtual DbSet<C_tblSoDuTKCT01> C_tblSoDuTKCT01 { get; set; }
        public virtual DbSet<C_tblSoDuTKCT1> C_tblSoDuTKCT1 { get; set; }
        public virtual DbSet<C_tblTonDNPS> C_tblTonDNPS { get; set; }
        public virtual DbSet<C_TD_BQGQ> C_TD_BQGQ { get; set; }
        public virtual DbSet<C_temp> C_temp { get; set; }
        public virtual DbSet<C_temp_bthem> C_temp_bthem { get; set; }
        public virtual DbSet<C_temp_convert_to_fieldshow_screen_table> C_temp_convert_to_fieldshow_screen_table { get; set; }
        public virtual DbSet<C_test_mbf> C_test_mbf { get; set; }
        public virtual DbSet<C_Testing> C_Testing { get; set; }
        public virtual DbSet<C_tiendo_hd> C_tiendo_hd { get; set; }
        public virtual DbSet<C_TieuThucPB> C_TieuThucPB { get; set; }
        public virtual DbSet<C_tinh> C_tinh { get; set; }
        public virtual DbSet<C_TKKC> C_TKKC { get; set; }
        public virtual DbSet<C_TKhoDau_BQGQ> C_TKhoDau_BQGQ { get; set; }
        public virtual DbSet<C_TKhoDau_PS_BQGQ> C_TKhoDau_PS_BQGQ { get; set; }
        public virtual DbSet<C_TKhoDau_PS_TC> C_TKhoDau_PS_TC { get; set; }
        public virtual DbSet<C_TKhoDau_TC> C_TKhoDau_TC { get; set; }
        public virtual DbSet<C_Tongiao> C_Tongiao { get; set; }
        public virtual DbSet<C_TT> C_TT { get; set; }
        public virtual DbSet<C_TTHonNhan> C_TTHonNhan { get; set; }
        public virtual DbSet<C_ThueTNCN> C_ThueTNCN { get; set; }
        public virtual DbSet<C_trangthaicuoithang> C_trangthaicuoithang { get; set; }
        public virtual DbSet<C_TREE> C_TREE { get; set; }
        public virtual DbSet<C_treeview> C_treeview { get; set; }
        public virtual DbSet<C_TrinhDoCM> C_TrinhDoCM { get; set; }
        public virtual DbSet<C_truong> C_truong { get; set; }
        public virtual DbSet<C_vviecpluc> C_vviecpluc { get; set; }
        public virtual DbSet<C_WS> C_WS { get; set; }
        public virtual DbSet<C_Xe> C_Xe { get; set; }
        public virtual DbSet<C_xmlhoadon> C_xmlhoadon { get; set; }
        public virtual DbSet<C_YEUCAU> C_YEUCAU { get; set; }
        public virtual DbSet<APEXSQL_LOG_LOGIN> APEXSQL_LOG_LOGIN { get; set; }
        public virtual DbSet<BTF> BTF { get; set; }
        public virtual DbSet<DataTable1> DataTable1 { get; set; }
        public virtual DbSet<DMktTon01> DMktTon01 { get; set; }
        public virtual DbSet<ERP_CT_Vat_Tu> ERP_CT_Vat_Tu { get; set; }
        public virtual DbSet<ERP_Don_Dat_Hang> ERP_Don_Dat_Hang { get; set; }
        public virtual DbSet<ERP_HUMAN_BANG_CC> ERP_HUMAN_BANG_CC { get; set; }
        public virtual DbSet<ERP_HUMAN_chamcong> ERP_HUMAN_chamcong { get; set; }
        public virtual DbSet<ERP_HUMAN_GIA_DINH> ERP_HUMAN_GIA_DINH { get; set; }
        public virtual DbSet<ERP_HUMAN_Loai_HDong> ERP_HUMAN_Loai_HDong { get; set; }
        public virtual DbSet<ERP_HUMAN_QD_Ca> ERP_HUMAN_QD_Ca { get; set; }
        public virtual DbSet<ERP_HUMAN_QLY_NS> ERP_HUMAN_QLY_NS { get; set; }
        public virtual DbSet<ERP_HUMAN_TongHopDLCC> ERP_HUMAN_TongHopDLCC { get; set; }
        public virtual DbSet<ERP_KHANG_BAOGIA> ERP_KHANG_BAOGIA { get; set; }
        public virtual DbSet<ERP_KHANG_GIAODICH> ERP_KHANG_GIAODICH { get; set; }
        public virtual DbSet<ERP_KHANG_HOPDONG> ERP_KHANG_HOPDONG { get; set; }
        public virtual DbSet<ERP_ORDER_CHAM_CONG> ERP_ORDER_CHAM_CONG { get; set; }
        public virtual DbSet<ERP_ORDER_DU_LIEU> ERP_ORDER_DU_LIEU { get; set; }
        public virtual DbSet<ERP_ORDER_KEHOACH> ERP_ORDER_KEHOACH { get; set; }
        public virtual DbSet<ERP_ORDER_KEHOACH1> ERP_ORDER_KEHOACH1 { get; set; }
        public virtual DbSet<ERP_ORDER_MAYCHAMC> ERP_ORDER_MAYCHAMC { get; set; }
        public virtual DbSet<ERP_ORDER_THUNG_VD> ERP_ORDER_THUNG_VD { get; set; }
        public virtual DbSet<ERP_PRIVATE_PROC> ERP_PRIVATE_PROC { get; set; }
        public virtual DbSet<ERP_TASK_MAIL> ERP_TASK_MAIL { get; set; }
        public virtual DbSet<ERP_TASK_PS_MAIL> ERP_TASK_PS_MAIL { get; set; }
        public virtual DbSet<ERP_TIMKIEM> ERP_TIMKIEM { get; set; }
        public virtual DbSet<ERP_TIMKIEM_DK> ERP_TIMKIEM_DK { get; set; }
        public virtual DbSet<FileToDownload> FileToDownload { get; set; }
        public virtual DbSet<FormPermission> FormPermission { get; set; }
        public virtual DbSet<HinhCay> HinhCay { get; set; }
        public virtual DbSet<HTKK_dulieu> HTKK_dulieu { get; set; }
        public virtual DbSet<InterfaceRegulation> InterfaceRegulation { get; set; }
        public virtual DbSet<KTCDKT_CDPS> KTCDKT_CDPS { get; set; }
        public virtual DbSet<KTCDKT_CongThuc> KTCDKT_CongThuc { get; set; }
        public virtual DbSet<KTCDKT_TKLuongTinh> KTCDKT_TKLuongTinh { get; set; }
        public virtual DbSet<MenuFormfit> MenuFormfit { get; set; }
        public virtual DbSet<MessageBoxLanguage> MessageBoxLanguage { get; set; }
        public virtual DbSet<ModiForm_LastTime> ModiForm_LastTime { get; set; }
        public virtual DbSet<modifydate_table> modifydate_table { get; set; }
        public virtual DbSet<ModiTable_LastTime> ModiTable_LastTime { get; set; }
        public virtual DbSet<ModiTitbrow_LastTime> ModiTitbrow_LastTime { get; set; }
        public virtual DbSet<MultiLanguage> MultiLanguage { get; set; }
        public virtual DbSet<pt_Screen> pt_Screen { get; set; }
        public virtual DbSet<pt_Screen2> pt_Screen2 { get; set; }
        public virtual DbSet<R781_004_1_20200219082303> R781_004_1_20200219082303 { get; set; }
        public virtual DbSet<R781_004_1_20200219082402> R781_004_1_20200219082402 { get; set; }
        public virtual DbSet<R781_004_1_20200219082527> R781_004_1_20200219082527 { get; set; }
        public virtual DbSet<R781_004_1_20200219082618> R781_004_1_20200219082618 { get; set; }
        public virtual DbSet<R781_004_1_20200219082825> R781_004_1_20200219082825 { get; set; }
        public virtual DbSet<R781_004_1_20200219083616> R781_004_1_20200219083616 { get; set; }
        public virtual DbSet<R781_004_1_20200219083638> R781_004_1_20200219083638 { get; set; }
        public virtual DbSet<R781_004_1_20200219083747> R781_004_1_20200219083747 { get; set; }
        public virtual DbSet<R781_004_1_20200219083822> R781_004_1_20200219083822 { get; set; }
        public virtual DbSet<R781_004_1_20200219083837> R781_004_1_20200219083837 { get; set; }
        public virtual DbSet<R781_004_1_20200219083936> R781_004_1_20200219083936 { get; set; }
        public virtual DbSet<R781_004_1_20200219084012> R781_004_1_20200219084012 { get; set; }
        public virtual DbSet<R781_004_1_20200219084029> R781_004_1_20200219084029 { get; set; }
        public virtual DbSet<R781_004_1_20200219084139> R781_004_1_20200219084139 { get; set; }
        public virtual DbSet<R781_004_1_20200219084147> R781_004_1_20200219084147 { get; set; }
        public virtual DbSet<R781_004_1_20200219085038> R781_004_1_20200219085038 { get; set; }
        public virtual DbSet<R781_004_1_20200219085103> R781_004_1_20200219085103 { get; set; }
        public virtual DbSet<R781_004_1_20200219085219> R781_004_1_20200219085219 { get; set; }
        public virtual DbSet<R781_004_1_20200219085230> R781_004_1_20200219085230 { get; set; }
        public virtual DbSet<R811_001_1_20231222144031> R811_001_1_20231222144031 { get; set; }
        public virtual DbSet<R811_001_1_20231222144201> R811_001_1_20231222144201 { get; set; }
        public virtual DbSet<R811_001_1_20231222144238> R811_001_1_20231222144238 { get; set; }
        public virtual DbSet<R815_001_1_20231222104542> R815_001_1_20231222104542 { get; set; }
        public virtual DbSet<R819_001_1_20231222145657> R819_001_1_20231222145657 { get; set; }
        public virtual DbSet<R819_001_1_20231222145700> R819_001_1_20231222145700 { get; set; }
        public virtual DbSet<R819_006_1_20231220134932> R819_006_1_20231220134932 { get; set; }
        public virtual DbSet<R819_006_1_20231220135752> R819_006_1_20231220135752 { get; set; }
        public virtual DbSet<R821_002_1_20230922163443> R821_002_1_20230922163443 { get; set; }
        public virtual DbSet<R821_002_1_20230922163444> R821_002_1_20230922163444 { get; set; }
        public virtual DbSet<R821_002_1_20230922163545> R821_002_1_20230922163545 { get; set; }
        public virtual DbSet<R821_002_1_20230922163546> R821_002_1_20230922163546 { get; set; }
        public virtual DbSet<R821_002_1_20230922163644> R821_002_1_20230922163644 { get; set; }
        public virtual DbSet<R821_002_1_20230922163645> R821_002_1_20230922163645 { get; set; }
        public virtual DbSet<R821_002_1_20230922163717> R821_002_1_20230922163717 { get; set; }
        public virtual DbSet<R821_002_1_20230922163718> R821_002_1_20230922163718 { get; set; }
        public virtual DbSet<R821_002_1_20230922163823> R821_002_1_20230922163823 { get; set; }
        public virtual DbSet<R821_002_1_20230922163843> R821_002_1_20230922163843 { get; set; }
        public virtual DbSet<R821_002_1_20230922163844> R821_002_1_20230922163844 { get; set; }
        public virtual DbSet<R821_002_1_20230922163914> R821_002_1_20230922163914 { get; set; }
        public virtual DbSet<R821_002_1_20230922163915> R821_002_1_20230922163915 { get; set; }
        public virtual DbSet<R821_002_1_20230922164006> R821_002_1_20230922164006 { get; set; }
        public virtual DbSet<R821_002_1_20230922164007> R821_002_1_20230922164007 { get; set; }
        public virtual DbSet<R821_002_1_20230922164113> R821_002_1_20230922164113 { get; set; }
        public virtual DbSet<R821_002_1_20230922164232> R821_002_1_20230922164232 { get; set; }
        public virtual DbSet<R821_002_1_20230922164233> R821_002_1_20230922164233 { get; set; }
        public virtual DbSet<R821_002_1_20230922164332> R821_002_1_20230922164332 { get; set; }
        public virtual DbSet<R821_002_1_20230922164333> R821_002_1_20230922164333 { get; set; }
        public virtual DbSet<R821_002_1_20230922164452> R821_002_1_20230922164452 { get; set; }
        public virtual DbSet<R821_002_1_20230922164453> R821_002_1_20230922164453 { get; set; }
        public virtual DbSet<R821_002_1_20230922164515> R821_002_1_20230922164515 { get; set; }
        public virtual DbSet<R821_002_1_20230922164516> R821_002_1_20230922164516 { get; set; }
        public virtual DbSet<R821_002_1_20230922164712> R821_002_1_20230922164712 { get; set; }
        public virtual DbSet<R821_002_1_20230922164713> R821_002_1_20230922164713 { get; set; }
        public virtual DbSet<R821_006_1_20231221084154> R821_006_1_20231221084154 { get; set; }
        public virtual DbSet<R821_006_1_20231221084155> R821_006_1_20231221084155 { get; set; }
        public virtual DbSet<R821_006_1_20231221084339> R821_006_1_20231221084339 { get; set; }
        public virtual DbSet<R821_006_1_20231221085109> R821_006_1_20231221085109 { get; set; }
        public virtual DbSet<R824_001_1_20230916101947> R824_001_1_20230916101947 { get; set; }
        public virtual DbSet<R824_001_1_20230916102009> R824_001_1_20230916102009 { get; set; }
        public virtual DbSet<R824_001_1_20240306193150> R824_001_1_20240306193150 { get; set; }
        public virtual DbSet<R824_002_1_20230914171541> R824_002_1_20230914171541 { get; set; }
        public virtual DbSet<R824_002_1_20230914171657> R824_002_1_20230914171657 { get; set; }
        public virtual DbSet<R824_002_1_20230914171748> R824_002_1_20230914171748 { get; set; }
        public virtual DbSet<R824_002_1_20230915085147> R824_002_1_20230915085147 { get; set; }
        public virtual DbSet<R824_002_1_20230915085534> R824_002_1_20230915085534 { get; set; }
        public virtual DbSet<R824_006_1_20231214094225> R824_006_1_20231214094225 { get; set; }
        public virtual DbSet<R824_006_1_20231214094320> R824_006_1_20231214094320 { get; set; }
        public virtual DbSet<R824_006_1_20231219101946> R824_006_1_20231219101946 { get; set; }
        public virtual DbSet<R824_006_1_20231221085726> R824_006_1_20231221085726 { get; set; }
        public virtual DbSet<R824_006_1_20231221085801> R824_006_1_20231221085801 { get; set; }
        public virtual DbSet<R824_006_1_20231221085921> R824_006_1_20231221085921 { get; set; }
        public virtual DbSet<R824_006_1_20231221090300> R824_006_1_20231221090300 { get; set; }
        public virtual DbSet<R824_006_1_20231221090545> R824_006_1_20231221090545 { get; set; }
        public virtual DbSet<R824_008_1_20230915085016> R824_008_1_20230915085016 { get; set; }
        public virtual DbSet<R824_008_1_20230915085055> R824_008_1_20230915085055 { get; set; }
        public virtual DbSet<R824_008_1_20230915085621> R824_008_1_20230915085621 { get; set; }
        public virtual DbSet<R824_008_1_20230915112145> R824_008_1_20230915112145 { get; set; }
        public virtual DbSet<R824_008_1_20230915112217> R824_008_1_20230915112217 { get; set; }
        public virtual DbSet<R825_001_1_20240306193151> R825_001_1_20240306193151 { get; set; }
        public virtual DbSet<R825_002_1_20230915085149> R825_002_1_20230915085149 { get; set; }
        public virtual DbSet<R825_002_1_20230915085536> R825_002_1_20230915085536 { get; set; }
        public virtual DbSet<R827_016_1_20240118111430> R827_016_1_20240118111430 { get; set; }
        public virtual DbSet<R829_001_1_20230916101922> R829_001_1_20230916101922 { get; set; }
        public virtual DbSet<R829_002_1_20230915083011> R829_002_1_20230915083011 { get; set; }
        public virtual DbSet<R829_006_1_20231212095109> R829_006_1_20231212095109 { get; set; }
        public virtual DbSet<R829_006_1_20231213145514> R829_006_1_20231213145514 { get; set; }
        public virtual DbSet<R829_006_1_20231219111902> R829_006_1_20231219111902 { get; set; }
        public virtual DbSet<R829_006_1_20231221085542> R829_006_1_20231221085542 { get; set; }
        public virtual DbSet<R829_008_1_20230915085203> R829_008_1_20230915085203 { get; set; }
        public virtual DbSet<Screen_CuoiThang> Screen_CuoiThang { get; set; }
        public virtual DbSet<table_resul_when_insert_data_to_sql> table_resul_when_insert_data_to_sql { get; set; }
        public virtual DbSet<TablePermission> TablePermission { get; set; }
        public virtual DbSet<TableRelation> TableRelation { get; set; }
        public virtual DbSet<tbl_Joins> tbl_Joins { get; set; }
        public virtual DbSet<tbl_NgayNghi> tbl_NgayNghi { get; set; }
        public virtual DbSet<tblab> tblab { get; set; }
        public virtual DbSet<tblChucNang> tblChucNang { get; set; }
        public virtual DbSet<tblERP> tblERP { get; set; }
        public virtual DbSet<tblfile> tblfile { get; set; }
        public virtual DbSet<tblKSCfg> tblKSCfg { get; set; }
        public virtual DbSet<tblVersionSPF> tblVersionSPF { get; set; }
        public virtual DbSet<teee> teee { get; set; }
        public virtual DbSet<tem_tygiatt200_1> tem_tygiatt200_1 { get; set; }
        public virtual DbSet<temp> temp { get; set; }
        public virtual DbSet<temp_formobj> temp_formobj { get; set; }
        public virtual DbSet<TKKSTEM> TKKSTEM { get; set; }
        public virtual DbSet<tmpDGVon> tmpDGVon { get; set; }
        public virtual DbSet<tmpGVChenhLech1> tmpGVChenhLech1 { get; set; }
        public virtual DbSet<UFunct> UFunct { get; set; }
    
        [DbFunction("EFF_EFFE_200Entities", "f_tscd_thanhly")]
        public virtual IQueryable<f_tscd_thanhly_Result> f_tscd_thanhly(Nullable<System.DateTime> ngay_thc, Nullable<int> dvcs, Nullable<decimal> tscd)
        {
            var ngay_thcParameter = ngay_thc.HasValue ?
                new ObjectParameter("ngay_thc", ngay_thc) :
                new ObjectParameter("ngay_thc", typeof(System.DateTime));
    
            var dvcsParameter = dvcs.HasValue ?
                new ObjectParameter("dvcs", dvcs) :
                new ObjectParameter("dvcs", typeof(int));
    
            var tscdParameter = tscd.HasValue ?
                new ObjectParameter("tscd", tscd) :
                new ObjectParameter("tscd", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_tscd_thanhly_Result>("[EFF_EFFE_200Entities].[f_tscd_thanhly](@ngay_thc, @dvcs, @tscd)", ngay_thcParameter, dvcsParameter, tscdParameter);
        }
    
        [DbFunction("EFF_EFFE_200Entities", "anhien_bt_them")]
        public virtual IQueryable<anhien_bt_them_Result> anhien_bt_them(string form, string ma_scr, string btthems)
        {
            var formParameter = form != null ?
                new ObjectParameter("form", form) :
                new ObjectParameter("form", typeof(string));
    
            var ma_scrParameter = ma_scr != null ?
                new ObjectParameter("ma_scr", ma_scr) :
                new ObjectParameter("ma_scr", typeof(string));
    
            var btthemsParameter = btthems != null ?
                new ObjectParameter("btthems", btthems) :
                new ObjectParameter("btthems", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<anhien_bt_them_Result>("[EFF_EFFE_200Entities].[anhien_bt_them](@form, @ma_scr, @btthems)", formParameter, ma_scrParameter, btthemsParameter);
        }
    
        [DbFunction("EFF_EFFE_200Entities", "FIELD_PHNX")]
        public virtual IQueryable<FIELD_PHNX_Result> FIELD_PHNX(Nullable<decimal> ma_scr)
        {
            var ma_scrParameter = ma_scr.HasValue ?
                new ObjectParameter("ma_scr", ma_scr) :
                new ObjectParameter("ma_scr", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FIELD_PHNX_Result>("[EFF_EFFE_200Entities].[FIELD_PHNX](@ma_scr)", ma_scrParameter);
        }
    
        [DbFunction("EFF_EFFE_200Entities", "GetObjectHideUnHide")]
        public virtual IQueryable<GetObjectHideUnHide_Result> GetObjectHideUnHide(Nullable<int> ma_scr, string form)
        {
            var ma_scrParameter = ma_scr.HasValue ?
                new ObjectParameter("ma_scr", ma_scr) :
                new ObjectParameter("ma_scr", typeof(int));
    
            var formParameter = form != null ?
                new ObjectParameter("form", form) :
                new ObjectParameter("form", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetObjectHideUnHide_Result>("[EFF_EFFE_200Entities].[GetObjectHideUnHide](@ma_scr, @form)", ma_scrParameter, formParameter);
        }
    
        [DbFunction("EFF_EFFE_200Entities", "GetObjectOrderOnForm")]
        public virtual IQueryable<GetObjectOrderOnForm_Result> GetObjectOrderOnForm(Nullable<int> ma_scr, string form)
        {
            var ma_scrParameter = ma_scr.HasValue ?
                new ObjectParameter("ma_scr", ma_scr) :
                new ObjectParameter("ma_scr", typeof(int));
    
            var formParameter = form != null ?
                new ObjectParameter("form", form) :
                new ObjectParameter("form", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetObjectOrderOnForm_Result>("[EFF_EFFE_200Entities].[GetObjectOrderOnForm](@ma_scr, @form)", ma_scrParameter, formParameter);
        }
    
        [DbFunction("EFF_EFFE_200Entities", "GetTable_Screenobj")]
        public virtual IQueryable<GetTable_Screenobj_Result> GetTable_Screenobj(Nullable<int> ma_scr)
        {
            var ma_scrParameter = ma_scr.HasValue ?
                new ObjectParameter("ma_scr", ma_scr) :
                new ObjectParameter("ma_scr", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetTable_Screenobj_Result>("[EFF_EFFE_200Entities].[GetTable_Screenobj](@ma_scr)", ma_scrParameter);
        }
    
        [DbFunction("EFF_EFFE_200Entities", "gia_tri_kh_thang")]
        public virtual IQueryable<gia_tri_kh_thang_Result> gia_tri_kh_thang(Nullable<System.DateTime> ngay_thc1, Nullable<int> dvcs)
        {
            var ngay_thc1Parameter = ngay_thc1.HasValue ?
                new ObjectParameter("ngay_thc1", ngay_thc1) :
                new ObjectParameter("ngay_thc1", typeof(System.DateTime));
    
            var dvcsParameter = dvcs.HasValue ?
                new ObjectParameter("dvcs", dvcs) :
                new ObjectParameter("dvcs", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<gia_tri_kh_thang_Result>("[EFF_EFFE_200Entities].[gia_tri_kh_thang](@ngay_thc1, @dvcs)", ngay_thc1Parameter, dvcsParameter);
        }
    
        [DbFunction("EFF_EFFE_200Entities", "gia_tri_pb_thang")]
        public virtual IQueryable<gia_tri_pb_thang_Result> gia_tri_pb_thang(Nullable<System.DateTime> ngay_thc1, Nullable<int> dvcs)
        {
            var ngay_thc1Parameter = ngay_thc1.HasValue ?
                new ObjectParameter("ngay_thc1", ngay_thc1) :
                new ObjectParameter("ngay_thc1", typeof(System.DateTime));
    
            var dvcsParameter = dvcs.HasValue ?
                new ObjectParameter("dvcs", dvcs) :
                new ObjectParameter("dvcs", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<gia_tri_pb_thang_Result>("[EFF_EFFE_200Entities].[gia_tri_pb_thang](@ngay_thc1, @dvcs)", ngay_thc1Parameter, dvcsParameter);
        }
    
        [DbFunction("EFF_EFFE_200Entities", "indexunique")]
        public virtual IQueryable<indexunique_Result> indexunique(string tablename)
        {
            var tablenameParameter = tablename != null ?
                new ObjectParameter("tablename", tablename) :
                new ObjectParameter("tablename", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<indexunique_Result>("[EFF_EFFE_200Entities].[indexunique](@tablename)", tablenameParameter);
        }
    
        [DbFunction("EFF_EFFE_200Entities", "KtraSoLuongTon2")]
        public virtual IQueryable<KtraSoLuongTon2_Result> KtraSoLuongTon2(Nullable<decimal> ma_thb, Nullable<decimal> so_luong, Nullable<System.DateTime> ngay_thc, Nullable<decimal> kho, string ma_tk1, Nullable<int> dvcs)
        {
            var ma_thbParameter = ma_thb.HasValue ?
                new ObjectParameter("ma_thb", ma_thb) :
                new ObjectParameter("ma_thb", typeof(decimal));
    
            var so_luongParameter = so_luong.HasValue ?
                new ObjectParameter("so_luong", so_luong) :
                new ObjectParameter("so_luong", typeof(decimal));
    
            var ngay_thcParameter = ngay_thc.HasValue ?
                new ObjectParameter("ngay_thc", ngay_thc) :
                new ObjectParameter("ngay_thc", typeof(System.DateTime));
    
            var khoParameter = kho.HasValue ?
                new ObjectParameter("kho", kho) :
                new ObjectParameter("kho", typeof(decimal));
    
            var ma_tk1Parameter = ma_tk1 != null ?
                new ObjectParameter("ma_tk1", ma_tk1) :
                new ObjectParameter("ma_tk1", typeof(string));
    
            var dvcsParameter = dvcs.HasValue ?
                new ObjectParameter("dvcs", dvcs) :
                new ObjectParameter("dvcs", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<KtraSoLuongTon2_Result>("[EFF_EFFE_200Entities].[KtraSoLuongTon2](@ma_thb, @so_luong, @ngay_thc, @kho, @ma_tk1, @dvcs)", ma_thbParameter, so_luongParameter, ngay_thcParameter, khoParameter, ma_tk1Parameter, dvcsParameter);
        }
    
        [DbFunction("EFF_EFFE_200Entities", "luachon")]
        public virtual IQueryable<luachon_Result> luachon(Nullable<decimal> ma_scr)
        {
            var ma_scrParameter = ma_scr.HasValue ?
                new ObjectParameter("ma_scr", ma_scr) :
                new ObjectParameter("ma_scr", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<luachon_Result>("[EFF_EFFE_200Entities].[luachon](@ma_scr)", ma_scrParameter);
        }
    
        [DbFunction("EFF_EFFE_200Entities", "split_Field_Ktra")]
        public virtual IQueryable<split_Field_Ktra_Result> split_Field_Ktra(string bien)
        {
            var bienParameter = bien != null ?
                new ObjectParameter("bien", bien) :
                new ObjectParameter("bien", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<split_Field_Ktra_Result>("[EFF_EFFE_200Entities].[split_Field_Ktra](@bien)", bienParameter);
        }
    
        [DbFunction("EFF_EFFE_200Entities", "SplitString")]
        public virtual IQueryable<SplitString_Result> SplitString(string myString, string deliminator)
        {
            var myStringParameter = myString != null ?
                new ObjectParameter("myString", myString) :
                new ObjectParameter("myString", typeof(string));
    
            var deliminatorParameter = deliminator != null ?
                new ObjectParameter("deliminator", deliminator) :
                new ObjectParameter("deliminator", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<SplitString_Result>("[EFF_EFFE_200Entities].[SplitString](@myString, @deliminator)", myStringParameter, deliminatorParameter);
        }
    
        [DbFunction("EFF_EFFE_200Entities", "TachSoChu")]
        public virtual IQueryable<TachSoChu_Result> TachSoChu(string str)
        {
            var strParameter = str != null ?
                new ObjectParameter("str", str) :
                new ObjectParameter("str", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<TachSoChu_Result>("[EFF_EFFE_200Entities].[TachSoChu](@str)", strParameter);
        }
    }
}
