//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class MultiLanguage
    {
        public string VietNam { get; set; }
        public string English { get; set; }
        public string China { get; set; }
        public string Japan { get; set; }
        public int f_identity { get; set; }
        public System.DateTime datetime { get; set; }
    }
}
