//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class pt_Screen
    {
        public Nullable<int> disable { get; set; }
        public Nullable<int> ma_scr { get; set; }
        public string ma { get; set; }
        public string ten_mascr { get; set; }
        public Nullable<int> Kieu { get; set; }
        public Nullable<decimal> sxluoi { get; set; }
        public string keypt { get; set; }
        public string trangthai { get; set; }
        public string ten { get; set; }
        public string fieldname { get; set; }
        public string from_alia { get; set; }
        public string from_field { get; set; }
        public string filt_field { get; set; }
        public Nullable<int> macdinh { get; set; }
        public Nullable<int> chuc_nang { get; set; }
        public Nullable<int> de_lai { get; set; }
        public decimal f_identity { get; set; }
        public decimal stt2 { get; set; }
    }
}
