//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class R781_004_1_20200219083837
    {
        public int tentb { get; set; }
        public decimal cot0 { get; set; }
        public decimal cot1 { get; set; }
        public decimal cot2 { get; set; }
        public decimal cot3 { get; set; }
        public decimal cot6 { get; set; }
        public decimal tongcong { get; set; }
    }
}
