//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class R811_001_1_20231222144238_1_1_0
    {
        public long recno { get; set; }
        public long stt { get; set; }
        public string tennhanvien { get; set; }
        public string mabhxh { get; set; }
        public string tkhoan { get; set; }
        public string mst { get; set; }
        public string ten { get; set; }
        public string loaipt { get; set; }
        public System.DateTime ngaysinh { get; set; }
        public string diachi { get; set; }
        public string masothue { get; set; }
        public System.DateTime tungay { get; set; }
        public System.DateTime denngay { get; set; }
        public string ghichu { get; set; }
        public int nhanvien { get; set; }
        public long fidentity { get; set; }
    }
}
