//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class R815_001_1_20231222104542
    {
        public long stt { get; set; }
        public string tennhanvien { get; set; }
        public string mabhxh { get; set; }
        public string TKHOAN_NH { get; set; }
        public string TenNganHang { get; set; }
        public string hinhthuc { get; set; }
        public string bophanten { get; set; }
        public string vitriten { get; set; }
        public decimal hsluong { get; set; }
        public decimal hsvkhung { get; set; }
        public decimal hschucvu { get; set; }
        public decimal hstnien { get; set; }
        public decimal hsknhiem { get; set; }
        public decimal hsdochai { get; set; }
        public decimal hstrnhiem { get; set; }
        public decimal pcvpp { get; set; }
        public decimal pcdienthoai { get; set; }
        public decimal pcphuongtien { get; set; }
        public decimal pckhac { get; set; }
        public int nhanvien { get; set; }
        public long fidentity { get; set; }
        public string bophanma { get; set; }
        public string manhanvien { get; set; }
    }
}
