//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class R819_001_1_20231222145700
    {
        public long stt { get; set; }
        public string bophanten { get; set; }
        public string tennhanvien { get; set; }
        public string vitri { get; set; }
        public int songuoi { get; set; }
        public decimal luongcb { get; set; }
        public decimal luongtthuan { get; set; }
        public decimal congthoigian { get; set; }
        public decimal congphep { get; set; }
        public decimal congtangca { get; set; }
        public decimal congtong { get; set; }
        public decimal tienluong { get; set; }
        public decimal pcchucvu { get; set; }
        public decimal pcvpp { get; set; }
        public decimal pcphuongtien { get; set; }
        public decimal pcdienthoai { get; set; }
        public decimal pckhac { get; set; }
        public decimal tcapdxcot { get; set; }
        public decimal tcapdxkot { get; set; }
        public decimal sosuatan { get; set; }
        public decimal pcantrua { get; set; }
        public decimal tongtien { get; set; }
        public decimal tientinhbh { get; set; }
        public decimal nbhxh { get; set; }
        public decimal nbhyt { get; set; }
        public decimal nbhtn { get; set; }
        public decimal nkpcd { get; set; }
        public decimal dbhxh { get; set; }
        public decimal dbhyt { get; set; }
        public decimal dbhtn { get; set; }
        public decimal dkpcd { get; set; }
        public decimal tnnopthue { get; set; }
        public decimal songuoipt { get; set; }
        public decimal giamgc { get; set; }
        public decimal tntinhthue { get; set; }
        public decimal thuetncn { get; set; }
        public decimal tamung { get; set; }
        public decimal truythu { get; set; }
        public decimal tongkhautru { get; set; }
        public decimal thuclinh { get; set; }
        public int cap { get; set; }
        public string bophanma { get; set; }
        public string manhanvien { get; set; }
        public int nhanvien { get; set; }
        public string hinhthucten { get; set; }
        public int nghits { get; set; }
        public int C_count { get; set; }
        public string loaihdten { get; set; }
        public int sx { get; set; }
        public int in_dam { get; set; }
        public string bophan_email { get; set; }
    }
}
