//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class R824_002_1_20230914171657
    {
        public decimal sttsx { get; set; }
        public string hovaten { get; set; }
        public string masothue { get; set; }
        public string cmnd { get; set; }
        public int uyquyen { get; set; }
        public string nuocngoai { get; set; }
        public decimal tongchiuthue { get; set; }
        public decimal tongchiuthue1 { get; set; }
        public decimal tongchiuthue2 { get; set; }
        public decimal tongchiuthue3 { get; set; }
        public decimal nguoipt { get; set; }
        public decimal giamtrugiacanh { get; set; }
        public decimal tuthien { get; set; }
        public decimal baohiem { get; set; }
        public decimal huutri { get; set; }
        public decimal thunhaptinhthue12 { get; set; }
        public decimal thuedanop { get; set; }
        public decimal thuedanop1 { get; set; }
        public decimal thuephainop { get; set; }
        public decimal thuenopthua { get; set; }
        public decimal thuechuanop { get; set; }
        public string nhohon50k { get; set; }
        public string bophanten { get; set; }
        public string sotk { get; set; }
        public int idnv { get; set; }
        public decimal gtpt { get; set; }
        public int gtbt { get; set; }
        public int songuoi { get; set; }
        public int songuoithue { get; set; }
        public int songuoigtgc { get; set; }
        public int thunhapthue { get; set; }
        public int nhanvien { get; set; }
        public short bng { get; set; }
        public decimal thunhaptinhthue { get; set; }
    }
}
