//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class R825_001_1_20240306193151_1_1_0
    {
        public long recno { get; set; }
        public Nullable<int> idnv { get; set; }
        public string manv { get; set; }
        public string tennv { get; set; }
        public string tennpt { get; set; }
        public System.DateTime tungay { get; set; }
        public System.DateTime denngay { get; set; }
        public Nullable<System.DateTime> ngay0 { get; set; }
        public Nullable<System.DateTime> ngay1 { get; set; }
        public int t1 { get; set; }
        public int t2 { get; set; }
        public int t3 { get; set; }
        public int t4 { get; set; }
        public int t5 { get; set; }
        public int t6 { get; set; }
        public int t7 { get; set; }
        public int t8 { get; set; }
        public int t9 { get; set; }
        public int t10 { get; set; }
        public int t11 { get; set; }
        public int t12 { get; set; }
        public Nullable<int> tong { get; set; }
        public Nullable<int> gtpt { get; set; }
        public Nullable<int> nhom { get; set; }
    }
}
