//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class R827_016_1_20240118111430
    {
        public long stt { get; set; }
        public string tennhanvien { get; set; }
        public string mabhxh { get; set; }
        public string ten { get; set; }
        public System.DateTime ngaysinh { get; set; }
        public string masothue { get; set; }
        public string loaigiayto { get; set; }
        public string sogiayto { get; set; }
        public string quanhe { get; set; }
        public string tungay { get; set; }
        public string denngay { get; set; }
        public int nhanvien { get; set; }
        public long fidentity { get; set; }
    }
}
