//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class R829_008_1_20230915085203
    {
        public string ten { get; set; }
        public string masothue { get; set; }
        public decimal tong1 { get; set; }
        public decimal tong2 { get; set; }
        public decimal thue { get; set; }
        public int songuoi1 { get; set; }
        public int songuoi2 { get; set; }
        public int nhanvien { get; set; }
    }
}
