//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablePermission
    {
        public string TableName { get; set; }
        public int ma_user { get; set; }
        public string ReadOnlyRow { get; set; }
        public string InVisibleRow { get; set; }
        public string NotDeletedRow { get; set; }
        public string ReadOnlyColumn { get; set; }
        public string InVisibleColumn { get; set; }
        public string ReadOnlyCell { get; set; }
        public bool AllowInsert { get; set; }
        public bool AllowEdit { get; set; }
        public bool AllowVisible { get; set; }
        public string VisibleRow { get; set; }
        public decimal f_identity { get; set; }
        public System.DateTime datetime { get; set; }
        public string ReadOnlyRow_old { get; set; }
        public string VisibleRow_old { get; set; }
    }
}
