//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableRelation
    {
        public string RelationName { get; set; }
        public string ParentTable { get; set; }
        public string ChildTable { get; set; }
        public string ParentColumn { get; set; }
        public string ChildColumn { get; set; }
        public string innerjoinstring { get; set; }
    }
}
