//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_resul_when_insert_data_to_sql
    {
        public string form { get; set; }
        public int ws { get; set; }
        public int ma_user { get; set; }
        public byte kq { get; set; }
    }
}
