//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Joins
    {
        public string cTable { get; set; }
        public string cJoinType { get; set; }
        public string cTableJoin { get; set; }
        public string cDK_Joins { get; set; }
        public int f_identity { get; set; }
    }
}
