//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_NgayNghi
    {
        public System.DateTime Ngay { get; set; }
        public System.DateTime Ngay_am { get; set; }
        public int Thu { get; set; }
        public string GhiChu { get; set; }
        public decimal f_identity { get; set; }
        public System.DateTime Datetime { get; set; }
    }
}
