//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Download
    {
        public int iMa_repo { get; set; }
        public string sMau { get; set; }
        public string cColumn_Def { get; set; }
        public string cColumn_Add { get; set; }
        public string cColumn_Group { get; set; }
        public string cColumn_Order { get; set; }
        public string cTable_Dn { get; set; }
        public int iOK { get; set; }
        public System.DateTime DateTime { get; set; }
        public int f_identity { get; set; }
        public string cTable_Add { get; set; }
    }
}
