//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LogIn
    {
        public string TenUser { get; set; }
        public string TenMay { get; set; }
        public string DiaChiIP { get; set; }
        public System.DateTime DateTime { get; set; }
        public decimal F_identity { get; set; }
    }
}
