//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblab
    {
        public System.DateTime NGAY_THC { get; set; }
        public int MA_SCR { get; set; }
        public int LOAICT { get; set; }
        public string CHUNG_TU { get; set; }
        public string SOHD { get; set; }
        public string SERIHD { get; set; }
        public int vp_DDien { get; set; }
        public int Hiep_Hoi { get; set; }
        public int bo_phanc { get; set; }
        public int nhan_vien { get; set; }
        public System.DateTime HanThanhToan { get; set; }
        public System.DateTime Ngay_CheckIn { get; set; }
        public System.DateTime Ngay_CheckOut { get; set; }
        public System.DateTime Ngay_RaHD { get; set; }
        public decimal PhanTram_TT { get; set; }
        public int Loai_doan { get; set; }
        public decimal f_identity { get; set; }
        public decimal Tien_CK_NT { get; set; }
        public decimal Tien_CK { get; set; }
        public decimal PT_CK { get; set; }
        public short TT_HD { get; set; }
        public int cs_hoaHong { get; set; }
        public decimal Tien_TT { get; set; }
    }
}
