//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChucNang
    {
        public int iMaCN { get; set; }
        public string sMa { get; set; }
        public string sTenCN { get; set; }
        public string sDienGiai { get; set; }
    }
}
