//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVersionSPF
    {
        public int iMaSPF { get; set; }
        public string sMa { get; set; }
        public string sTenSPF { get; set; }
        public string sParameter { get; set; }
        public string sMean { get; set; }
        public string sVD { get; set; }
        public byte[] bCode { get; set; }
        public string sDescription { get; set; }
        public System.DateTime tDatetime { get; set; }
        public string sFileName { get; set; }
        public int iFileSize { get; set; }
        public int iMaCN { get; set; }
    }
}
