//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class teee
    {
        public string ten { get; set; }
        public string TenHienThi { get; set; }
        public int Dai { get; set; }
        public int nDecima { get; set; }
        public string From_alia { get; set; }
        public string FILT_FIELD { get; set; }
        public string Type_HT { get; set; }
        public int Dai_HT { get; set; }
        public decimal f_identity { get; set; }
        public System.DateTime datetime { get; set; }
    }
}
