//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class tem_tygiatt200_1
    {
        public System.DateTime ngay_thc { get; set; }
        public decimal f_identity { get; set; }
        public string ma_tk0 { get; set; }
        public string ma_tk1 { get; set; }
        public decimal ps_no1 { get; set; }
        public decimal tien_usd { get; set; }
        public decimal ty_gia { get; set; }
        public string dv_do { get; set; }
        public int ma_kh { get; set; }
    }
}
