//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINHSAU
    {
        public int MA_REPO { get; set; }
        public double STT { get; set; }
        public string TINHSAU1 { get; set; }
        public int F_IDENTITY { get; set; }
        public System.DateTime DATETIME { get; set; }
    }
}
