//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpGVChenhLech1
    {
        public int ma_thb { get; set; }
        public Nullable<decimal> chenhlech { get; set; }
        public Nullable<decimal> sl { get; set; }
        public string ma_tk0000 { get; set; }
        public string ma_tk0 { get; set; }
        public string ma_tk1 { get; set; }
    }
}
