//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class tyle_pb_cn
    {
        public int vviec { get; set; }
        public int donvi { get; set; }
        public int bo_phan { get; set; }
        public decimal ty_le { get; set; }
        public int ws { get; set; }
        public short ma_user { get; set; }
        public short ma_user1 { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime datetime { get; set; }
        public decimal f_identity { get; set; }
    }
}
