//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class UFunct
    {
        public string Name { get; set; }
        public string StringOut { get; set; }
        public string ghi_chu { get; set; }
        public string VD { get; set; }
        public decimal f_identity { get; set; }
    }
}
