//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaDonDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpdateEffect
    {
        public string ma { get; set; }
        public string ten { get; set; }
        public byte loai { get; set; }
        public byte[] dinhkem { get; set; }
        public string tenFile { get; set; }
        public string caulenhSQL { get; set; }
        public string codethem { get; set; }
        public string codethemx { get; set; }
        public long dvcs1 { get; set; }
        public System.DateTime datetime { get; set; }
        public long f_identity { get; set; }
    }
}
